// Split out of main(): see docs/plans/main-split/README.md (Block C)
#include "app/frame/FrameCtx.h"

namespace app
{
   int sBenchB2Render3DIdx = -1;
   int sBenchB2OutputIdx = -1;
   std::string sBenchB2Variant;
   int sBenchB4CamIdx = -1;
   int sBenchB4LfoIdx = -1;
   std::string sBenchB9Scene;
   std::string sBenchB9Variant;
   double sBenchB9RssBuiltMb = -1.0;
   double sBenchB9RssStartMb = -1.0;
   double sBenchB9RssF32Mb = -1.0;
   double sBenchB9RssF152Mb = -1.0;
   double sBenchB9RssPeakMb = -1.0;
   double sBenchB9FootBuiltMb = -1.0;
   double sBenchB9FootF32Mb = -1.0;
   double sBenchB9FootF152Mb = -1.0;
   double sBenchB9FootPeakMb = -1.0;
   Bench::PercentileRing sBenchB9FrameMs;
   std::vector<std::pair<int, double>> sBenchB9RssSamples;
   std::vector<std::pair<int, double>> sBenchB9FootSamples;
   int sBenchB3OutputIdx = -1;
   int sBenchB3Render3DIdx = -1;
   int sBenchB3TwistIdx = -1;
   std::string sBenchB3Variant;
   int sBenchB3MonitorRefreshHz = 60;
   bool sBenchB3Unfocused = false;
   int sBenchB3TargetRateHz = 60;
   Bench::PercentileRing sBenchB3FrameMs;
   Bench::PercentileRing sBenchB3ProjIntervalRing;
   Bench::PercentileRing sBenchB3InputToPhotonFrames;
   double sBenchB3LastProjSwapMs = -1.0;
   int sBenchB3MissedVsyncCount = 0;
   int sBenchB3TotalVsyncCount = 0;
   AudioEngine::XrunCounts sBenchB3XrunBaseline;
   int sBenchB3PendingInputInjectFrame = -1;
   unsigned long long sBenchB3RevBeforeInject = 0;
   bool sBenchB3ProbePaused = false;
   bool sBenchB3I2PDryRun = false;
   double sBenchB3RssStartMb = -1.0;
   double sBenchB3RssPeakMb = -1.0;
   double sBenchB3FootStartMb = -1.0;
   double sBenchB3FootPeakMb = -1.0;
   double sBenchB7StartS = -1.0;
   double sBenchB7LastSampleS = -1.0;
   uint64_t sBenchB7LoadMark = 0;
   Bench::PercentileRing sBenchB7WinFrameMs;
   nlohmann::json sBenchB7Samples = nlohmann::json::array();
   std::string sBenchB8Variant;
   std::string sBenchB8SetupError;
   int sBenchB8TotalFrames = 600;
   int sBenchB8Windows = 0;
   bool sBenchB8WantCamera = false;
   bool sBenchB8WantSyphon = false;
   std::string sBenchB8CameraSkipReason;
   std::vector<int> sBenchB8ClipIdx;
   std::vector<int> sBenchB8OutputIdx;
   int sBenchB8SyphonIdx = -1;
   int sBenchB8CameraIdx = -1;
   bool sBenchB8Unfocused = false;
   bool sBenchB8Overlap = false;
   double sBenchB8RefreshMs = 1000.0 / 60.0;
   int sBenchB8OnVsyncFrames = 0;
   int sBenchB8IntervalFrames = 0;
   double sBenchB8FootStartMb = -1.0;
   double sBenchB8FootPeakMb = -1.0;
   double sBenchB8RssStartMb = -1.0;
   Bench::PercentileRing sBenchB8FrameMs;
   std::vector<BenchB8Window> sBenchB8Win;
   bool sBenchB8ForceOverlap = false;
   bool sBenchB8Sampling = false;
   std::string sBenchB6Variant;
   std::string sBenchB6Mode = "all";
   int sBenchB6TotalFrames = 600;
   bool sBenchB6Vsync = true;
   bool sBenchB6Unfocused = false;
   float sBenchB6GridMaxX = 0.0f;
   float sBenchB6GridMaxY = 0.0f;
   int sBenchB6DragNodeIndex = -1;
   double sBenchB6RssStartMb = -1.0;
   double sBenchB6FootStartMb = -1.0;
   double sBenchB6FootPeakMb = -1.0;
   Bench::PercentileRing sBenchB6FrameMs;
   Bench::PercentileRing sBenchB6PanFrameMs;
   Bench::PercentileRing sBenchB6ZoomFrameMs;
   Bench::PercentileRing sBenchB6DragFrameMs;
   Bench::PercentileRing sBenchB6DropdownFrameMs;
   double sBenchB6VisibleNodesSum = 0.0;
   double sBenchB6BodiesDrawnSum = 0.0;
   double sBenchB6OffscreenBodyMsSum = 0.0;
   int sBenchB6SampledFrames = 0;
   int sBenchB6DropdownOpenFrames = 0;
   double sBenchB6RefreshMs = 1000.0 / 60.0;
   int sBenchB6OnVsyncFrames = 0;
   int sBenchB6IntervalFrames = 0;
   ImVec2 sBenchB6DragStartPos(0.0f, 0.0f);
   float sBenchB6DragMovedPx = 0.0f;
   Bench::PercentileRing sStageModulation;
   Bench::PercentileRing sStageCook;
   Bench::PercentileRing sStageNodeBodies;
   Bench::PercentileRing sStageLinks;
   Bench::PercentileRing sStageCookAll;
   Bench::PercentileRing sStageEditorEnd;
   Bench::PercentileRing sStageImGuiRender;
   Bench::PercentileRing sStageProjectors;
   Bench::PercentileRing sStageSwap;
   Bench::GpuTimerRing sGpuTimerRing;
   Bench::PercentileRing sBenchB5cFrameMs;
   double sBenchB5cRssStartMb = -1.0;
   Bench::PercentileRing sBenchB2FrameMs;
   double sBenchB2RssStartMb = -1.0;
   unsigned long long sBenchB2FboAtF32 = 0;
   bool offlineClockDone = false;
   double sTailProjIntervalMs = -1.0;
}
