#pragma once
// Shared state for the stages split out of main(). See docs/plans/main-split/README.md (Block C).
#include "app/AppShared.h"
#include "app/frame/FrameTests.h"
#include <optional>

extern int g_InfiniteDuplicatePinIds; // defined outside namespace app
namespace app
{
struct BenchB8Window
   {
      Bench::PercentileRing presentMs;
      Bench::PercentileRing intervalMs;
      double lastSwapMs = -1.0;
      int refreshHz = 0;
      int monitorIndex = -1;
      int onVsync = 0; // intervals within 1.5 ms of a whole number of this display's refreshes
   };

struct FrameCtx
{
   double sMainRssStartMb{};
   double sMainFootStartMb{};
   double tPreWindow{};
   GLFWwindow* window{};
   double tWindowGl{};
   double tImGuiFonts{};
   double tScanners{};
   std::vector<std::pair<std::string, std::string>> allTypes{};
   bool selfTest{};
   char searchBuf[128]{};
   bool searchJustOpened{};
   bool searchPopupCentered{};
   bool searchPopupOpen{};
   bool searchRequestClose{};
   std::vector<std::string> clipboard{};
   std::vector<INode*> clipboardSources{};
   std::vector<int> clipboardOrigIndex{};
   std::vector<int> clipboardOrigGroup{};
   ClusterClipboard clipboardCluster{};
   double tSettingsInit{};
   double sFirstFrameEndMs{};
   int frameId{};
   bool splashEnabled{};
   bool isBenchB5c{};
   bool isBenchB2{};
   bool isBenchB7{};
   bool isBenchB3{};
   bool isBenchB4{};
   bool isBenchB6{};
   bool isBenchB9{};
   bool isBenchB8{};
   bool benchB6Stages{};
   bool benchStagesSample{};
   bool benchStagesCpuSample{};
   bool benchGpuPerNode{};
   const ImGuiViewport* vp{};
   float savedWheel{};
   float savedWheelH{};
   float kNodePanelWidth{};
   bool viewportBottom{};
   bool viewportRight{};
   bool matrixBottom{};
   bool matrixRight{};
   bool perfBottom{};
   bool perfRight{};
   bool arrangeBottom{};
   bool arrangeRight{};
   float graphHeight{};
   bool dropInsideArrangePanel{};
   std::optional<ConditionalStageTimer> timerNodeBodies;
   std::optional<Bench::ConditionalGpuStageTimer> timerNodeBodiesGpu;
   bool b6TrackVis{};
   int b6FrameVisibleCount{};
   int b6FrameBodiesDrawnCount{};
   double b6FrameOffscreenMs{};
   std::optional<ConditionalStageTimer> timerLinks;
   std::optional<Bench::ConditionalGpuStageTimer> timerLinksGpu;
   bool typing{};
   bool cmdOrCtrl{};
   double now{};
};

extern int sBenchB2Render3DIdx;
extern int sBenchB2OutputIdx;
extern std::string sBenchB2Variant;
extern int sBenchB4CamIdx;
extern int sBenchB4LfoIdx;
extern std::string sBenchB9Scene;
extern std::string sBenchB9Variant;
extern double sBenchB9RssBuiltMb;
extern double sBenchB9RssStartMb;
extern double sBenchB9RssF32Mb;
extern double sBenchB9RssF152Mb;
extern double sBenchB9RssPeakMb;
extern double sBenchB9FootBuiltMb;
extern double sBenchB9FootF32Mb;
extern double sBenchB9FootF152Mb;
extern double sBenchB9FootPeakMb;
extern Bench::PercentileRing sBenchB9FrameMs;
extern std::vector<std::pair<int, double>> sBenchB9RssSamples;
extern std::vector<std::pair<int, double>> sBenchB9FootSamples;
extern int sBenchB3OutputIdx;
extern int sBenchB3Render3DIdx;
extern int sBenchB3TwistIdx;
extern std::string sBenchB3Variant;
extern int sBenchB3MonitorRefreshHz;
extern bool sBenchB3Unfocused;
extern int sBenchB3TargetRateHz;
extern Bench::PercentileRing sBenchB3FrameMs;
extern Bench::PercentileRing sBenchB3ProjIntervalRing;
extern Bench::PercentileRing sBenchB3InputToPhotonFrames;
extern double sBenchB3LastProjSwapMs;
extern int sBenchB3MissedVsyncCount;
extern int sBenchB3TotalVsyncCount;
extern AudioEngine::XrunCounts sBenchB3XrunBaseline;
extern int sBenchB3PendingInputInjectFrame;
extern unsigned long long sBenchB3RevBeforeInject;
extern bool sBenchB3ProbePaused;
extern bool sBenchB3I2PDryRun;
extern double sBenchB3RssStartMb;
extern double sBenchB3RssPeakMb;
extern double sBenchB3FootStartMb;
extern double sBenchB3FootPeakMb;
extern double sBenchB7StartS;
extern double sBenchB7LastSampleS;
extern uint64_t sBenchB7LoadMark;
extern Bench::PercentileRing sBenchB7WinFrameMs;
extern nlohmann::json sBenchB7Samples;
extern std::string sBenchB8Variant;
extern std::string sBenchB8SetupError;
extern int sBenchB8TotalFrames;
extern int sBenchB8Windows;
extern bool sBenchB8WantCamera;
extern bool sBenchB8WantSyphon;
extern std::string sBenchB8CameraSkipReason;
extern std::vector<int> sBenchB8ClipIdx;
extern std::vector<int> sBenchB8OutputIdx;
extern int sBenchB8SyphonIdx;
extern int sBenchB8CameraIdx;
extern bool sBenchB8Unfocused;
extern bool sBenchB8Overlap;
extern double sBenchB8RefreshMs;
extern int sBenchB8OnVsyncFrames;
extern int sBenchB8IntervalFrames;
extern double sBenchB8FootStartMb;
extern double sBenchB8FootPeakMb;
extern double sBenchB8RssStartMb;
extern Bench::PercentileRing sBenchB8FrameMs;
extern std::vector<BenchB8Window> sBenchB8Win;
extern bool sBenchB8ForceOverlap;
extern bool sBenchB8Sampling;
extern std::string sBenchB6Variant;
extern std::string sBenchB6Mode;
extern int sBenchB6TotalFrames;
extern bool sBenchB6Vsync;
extern bool sBenchB6Unfocused;
extern float sBenchB6GridMaxX;
extern float sBenchB6GridMaxY;
extern int sBenchB6DragNodeIndex;
extern double sBenchB6RssStartMb;
extern double sBenchB6FootStartMb;
extern double sBenchB6FootPeakMb;
extern Bench::PercentileRing sBenchB6FrameMs;
extern Bench::PercentileRing sBenchB6PanFrameMs;
extern Bench::PercentileRing sBenchB6ZoomFrameMs;
extern Bench::PercentileRing sBenchB6DragFrameMs;
extern Bench::PercentileRing sBenchB6DropdownFrameMs;
extern double sBenchB6VisibleNodesSum;
extern double sBenchB6BodiesDrawnSum;
extern double sBenchB6OffscreenBodyMsSum;
extern int sBenchB6SampledFrames;
extern int sBenchB6DropdownOpenFrames;
extern double sBenchB6RefreshMs;
extern int sBenchB6OnVsyncFrames;
extern int sBenchB6IntervalFrames;
extern ImVec2 sBenchB6DragStartPos;
extern float sBenchB6DragMovedPx;
extern Bench::PercentileRing sStageModulation;
extern Bench::PercentileRing sStageCook;
extern Bench::PercentileRing sStageNodeBodies;
extern Bench::PercentileRing sStageLinks;
extern Bench::PercentileRing sStageCookAll;
extern Bench::PercentileRing sStageEditorEnd;
extern Bench::PercentileRing sStageImGuiRender;
extern Bench::PercentileRing sStageProjectors;
extern Bench::PercentileRing sStageSwap;
extern Bench::GpuTimerRing sGpuTimerRing;
extern Bench::PercentileRing sBenchB5cFrameMs;
extern double sBenchB5cRssStartMb;
extern Bench::PercentileRing sBenchB2FrameMs;
extern double sBenchB2RssStartMb;
extern unsigned long long sBenchB2FboAtF32;
extern bool offlineClockDone;
extern double sTailProjIntervalMs;

void ApplyUiScale(GLFWwindow* window, bool rendererReady);
int InitApp(FrameCtx& fc, int argc, char** argv);
void DrawFramePump(FrameCtx& fc);
void DrawMenuBar(FrameCtx& fc);
void DrawLayout(FrameCtx& fc);
void DrawDropHandling(FrameCtx& fc);
void DrawFrameTestsA(FrameCtx& fc);
void DrawBenchHarness(FrameCtx& fc);
void DrawNodeBodies(FrameCtx& fc);
void DrawLinks(FrameCtx& fc);
void DrawKeyboard(FrameCtx& fc);
void DrawPopupsA(FrameCtx& fc);
void DrawPopupsB(FrameCtx& fc);
void DrawSidePanels(FrameCtx& fc);
int DrawFloating(FrameCtx& fc);
int DrawTestsB(FrameCtx& fc);
void DrawPresent(FrameCtx& fc);
}
