#pragma once

// The Drum Sequencer's groove library: a table of 141 grooves in 10 categories.
// Ported from Ricardo Palmieri's fork (PR #24 to n1m21n/Infinite, commit
// a3ab7319), MIT licensed, with the same copyright terms as this repository.
// Titles were rewritten to generic style names (no song or artist names).
//
// Every groove has three parts, A (verse / main groove), B (bridge /
// breakdown) and C (chorus / fuller, often two bars ending in a fill). Every
// pattern assumes the lane layout below, which is also the order of the
// bundled kit in assets/drumkits/infinite-basic (see KitFile).
//
// Cells: X accent (1.0), x normal (0.75), o ghost (0.4), . rest.
// tones[lane]: semitones added to that lane's X cells (two-tone bells such as
// agogo / campana: X = low bell, x = high bell).
// Grooves are style sketches, not transcriptions of any recording.

#include "audio/MusicTime.h"

namespace DrumPatterns
{
   struct Part
   {
      int steps;            // this part's length
      const char* lanes[8]; // nullptr = lane silent in this part
   };

   struct Groove
   {
      const char* category;
      const char* name;
      int bpm;          // suggested tempo, shown only
      int rate;         // MusicTime::RateDivision (an int, see static_asserts below)
      float swing;      // 0..1, the node's swing
      Part parts[3];    // A, B, C
      float tones[8];
   };

   inline const char* PartName(int part)
   {
      static const char* const kNames[3] = { "A verse", "B bridge", "C chorus" };
      return (part >= 0 && part < 3) ? kNames[part] : "";
   }

   inline const char* LaneRole(int lane)
   {
      static const char* const kRoles[8] = { "kick", "snare", "closed hat", "open hat",
                                             "clap / rim", "low tom / conga", "high tom / conga", "bell / ride" };
      return (lane >= 0 && lane < 8) ? kRoles[lane] : "";
   }

   inline const char* KitFile(int lane)
   {
      static const char* const kFiles[8] = { "01-kick.wav", "02-snare.wav", "03-closed-hat.wav", "04-open-hat.wav",
                                             "05-clap.wav", "06-low-tom.wav", "07-high-tom.wav", "08-bell.wav" };
      return (lane >= 0 && lane < 8) ? kFiles[lane] : "";
   }

   inline float CellVelocity(char c)
   {
      return c == 'X' ? 1.0f : (c == 'x' ? 0.75f : (c == 'o' ? 0.4f : 0.0f));
   }

   inline const char* const* Categories(int& count)
   {
      static const char* const kCats[] = {
         "Rock & Pop", "Funk & Breaks", "Hip Hop", "Electronic", "Latin & Caribbean", "Brazil", "Middle East & North Africa", "India", "Africa & World", "Jazz",
      };
      count = (int)(sizeof(kCats) / sizeof(kCats[0]));
      return kCats;
   }

   inline const Groove* All(int& count)
   {
      static const Groove kGrooves[] = {
         { "Rock & Pop", "Rock (8th hats)", 110, 12, 0.00f,
           { { 16, { "X.......X.......", "....X.......X...", "x.x.x.x.x.x.x.x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X.......X.......", nullptr, nullptr, nullptr, "....X.......X...", "x.x.x.x.x.x.x.x.", nullptr, nullptr } },
             { 32, { "X.......X.x.....X.......X.x.....", "....X.......X.......X.....x.XxXX", nullptr, "X...............................", nullptr, "...............................x", "..............................x.", "x.x.x.x.x.x.x.x.x.x.x.x.x.x....." } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Rock & Pop", "Rock (driving)", 128, 12, 0.00f,
           { { 16, { "X.x.....X.x...x.", "....X.......X...", "X.x.x.x.X.x.x.x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X.......X.......", "............X...", "x.x.x.x.x.x.x.x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X.x...x.X.x...x.", "....X.......X...", nullptr, "X...............", nullptr, nullptr, nullptr, "X.x.X.x.X.x.X.x." } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Rock & Pop", "Pop (16th hats)", 100, 12, 0.00f,
           { { 16, { "X.....x.X.......", "....X.......X...", "XoxoXoxoXoxoXoxo", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X...............", nullptr, "x.x.x.x.x.x.x.x.", nullptr, "....X.......X...", nullptr, nullptr, nullptr } },
             { 32, { "X.....x.X.x.....X.....x.X.......", "....X.......X.......X.......X.XX", "XoxXXoxXXoxXXoxXXoxXXoxXXoxX....", "X...............................", "....X.......X.......X.......X...", nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Rock & Pop", "Half-time", 140, 12, 0.00f,
           { { 16, { "X.........x.....", "........X.......", "x.x.x.x.x.x.x.x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X...............", "........X.......", nullptr, nullptr, nullptr, nullptr, nullptr, "x.x.x.x.x.x.x.x." } },
             { 16, { "X.....x...x.....", "........X.....o.", nullptr, "X...............", nullptr, nullptr, nullptr, "X.x.x.x.X.x.x.x." } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Rock & Pop", "Four on the snare", 120, 12, 0.00f,
           { { 16, { "X.....x.X.....x.", "X...X...X...X...", "x.x.x.x.x.x.x.x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X.......X.......", nullptr, "x.x.x.x.x.x.x.x.", nullptr, "....X.......X...", nullptr, nullptr, nullptr } },
             { 16, { "X.....x.X.....x.", "X...X...X...X...", ".xx..xx..xx..xx.", "X...............", "X...X...X...X...", nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Rock & Pop", "Stomp-stomp-clap", 81, 12, 0.00f,
           { { 16, { "X.X.....X.X.....", nullptr, nullptr, nullptr, "....X.......X...", nullptr, nullptr, nullptr } },
             { 16, { "X.X.....X.X.....", nullptr, nullptr, nullptr, "....X.......X...", "X.X.....X.X.....", nullptr, nullptr } },
             { 16, { "X.X.....X.X.....", "....X.......X...", nullptr, "X...............", "....X.......X...", nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Rock & Pop", "Straight backbeat", 117, 12, 0.00f,
           { { 16, { "X.......X.......", "....X.......X...", "x.x.x.x.x.x.x.x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X.......X.......", nullptr, "x.x.x.x.x.x.x.x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X.......X.......", "....X.......X...", "xxxxxxxxxxxxxxxx", nullptr, "....X.......X...", nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Rock & Pop", "Girl-group backbeat", 128, 12, 0.00f,
           { { 16, { "X.....x.x.......", "............X...", "x.x.x.x.x.x.x.x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X.....x.x.......", "............X...", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X.....x.x.......", "....X.......X...", "x.x.x.x.x.x.x.x.", "X...............", "....X.......X...", nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Rock & Pop", "Tom clave beat", 110, 12, 0.00f,
           { { 16, { nullptr, nullptr, "x.x.x.x.x.x.x.x.", nullptr, nullptr, "X..x..x...x.x...", "X..x..x...x.x...", nullptr } },
             { 16, { nullptr, nullptr, "x.x.x.x.x.x.x.x.", nullptr, nullptr, "X..x..x...x.x...", nullptr, nullptr } },
             { 16, { "X.......X.......", "....X.......X...", "xxxxxxxxxxxxxxxx", nullptr, nullptr, "X..x..x...x.x...", "X..x..x...x.x...", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Rock & Pop", "Motorik", 125, 12, 0.00f,
           { { 16, { "X.......X.x.....", "....X.......X...", "x.x.x.x.x.x.x.x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X.......X.x.....", nullptr, "x.x.x.x.x.x.x.x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X.......X.x.....", "....X.......X...", "xxxxxxxxxxxxxxxx", "X...............", nullptr, nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Rock & Pop", "Disco", 120, 12, 0.00f,
           { { 16, { "X...X...X...X...", "....X.......X...", "x...x...x...x...", "..X...X...X...X.", nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X...X...X...X...", nullptr, "xx.xxx.xxx.xxx.x", "..X...X...X...X.", nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X...X...X...X...", "....X.......X...", "xx.xxx.xxx.xxx.x", "..X...X...X...X.", "....X.......X...", nullptr, nullptr, "X..............." } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Rock & Pop", "Synthwave (gated snare)", 100, 12, 0.00f,
           { { 16, { "X.....x.X.x.....", "....X.......X...", "x.x.x.x.x.x.x.x.", nullptr, "....X.......X...", nullptr, nullptr, nullptr } },
             { 16, { "X.......X.......", nullptr, "x.x.x.x.x.x.x.x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 32, { "X.....x.X.x.....X.....x.X.x.....", "....X.......X.......X.......X.X.", "xxxxxxxxxxxxxxxxxxxxxxxxxxxx....", "X...............................", "....X.......X.......X.......X...", "...............................X", nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Rock & Pop", "Shuffle (blues)", 96, 11, 0.00f,
           { { 12, { "X.....X.....", "...X.....X..", "X.xX.xX.xX.x", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 12, { "X...........", "...o.....o..", "X.xX.xX.xX.x", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 12, { "X.....X...x.", "...X.....X..", nullptr, "X...........", nullptr, nullptr, nullptr, "X.xX.xX.xX.x" } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Rock & Pop", "Half-time shuffle (ghost notes)", 86, 11, 0.00f,
           { { 24, { "X..........xX...........", ".o..o.X...o..o..o.X...o.", "X.xX.xX.xX.xX.xX.xX.xX.x", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 24, { "X...........X...........", "......X...........X.....", "X.xX.xX.xX.xX.xX.xX.xX.x", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 24, { "X..........xX.....x.....", ".o..o.X...o..o..o.X..oXX", nullptr, "X.......................", nullptr, nullptr, nullptr, "X.xX.xX.xX.xX.xX.xX.xX.." } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Rock & Pop", "Punk", 180, 12, 0.00f,
           { { 16, { "X.......X.x.....", "....X.......X...", "X.X.X.X.X.X.X.X.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X.X.X.X.X.X.X.X.", "....X.......X...", nullptr, nullptr, nullptr, nullptr, nullptr, "X...X...X...X..." } },
             { 16, { "X.......X.x.....", "....X.......X...", nullptr, "X.X.X.X.X.X.X.X.", nullptr, nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Rock & Pop", "Skank beat (punk / thrash)", 190, 12, 0.00f,
           { { 8, { "X...X...", "..X...X.", nullptr, nullptr, nullptr, nullptr, nullptr, "X.x.X.x." } },
             { 8, { "X.......", "....X...", nullptr, nullptr, nullptr, nullptr, nullptr, "x.x.x.x." } },
             { 8, { "X...X...", "..X...X.", nullptr, "X.X.X.X.", nullptr, nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Rock & Pop", "Gallop (metal)", 170, 12, 0.00f,
           { { 16, { "X.XXX.XXX.XXX.XX", "....X.......X...", nullptr, nullptr, nullptr, nullptr, nullptr, "x.x.x.x.x.x.x.x." } },
             { 16, { "X.......X.......", "........X.......", nullptr, nullptr, nullptr, nullptr, nullptr, "x.x.x.x.x.x.x.x." } },
             { 16, { "X.XXX.XXX.XXX.XX", "....X.......X...", nullptr, "X...X...X...X...", nullptr, nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Rock & Pop", "Double kick (metal)", 180, 12, 0.00f,
           { { 16, { "xxxxxxxxxxxxxxxx", "....X.......X...", nullptr, nullptr, nullptr, nullptr, nullptr, "X...X...X...X..." } },
             { 16, { "X.......X.......", "........X.......", nullptr, nullptr, nullptr, nullptr, nullptr, "x.x.x.x.x.x.x.x." } },
             { 16, { "xxxxxxxxxxxxxxxx", "....X.......X...", nullptr, "X...X...X...X...", nullptr, "..............XX", nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Rock & Pop", "Blast beat", 200, 12, 0.00f,
           { { 8, { "X.X.X.X.", "X.X.X.X.", nullptr, nullptr, nullptr, nullptr, nullptr, "X.X.X.X." } },
             { 8, { "xxxxxxxx", "....X...", nullptr, nullptr, nullptr, nullptr, nullptr, "X...X..." } },
             { 8, { "X.X.X.X.", "X.X.X.X.", nullptr, "X.X.X.X.", nullptr, nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Funk & Breaks", "Funk (16th hats, ghosts)", 100, 12, 0.00f,
           { { 16, { "X.X.......X..x..", "....X..o.o..X..o", "xxxxxxxxxxxxxxxx", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X.........X.....", "....X.......X...", "x.x.x.x.x.x.x.x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 32, { "X.X.......X..x..X.X.......X.....", "....X..o.o..X..o....X..o.o..XoXX", "xxxxxxxxxxxxxxxxxxxxxxxxxxxx....", "..............X.................", nullptr, nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Funk & Breaks", "Funk (linear)", 96, 12, 0.00f,
           { { 16, { "X.....X..X....X.", "..o.X...o..oX...", ".X.X...xx.X..x..", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X.....X.........", "....X.......X...", ".X.X.X.X.X.X.X.X", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X.....X..X....X.", "..o.X...o..oX.oX", ".X.X...xx.X..x..", "X...............", nullptr, nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Funk & Breaks", "Funk (syncopated, open hat)", 100, 12, 0.00f,
           { { 16, { "X.X.......X..X..", "....X..o.o.oX..o", "xxxxxxx.xxxxxxxx", ".......X........", nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X.X.......X.....", "....X.......X...", "xxxxxxxxxxxxxxxx", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 32, { "X.X.......X..X..X.X.......X.....", "....X..o.o.oX..o....X..o.o.oXoXo", "xxxxxxx.xxxxxxxxxxxxxxx.xxxx....", ".......X...............X........", nullptr, nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Funk & Breaks", "Two-bar break", 136, 12, 0.00f,
           { { 32, { "X.X.......XX....X.X.......X.....", "....X..o.o..X..o....X..o.o....X.", nullptr, nullptr, nullptr, nullptr, nullptr, "x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x." } },
             { 32, { "X.X.......XX....X.X.......X.....", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, "x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x." } },
             { 32, { "X.X.......XX......XX......X.....", "....X..o.o..X..o.o..X..o.o....X.", nullptr, "........................X.......", nullptr, nullptr, nullptr, "x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x." } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Funk & Breaks", "Funk break (open-hat backbeat)", 96, 12, 0.00f,
           { { 16, { "X......XX.X.....", "....X.......X...", "x.x.x.x.x.x...x.", "............X...", nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X......XX.X.....", nullptr, "x.x.x.x.x.x...x.", "............X...", nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X......XX.X.....", "....X.......X..o", "xxxxxxxxxxxx..xx", "............X...", nullptr, nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Funk & Breaks", "Heavy slow break", 72, 12, 0.00f,
           { { 16, { "X.X......X.X....", "....X.......X...", "x.x.x.x.x.x.x.x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X.X......X.X....", nullptr, "x.x.x.x.x.x.x.x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X.X......X.X....", "....X.......X...", nullptr, "x.x.x.x.x.x.x.x.", nullptr, nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Funk & Breaks", "Conga break", 116, 12, 0.00f,
           { { 16, { "X.........X.....", "....X.......X...", "x.x.x.x.x.x.x.x.", nullptr, nullptr, "...xx......xx...", "x.xx..x.x.xx..x.", nullptr } },
             { 16, { nullptr, nullptr, nullptr, nullptr, nullptr, "...xx......xx...", "x.xx..x.x.xx..x.", nullptr } },
             { 16, { "X.....X...X.....", "....X.......X..o", "xxxxxxxxxxxxxxxx", "X...............", nullptr, "...xx......xx...", "x.xx..x.x.xx..x.", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Funk & Breaks", "Funk (ghost snare, 8th hats)", 110, 12, 0.00f,
           { { 16, { "X.......X.X.....", "....X..o......X.", "x.x.x.x.x.x.x.x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X.......X.......", nullptr, "x.x.x.x.x.x.x.x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X.....X.X.X.....", "....X..o..o...X.", "xxxxxxxxxxxxxxxx", "X...............", nullptr, nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Funk & Breaks", "Afrobeat", 108, 12, 0.00f,
           { { 16, { "X.....X...X.X...", "..o.X.o..o.oX..o", "x.xxx.xxx.xxx.xx", "...............X", nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X.....X.........", nullptr, "x.xxx.xxx.xxx.xx", nullptr, nullptr, nullptr, nullptr, "X.X.XX.X.X.X.X.." } },
             { 16, { "X.....X...X.X...", "..o.X.o..o.oX..o", "x.xxx.xxx.xxx.xx", "...............X", nullptr, nullptr, "......x...x.....", "X.X.XX.X.X.X.X.." } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Funk & Breaks", "Second line (New Orleans)", 100, 12, 0.00f,
           { { 16, { "X.....X...X.X...", "o.oXo.ooX.oooXo.", nullptr, nullptr, nullptr, nullptr, nullptr, "X...X...X...X..." } },
             { 16, { "X.....X...X.X...", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, "X...X...X...X..." } },
             { 16, { "X.....X...X.X...", "o.oXo.ooX.oooXoX", nullptr, "X...............", nullptr, nullptr, nullptr, "X...X...X...X..." } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Funk & Breaks", "Breakbeat (nu-skool)", 132, 12, 0.00f,
           { { 16, { "X.........X.....", "....X.......X...", "x.x.x.xxx.x.x.x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X...............", nullptr, "x.x.x.xxx.x.x.x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 32, { "X.....X...X.....X.........X.....", "....X.......X.......X..o.o..XXXX", "x.x.x.xxx.x.x.x.x.x.x.xxx.x.....", "X...............................", nullptr, nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Funk & Breaks", "Big beat", 136, 12, 0.00f,
           { { 16, { "X.X.......XX....", "....X..o.X..X...", "x.x.x.x.x.x.x.x.", "..............X.", nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X.........X.....", "............X...", "x.x.x.x.x.x.x.x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X.X.......XX....", "....X..o.X..X...", "xxxxxxxxxxxxxxxx", "X.............X.", "....X.......X...", nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Funk & Breaks", "Big beat 2", 128, 12, 0.00f,
           { { 16, { "X.....X.X.....X.", "....X.......X...", "xxXxxxXxxxXxxxXx", nullptr, "....X.......X...", nullptr, nullptr, nullptr } },
             { 16, { "X...............", nullptr, "xxXxxxXxxxXxxxXx", nullptr, "....X.......X...", nullptr, nullptr, nullptr } },
             { 16, { "X.....X.X.....X.", "....X.......X.XX", "xxXxxxXxxxXxxxXx", "X...............", "....X.......X...", "..............XX", nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Hip Hop", "Boom bap", 90, 12, 0.35f,
           { { 16, { "X......X..X.....", "....X.......X...", "x.x.x.x.x.x.x.x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X.........X.....", nullptr, "x.x.x.x.x.x.x.x.", nullptr, "....X.......X...", nullptr, nullptr, nullptr } },
             { 16, { "X..X...X..X..X..", "....X.......X...", "x.x.x.x.x.x.x.xx", "..............X.", nullptr, nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Hip Hop", "Lo-fi (loose swing)", 84, 12, 0.55f,
           { { 16, { "X.....X...X..x..", "....X.......X..o", "x.x.x.x.x.xxx.x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X.........X.....", nullptr, "x.x.x.x.x.x.x.x.", nullptr, "....X.......X...", nullptr, nullptr, nullptr } },
             { 16, { "X.....X...X..x..", "....X..o....X..o", "x.xxx.x.x.xxx.x.", nullptr, "....X.......X...", nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Hip Hop", "G-funk", 92, 12, 0.30f,
           { { 16, { "X.X.......X.....", "....X.......X...", "xxxxxxxxxxxxxxxx", nullptr, "....X.......X...", nullptr, nullptr, nullptr } },
             { 16, { "X.........X.....", nullptr, "xxxxxxxxxxxxxxxx", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X.X...X...X.....", "....X.......X...", "xxxxxxxxxxxxxxxx", "..............X.", "....X.......X...", nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Hip Hop", "Electro", 127, 12, 0.00f,
           { { 16, { "X.....X.......X.", nullptr, "xxxxxxxxxxxxxxxx", nullptr, "....X.......X...", nullptr, nullptr, "X..X..X...X..X.." } },
             { 16, { "X.....X.......X.", nullptr, "xxxxxxxxxxxxxxxx", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X.....X.......X.", "....X.......X...", "xxxxxxxxxxxxxxxx", nullptr, "....X.......X...", nullptr, "............X.XX", "X..X..X...X..X.." } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Hip Hop", "Trap", 140, 12, 0.00f,
           { { 32, { "X......X..X.....X.........X.X...", "........X...............X.......", "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "..............X.................", nullptr, nullptr, nullptr, nullptr } },
             { 32, { "X...............................", "........X...............X.......", "x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 32, { "X......X..X.....X..X......X.X...", "........X...............X.....oo", "xxxxxxxxxxxxxxxxxxxxxxxxXXXXXXXX", "..............X.................", "........X...............X.......", nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Hip Hop", "Trap (triplet hats)", 140, 14, 0.00f,
           { { 24, { "X.........X.....X.......", "............X...........", "xxxxxxxxxxxxxxxxxxxxxxxx", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 24, { "X.......................", "............X...........", "x..x..x..x..x..x..x..x..", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 24, { "X.....X...X.....X..X....", "............X...........", "xxxxxxxxxxxxxxxxXXXXXXXX", nullptr, "............X...........", nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Hip Hop", "UK drill", 142, 12, 0.00f,
           { { 32, { "X.........X........X....X.......", "........X....X..........X.......", "x..x..x.x..x..x.x..x..x.x..x..x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 32, { "X...............................", "........X...............X.......", "x..x..x.x..x..x.x..x..x.x..x..x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 32, { "X.........X........X....X..X....", "........X....X..........X....X.X", "x..x..x.x..x..x.x..x..x.xxxxxxxx", nullptr, nullptr, nullptr, "..............................x.", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Hip Hop", "Miami bass", 130, 12, 0.00f,
           { { 16, { "X......X..X.....", nullptr, "xxxxxxxxxxxxxxxx", nullptr, "....X.......X...", nullptr, nullptr, nullptr } },
             { 16, { "X...............", nullptr, "x.x.x.x.x.x.x.x.", nullptr, "....X.......X...", nullptr, nullptr, nullptr } },
             { 16, { "X......X..X...X.", "....X.......X..X", "xxxxxxxxxxxxxxxx", nullptr, "....X.......X...", nullptr, nullptr, "..X...X...X...X." } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Hip Hop", "Baltimore club", 130, 12, 0.00f,
           { { 16, { "X...X...X..X.XX.", nullptr, "x.x.x.x.x.x.x.x.", nullptr, "....X.......X...", nullptr, nullptr, nullptr } },
             { 16, { "X.......X.......", nullptr, nullptr, nullptr, "....X.......X...", nullptr, nullptr, nullptr } },
             { 16, { "X...X...X..X.XX.", "....X.......X...", "xxxxxxxxxxxxxxxx", nullptr, "....X.......X.XX", nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Hip Hop", "Jersey club", 140, 12, 0.00f,
           { { 16, { "X..X..X.X.X.X...", nullptr, "x.x.x.x.x.x.x.x.", nullptr, "....X.......X...", nullptr, nullptr, nullptr } },
             { 16, { "X.......X.......", nullptr, nullptr, nullptr, "....X.......X...", nullptr, nullptr, nullptr } },
             { 16, { "X..X..X.X.X.X.X.", nullptr, "xxxxxxxxxxxxxxxx", nullptr, "....X.......X...", nullptr, "...x..x....x..x.", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Hip Hop", "Footwork / juke", 160, 12, 0.00f,
           { { 16, { "X..X..X...X..X..", nullptr, "x.x.x.x.x.x.x.x.", nullptr, "....X.......X...", nullptr, "...x..x....x..x.", nullptr } },
             { 16, { "X..X..X.........", nullptr, nullptr, nullptr, "....X.......X...", nullptr, nullptr, nullptr } },
             { 16, { "X..X..X...X..XX.", "............X.XX", "xxxxxxxxxxxxxxxx", nullptr, "....X.......X...", nullptr, "...x..x....x..xx", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Electronic", "House", 124, 12, 0.00f,
           { { 16, { "X...X...X...X...", nullptr, "xo.oxo.oxo.oxo.o", "..X...X...X...X.", "....X.......X...", nullptr, nullptr, nullptr } },
             { 16, { nullptr, nullptr, "xo.oxo.oxo.oxo.o", "..X...X...X...X.", "....X.......X...", nullptr, nullptr, nullptr } },
             { 16, { "X...X...X...X...", "....X.......X...", "xxxxxxxxxxxxxxxx", "..X...X...X...X.", "....X.......X...", nullptr, "...x......x.....", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Electronic", "Deep house (shuffled)", 120, 12, 0.30f,
           { { 16, { "X...X...X...X...", nullptr, ".x.x.x.x.x.x.x.x", nullptr, "....X.......X...", nullptr, "...x......x.....", nullptr } },
             { 16, { nullptr, nullptr, ".x.x.x.x.x.x.x.x", nullptr, "....X.......X...", nullptr, nullptr, nullptr } },
             { 16, { "X...X...X...X...", nullptr, ".x.x.x.x.x.x.x.x", "..X...X...X...X.", "....X.......X...", nullptr, "...x..x...x....x", "..x.......x....." } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Electronic", "Techno", 130, 12, 0.00f,
           { { 16, { "X...X...X...X...", nullptr, "..x...x...x...x.", nullptr, "..............x.", nullptr, "...x..x....x....", nullptr } },
             { 16, { nullptr, nullptr, "..x...x...x...x.", nullptr, "....X.......X...", nullptr, "...x..x....x....", nullptr } },
             { 16, { "X...X...X...X...", nullptr, "xxXxxxXxxxXxxxXx", "..X...X...X...X.", "....X.......X...", nullptr, "...x..x....x..x.", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Electronic", "Techno (rolling)", 134, 12, 0.00f,
           { { 16, { "X...X...X...X...", nullptr, "xxXxxxXxxxXxxxXx", "..X...X...X...X.", "....X.......X...", nullptr, nullptr, nullptr } },
             { 16, { "X...............", nullptr, "xxXxxxXxxxXxxxXx", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X...X...X...X..x", nullptr, "xxXxxxXxxxXxxxXx", "..X...X...X...X.", "....X.......X...", ".x....x..x....x.", nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Electronic", "Minimal", 126, 12, 0.00f,
           { { 16, { "X...X...X...X...", nullptr, "..x...x...x...x.", nullptr, "..........x.....", nullptr, ".x.....x....x...", nullptr } },
             { 16, { nullptr, nullptr, "..x...x...x...x.", nullptr, "..........x.....", nullptr, ".x.....x....x...", nullptr } },
             { 16, { "X...X...X...X...", nullptr, ".xx..xx..xx..xx.", nullptr, "....X.....x.X...", nullptr, ".x.....x.x..x..x", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Electronic", "Acid house", 122, 12, 0.00f,
           { { 16, { "X...X...X...X...", nullptr, "xxXxxxXxxxXxxxXx", nullptr, "....X.......X...", nullptr, nullptr, nullptr } },
             { 16, { "X.......X.......", nullptr, "xxXxxxXxxxXxxxXx", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X...X...X...X...", nullptr, "xxXxxxXxxxXxxxXx", "..X...X...X...X.", "....X.......X...", nullptr, nullptr, "..x...x...x...x." } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Electronic", "Detroit techno", 128, 12, 0.00f,
           { { 16, { "X...X...X...X...", "............X..o", "..X...X...X...X.", nullptr, "....X.......X...", nullptr, nullptr, "X.x.X.x.X.x.X.x." } },
             { 16, { "X...X...X...X...", nullptr, "..X...X...X...X.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X...X...X...X...", "....X.......X.oo", "xxXxxxXxxxXxxxXx", "X...............", "....X.......X...", nullptr, nullptr, "X.x.X.x.X.x.X.x." } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Electronic", "Trance", 138, 12, 0.00f,
           { { 16, { "X...X...X...X...", nullptr, "x.x.x.x.x.x.x.x.", "..X...X...X...X.", "....X.......X...", nullptr, nullptr, nullptr } },
             { 16, { nullptr, nullptr, "x.x.x.x.x.x.x.x.", "..X...X...X...X.", nullptr, nullptr, nullptr, nullptr } },
             { 32, { "X...X...X...X...X...X...X...X...", "........................XXXXXXXX", "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "X.X...X...X...X...X...X...X...X.", "....X.......X.......X.......X...", nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Electronic", "Psytrance", 145, 12, 0.00f,
           { { 16, { "X...X...X...X...", nullptr, "..x...x...x...x.", nullptr, "....X.......X...", nullptr, nullptr, nullptr } },
             { 16, { nullptr, nullptr, "..x...x...x...x.", nullptr, nullptr, nullptr, ".x.x.x.x.x.x.x.x", nullptr } },
             { 16, { "X...X...X...X...", nullptr, "xxXxxxXxxxXxxxXx", "..X...X...X...X.", "....X.......X...", nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Electronic", "Hardstyle", 150, 12, 0.00f,
           { { 16, { "X...X...X...X...", nullptr, nullptr, "..X...X...X...X.", "....X.......X...", nullptr, nullptr, nullptr } },
             { 16, { nullptr, nullptr, nullptr, "..X...X...X...X.", "....X.......X...", nullptr, nullptr, nullptr } },
             { 16, { "X...X...X...X...", nullptr, "xxxxxxxxxxxxxxxx", "..X...X...X...X.", "....X.......X...", nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Electronic", "Gabber", 180, 12, 0.00f,
           { { 16, { "X...X...X...X...", nullptr, nullptr, "..x...x...x...x.", nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X.......X.......", nullptr, nullptr, "..x...x...x...x.", nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X...X...X...X..X", nullptr, nullptr, "..X...X...X...X.", "....X.......X...", nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Electronic", "UK garage (2-step)", 132, 12, 0.45f,
           { { 16, { "X.........X.....", "....X.......X...", ".x.x.x.x.x.x.x.x", nullptr, nullptr, nullptr, "...x.....x......", nullptr } },
             { 16, { "X...............", nullptr, ".x.x.x.x.x.x.x.x", nullptr, "....X.......X...", nullptr, nullptr, nullptr } },
             { 16, { "X......X..X.....", "....X.......X..o", ".x.x.x.x.x.x.x.x", "..X.......X.....", "....X.......X...", nullptr, "...x.....x......", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Electronic", "Speed garage (4x4)", 132, 12, 0.35f,
           { { 16, { "X...X...X...X...", "....X.......X...", ".x.x.x.x.x.x.x.x", "..X...X...X...X.", nullptr, nullptr, nullptr, nullptr } },
             { 16, { nullptr, nullptr, ".x.x.x.x.x.x.x.x", "..X...X...X...X.", nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X...X...X...X...", "....X.......X...", ".x.x.x.x.x.x.x.x", "..X...X...X...X.", "....X.......X...", nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Electronic", "Drum & bass (two-step)", 172, 12, 0.00f,
           { { 16, { "X.........X.....", "....X.......X...", "x.x.x.x.x.x.x.x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X...............", "............X...", nullptr, nullptr, nullptr, nullptr, nullptr, "x.x.x.x.x.x.x.x." } },
             { 32, { "X.........X.....X.........X...X.", "....X.......X.......X..o....X.XX", "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx..", "X...............................", nullptr, nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Electronic", "Jungle (chopped break)", 165, 12, 0.00f,
           { { 32, { "X.X.......XX....X.X......X......", "....X..o.o..X..o.o..X..o.o.X..X.", nullptr, nullptr, nullptr, nullptr, nullptr, "x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x." } },
             { 32, { "X.................X.............", "........X...............X.......", nullptr, nullptr, nullptr, nullptr, nullptr, "x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x." } },
             { 32, { "X.X.......XX....X.X...X..X......", "....X..o.oX.X..o.o..X..oXoXoXXXX", nullptr, "X...............................", nullptr, nullptr, nullptr, "x.x.x.x.x.x.x.x.x.x.x.x.x.x....." } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Electronic", "Dubstep (half-time)", 140, 12, 0.00f,
           { { 32, { "X.................X.............", nullptr, "x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.xx", nullptr, "........X...............X.......", nullptr, nullptr, nullptr } },
             { 32, { "X...............................", nullptr, nullptr, nullptr, "........X...............X.......", nullptr, nullptr, nullptr } },
             { 32, { "X.....X...........X...........X.", "........X...............X.....XX", "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "X...............................", "........X...............X.......", nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Electronic", "Grime", 140, 12, 0.00f,
           { { 32, { "X.................X...X.........", "........X...............X.......", "x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 32, { "X...............................", "........X...............X.......", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 32, { "X.....X...........X...X.......X.", "........X...............X....X..", "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", nullptr, nullptr, nullptr, "............................X.X.", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Electronic", "Trip-hop", 77, 12, 0.20f,
           { { 16, { "X..x......X.....", "....X.......X...", "x.xxx.xxx.xxx.xx", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X..x......X.....", nullptr, "x.xxx.xxx.xxx.xx", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X..x......X..x..", "....X.......X..o", "x.xxx.xxx.xxx.xx", "X...............", "....X.......X...", nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Electronic", "Trip-hop 2", 85, 12, 0.25f,
           { { 16, { "X......xX.....x.", "....X.......X..o", "x.x.x.x.x.x.x.x.", nullptr, nullptr, nullptr, nullptr, "..............x." } },
             { 16, { "X.......X.......", nullptr, "x.x.x.x.x.x.x.x.", nullptr, "....X.......X...", nullptr, nullptr, nullptr } },
             { 16, { "X......xX.....x.", "....X.......X..o", "xxxxxxxxxxxxxxxx", "X...............", nullptr, nullptr, nullptr, "..............x." } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Electronic", "Industrial stomp", 80, 12, 0.00f,
           { { 16, { "X.......X.X.....", "....X.......X...", "x...x...x...x...", nullptr, "....X.......X...", nullptr, nullptr, nullptr } },
             { 16, { "X.......X.......", nullptr, "x...x...x...x...", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X.....X.X.X.....", "....X.......X...", "x.x.x.x.x.x.x.x.", "X...............", "....X.......X...", "..............XX", nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Electronic", "Glitch-pop pulse", 134, 12, 0.00f,
           { { 16, { "X...X...X...X...", nullptr, "xxxxxxxxxxxxxxxx", nullptr, "....X.......X...", nullptr, "..x...x...x...x.", nullptr } },
             { 16, { nullptr, nullptr, "xxxxxxxxxxxxxxxx", nullptr, nullptr, nullptr, "..x...x...x...x.", nullptr } },
             { 16, { "X...X...X...X...", "....X.......X...", "xxxxxxxxxxxxxxxx", "..X...X...X...X.", "....X.......X...", nullptr, "..x...x...x...xx", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Electronic", "IDM (glitch)", 120, 12, 0.00f,
           { { 16, { "X..x.X....X.x...", "...oX....oX....X", "xx.x.xxxx.x.xxx.", nullptr, nullptr, nullptr, ".x....x....x.x..", nullptr } },
             { 16, { "X.........x.....", nullptr, "x.xx.x.x..xxx.x.", nullptr, nullptr, nullptr, ".x....x....x.x..", nullptr } },
             { 16, { "X..x.X.x..X.x..X", "...oX..o.oX..oXX", "xxxxxxxxxxxxxxxx", nullptr, nullptr, ".....x........x.", ".x....x....x.x.x", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Electronic", "Downtempo", 90, 12, 0.20f,
           { { 16, { "X.....x..X......", "....X.......X...", "x.x.x.x.x.x.x.x.", nullptr, "..............x.", nullptr, nullptr, nullptr } },
             { 16, { "X...............", nullptr, "x.x.x.x.x.x.x.x.", nullptr, "....X.......X...", nullptr, nullptr, nullptr } },
             { 16, { "X.....x..X....x.", "....X.......X..o", "xxxxxxxxxxxxxxxx", nullptr, "..............x.", nullptr, nullptr, "X..............." } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Electronic", "Ambient pulse", 70, 12, 0.00f,
           { { 16, { "X...............", nullptr, nullptr, nullptr, nullptr, nullptr, "........x.......", "....X.........x." } },
             { 16, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, "....X.........x." } },
             { 16, { "X.......X.......", nullptr, "..x...x...x...x.", nullptr, nullptr, nullptr, "......x.x.......", "....X.........x." } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Latin & Caribbean", "Salsa (2-3, full band)", 180, 9, 0.00f,
           { { 16, { "...x.......x....", nullptr, nullptr, nullptr, "..X.X...X..X..X.", "......XX......XX", "ooXooo..ooXooo..", "X.xx.xx.X.x.Xx.x" } },
             { 16, { nullptr, "X.X.XX.XX.XX.X.X", nullptr, nullptr, "..X.X...X..X..X.", "......XX......XX", "ooXooo..ooXooo..", nullptr } },
             { 16, { "...x..x....x..x.", nullptr, nullptr, "X...............", "..X.X...X..X..X.", "......XX...X..XX", "ooXooXX.ooXooXX.", "X.xx.xx.X.x.Xx.x" } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, -5.0f } },
         { "Latin & Caribbean", "Reggae one drop", 75, 12, 0.35f,
           { { 16, { "........X.......", nullptr, "x.x.x.x.x.x.x.x.", nullptr, "........X.......", nullptr, nullptr, nullptr } },
             { 16, { "........X.......", nullptr, "x.x.x.x.x.x.x.x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "........X.......", nullptr, "x.x.x.x.x.x.x.xx", "..............X.", "........X......x", nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Latin & Caribbean", "Reggae rockers", 78, 12, 0.30f,
           { { 16, { "X...X...X...X...", nullptr, "..x...x...x...x.", nullptr, "....X.......X...", nullptr, nullptr, nullptr } },
             { 16, { "X.......X.......", nullptr, "..x...x...x...x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X...X...X...X...", "............X.XX", "x.x.x.x.x.x.x.x.", "..X...X...X...X.", "....X.......X...", nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Latin & Caribbean", "Reggae steppers", 75, 12, 0.30f,
           { { 16, { "X...X...X...X...", nullptr, "x.x.x.x.x.x.x.xx", nullptr, "........X.......", nullptr, nullptr, nullptr } },
             { 16, { "X...X...X...X...", nullptr, "x.x.x.x.x.x.x.x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X...X...X...X...", "........X.....XX", "x.x.x.x.x.x.x.xx", "X...............", "........X.......", nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Latin & Caribbean", "Dub", 70, 12, 0.35f,
           { { 16, { "........X.......", nullptr, "..x...x...x...x.", "..............X.", "........X......x", nullptr, nullptr, nullptr } },
             { 16, { "........X.......", nullptr, "..x...x...x...x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X.......X.......", "..............XX", "..x...x...x...x.", "..............X.", "........X......x", nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Latin & Caribbean", "Ska", 160, 12, 0.00f,
           { { 16, { "X.......X.......", "....X.......X...", "..X...X...X...X.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X.......X.......", nullptr, "..X...X...X...X.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X.......X.......", "....X.......X...", nullptr, "..X...X...X...X.", "....X.......X...", nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Latin & Caribbean", "Dancehall", 100, 12, 0.00f,
           { { 16, { "X..X..X.X..X..X.", "....X.......X...", "x.x.x.x.x.x.x.x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X.......X.......", "....X.......X...", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X..X..X.X..X..X.", "....X.......X...", "xxxxxxxxxxxxxxxx", nullptr, "...X..X....X..X.", nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Latin & Caribbean", "Calypso / soca", 125, 12, 0.00f,
           { { 16, { "X...X...X...X...", "..x.X.x...x.X.xx", "x.x.x.x.x.x.x.x.", nullptr, nullptr, nullptr, nullptr, "..X...X...X...X." } },
             { 16, { "X...X...X...X...", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, "..X...X...X...X." } },
             { 16, { "X...X...X...X...", "..x.X.x...x.X.xx", "xxxxxxxxxxxxxxxx", "X...............", nullptr, nullptr, nullptr, "..X...X...X...X." } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Latin & Caribbean", "Tresillo", 100, 12, 0.00f,
           { { 16, { "X..X..X.X..X..X.", nullptr, "x.x.x.x.x.x.x.x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X.......X.......", nullptr, nullptr, nullptr, "X..X..X.X..X..X.", nullptr, nullptr, nullptr } },
             { 16, { "X..X..X.X..X..X.", nullptr, "xxxxxxxxxxxxxxxx", nullptr, "....X.......X...", nullptr, nullptr, "X..X..X.X..X..X." } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Latin & Caribbean", "Kizomba / zouk", 90, 12, 0.00f,
           { { 16, { "X..X..X.X..X..X.", nullptr, "x.xxx.xxx.xxx.xx", nullptr, "....X.......X...", nullptr, nullptr, nullptr } },
             { 16, { "X.......X.......", nullptr, "x.xxx.xxx.xxx.xx", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X..X..X.X..X..X.", "...x..x....x..x.", "x.xxx.xxx.xxx.xx", nullptr, "....X.......X...", nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Latin & Caribbean", "Moombahton", 108, 12, 0.00f,
           { { 16, { "X...X...X...X...", "...X..X....X..X.", "..x...x...x...x.", nullptr, "....X.......X...", nullptr, nullptr, nullptr } },
             { 16, { nullptr, "...X..X....X..X.", "..x...x...x...x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X...X...X...X...", "...X..X....X..X.", "xxxxxxxxxxxxxxxx", nullptr, "....X.......X...", nullptr, "......x.......xx", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Latin & Caribbean", "Son clave (3-2)", 180, 9, 0.00f,
           { { 16, { nullptr, nullptr, "x.x.x.x.x.x.x.x.", nullptr, "X..X..X...X.X...", "......XX......XX", "ooXooo..ooXooo..", nullptr } },
             { 16, { nullptr, nullptr, nullptr, nullptr, "..X.X...X..X..X.", "......XX......XX", "ooXooo..ooXooo..", nullptr } },
             { 16, { "...x..x....x..x.", nullptr, nullptr, nullptr, "X..X..X...X.X...", "......XX......XX", "ooXooo..ooXooo..", "X.XX.X.XX.X.XX.X" } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Latin & Caribbean", "Rumba clave (3-2)", 190, 9, 0.00f,
           { { 16, { nullptr, "X.XX.X.XX.X.XX.X", nullptr, nullptr, "X..X...X..X.X...", "......XX......XX", "ooXooo..ooXooo..", nullptr } },
             { 16, { nullptr, nullptr, nullptr, nullptr, "..X.X...X..X...X", "......XX......XX", nullptr, nullptr } },
             { 16, { nullptr, "X.XX.X.XX.X.XX.X", nullptr, nullptr, "X..X...X..X.X...", "......XX...X..XX", "ooXoooX.ooXo.XX.", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Latin & Caribbean", "Cascara", 180, 9, 0.00f,
           { { 16, { "...x.......x....", "X.XX.X.XX.X.XX.X", nullptr, nullptr, "X..X..X...X.X...", nullptr, nullptr, nullptr } },
             { 16, { nullptr, "X.X.XX.XX.XX.X.X", nullptr, nullptr, "..X.X...X..X..X.", nullptr, nullptr, nullptr } },
             { 16, { "...x..x....x..x.", "X.XX.X.XX.X.XX.X", nullptr, nullptr, "X..X..X...X.X...", "......XX......XX", "ooXooo..ooXooo..", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Latin & Caribbean", "Tumbao", 180, 9, 0.00f,
           { { 16, { nullptr, nullptr, nullptr, nullptr, "X..X..X...X.X...", "......XX......XX", "ooXooo..ooXooo..", nullptr } },
             { 16, { nullptr, nullptr, nullptr, nullptr, nullptr, "......X.......X.", "o.X.o...o.X.o...", nullptr } },
             { 16, { nullptr, nullptr, nullptr, nullptr, "X..X..X...X.X...", "......XX...X..XX", "ooXoooX.ooXooXX.", "X.XX.XX.X.X.XX.X" } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Latin & Caribbean", "Mambo", 200, 9, 0.00f,
           { { 16, { "...x..x....x..x.", nullptr, nullptr, nullptr, "X..X..X...X.X...", "......XX......XX", "ooXooo..ooXooo..", "X.xx.xx.X.x.Xx.x" } },
             { 16, { nullptr, nullptr, nullptr, nullptr, "X..X..X...X.X...", "......XX......XX", "ooXooo..ooXooo..", nullptr } },
             { 16, { "...x..x....x..x.", nullptr, nullptr, "X...X...X...X...", "X..X..X...X.X...", "......XX...X..XX", "ooXooXX.ooXooXX.", "X.xx.xx.X.x.Xx.x" } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, -5.0f } },
         { "Latin & Caribbean", "Cha-cha-chá", 116, 9, 0.00f,
           { { 16, { "X..x....X..x....", nullptr, "X.x.x.xxX.x.x.xx", nullptr, nullptr, "......XX......XX", "ooXooo..ooXooo..", "X.x.X.x.X.x.X.x." } },
             { 16, { "X.......X.......", nullptr, "X.x.x.xxX.x.x.xx", nullptr, nullptr, nullptr, "o.X.o...o.X.o...", nullptr } },
             { 16, { "X..x....X..x..x.", nullptr, "X.x.x.xxX.x.x.xx", nullptr, "..X.X...X..X..X.", "......XX...X..XX", "ooXoooX.ooXooXX.", "X.x.X.x.X.x.X.x." } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, -5.0f } },
         { "Latin & Caribbean", "Songo", 200, 9, 0.00f,
           { { 16, { "...x..x....x..x.", "o.XooXo.o.XooXo.", nullptr, nullptr, "..X.X...X..X..X.", nullptr, nullptr, "X.x.X.x.X.x.X.x." } },
             { 16, { "...x..x....x..x.", "o.X..X..o.X..X..", "x.x.x.x.x.x.x.x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X..x..x.X..x.Xx.", "o.XooXoXo.XooXXo", nullptr, nullptr, "..X.X...X..X..X.", nullptr, "......XX......XX", "X.xxX.xxX.xxX.xx" } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Latin & Caribbean", "Mozambique", 200, 9, 0.00f,
           { { 16, { nullptr, nullptr, nullptr, nullptr, "..X.X...X..X..X.", "X...X...X...X..X", ".X.X.XX..X.X.XX.", "X.XX.X.XX.XX.XX." } },
             { 16, { nullptr, nullptr, nullptr, nullptr, nullptr, "X...X...X...X...", nullptr, "X.XX.X.XX.XX.XX." } },
             { 16, { "X.......X.......", nullptr, nullptr, nullptr, "..X.X...X..X..X.", "X..XX...X..XX.XX", ".X.X.XX..XXX.XX.", "X.XX.X.XX.XX.XX." } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Latin & Caribbean", "Bembé (6/8 bell)", 110, 11, 0.00f,
           { { 12, { nullptr, nullptr, "x.xx.xx.xx.x", nullptr, "X..X..X..X..", "X.....X.....", "..xx..xx..xx", "X.X.XX.X.X.X" } },
             { 12, { nullptr, nullptr, nullptr, nullptr, "X..X..X..X..", nullptr, nullptr, "X.X.XX.X.X.X" } },
             { 12, { "X.....X.....", nullptr, "xxxxxxxxxxxx", nullptr, "X..X..X..X..", "X..X..X..XX.", ".xX.xX.xX.xX", "X.X.XX.X.X.X" } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Latin & Caribbean", "Guaguancó", 190, 9, 0.00f,
           { { 16, { nullptr, "X.XX.X.XX.X.XX.X", nullptr, nullptr, "X..X...X..X.X...", ".............XX.", "o.o..XX.o.o...o.", nullptr } },
             { 16, { nullptr, "X.XX.X.XX.X.XX.X", nullptr, nullptr, "X..X...X..X.X...", nullptr, nullptr, nullptr } },
             { 16, { nullptr, "X.XX.X.XX.X.XX.X", nullptr, nullptr, "X..X...X..X.X...", "...X.........XX.", "o.o..XX.o.oX.XX.", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Latin & Caribbean", "Reggaeton (dembow)", 95, 12, 0.00f,
           { { 16, { "X...X...X...X...", "...X..X....X..X.", "x.x.x.x.x.x.x.x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X.......X.......", nullptr, nullptr, nullptr, "...X..X....X..X.", nullptr, nullptr, nullptr } },
             { 16, { "X...X...X...X...", "...X..X....X..X.", "xxxxxxxxxxxxxxxx", "..x...x...x...x.", "...X..X....X..X.", nullptr, "......x.......xx", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Latin & Caribbean", "Cumbia", 92, 12, 0.00f,
           { { 16, { "X.......X.......", nullptr, "X.xxX.xxX.xxX.xx", nullptr, "..X...X...X...X.", nullptr, "....X..x....X.x.", nullptr } },
             { 16, { "X.......X.......", nullptr, "X.x.X.x.X.x.X.x.", nullptr, "..X...X...X...X.", nullptr, nullptr, nullptr } },
             { 16, { "X.....x.X.....x.", nullptr, "X.xxX.xxX.xxX.xx", nullptr, "..X...X...X...X.", "X.......X.......", ".xx.X.xx.xx.X.XX", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Latin & Caribbean", "Merengue", 140, 12, 0.00f,
           { { 16, { "X...X...X...X...", nullptr, "X.xxX.xxX.xxX.xx", nullptr, "X.....x.X.....x.", "....X..x.xx.X...", nullptr, nullptr } },
             { 16, { "X...X...X...X...", nullptr, "X.xxX.xxX.xxX.xx", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X..xX...X..xX...", nullptr, "X.xxX.xxX.xxX.xx", nullptr, "X.....x.X.....x.", "..x.X..x.xx.X.xx", nullptr, "X.x.X.x.X.x.X.x." } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Latin & Caribbean", "Bolero", 76, 12, 0.00f,
           { { 16, { "X.......X.......", nullptr, "x.x.x.x.x.x.x.x.", nullptr, "X...X.x.X...X...", nullptr, "X.o.x.o.X.o.x.o.", nullptr } },
             { 16, { "X.......X.......", nullptr, "x.x.x.x.x.x.x.x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X.....x.X.....x.", nullptr, "xxxxxxxxxxxxxxxx", nullptr, "X...X.x.X...X...", "..............XX", "X.oxx.oxX.oxx.oX", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Brazil", "Axé", 120, 12, 0.00f,
           { { 16, { "X.....X.X.....X.", "..X.X.....X.X..X", "x.xxx.xxx.xxx.xx", nullptr, nullptr, "....X.......X...", nullptr, nullptr } },
             { 16, { "X.......X.......", nullptr, "x.xxx.xxx.xxx.xx", nullptr, nullptr, "....X.......X...", nullptr, nullptr } },
             { 16, { "X.....X.X.....X.", "..X.X.....X.X..X", "xxxxxxxxxxxxxxxx", "X...............", nullptr, "....X.......X.X.", "X.xX.xX.X.xX.XX.", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Brazil", "Ijexá", 96, 12, 0.10f,
           { { 16, { "X.....x.X.......", nullptr, "x.X.x.X.x.X.x.X.", nullptr, nullptr, "X.....x.X...x.x.", "X.ooX.ooX.ooX.oo", "x.x.X.XXx.x.X.X." } },
             { 16, { nullptr, nullptr, "x.X.x.X.x.X.x.X.", nullptr, "....X.......X...", nullptr, "X.o.X.o.X.o.X.o.", "x.x.X.XXx.x.X.X." } },
             { 16, { "X.....x.X.....x.", nullptr, "xxXxxxXxxxXxxxXx", nullptr, "....X..x....X...", "X..x..X.X.x.x.XX", "X.ooX.ooX.ooX.oo", "x.x.X.XXx.x.X.X." } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, -5.0f } },
         { "Brazil", "Samba (batucada)", 140, 12, 0.12f,
           { { 16, { "o...X...o...X...", "xoxXxoxXxoxXxoxX", "xxxXxxxXxxxXxxxX", nullptr, "X.X.XX.X.XX.X.X.", "X..x..x.X.x..xx.", nullptr, "X.x.x.X.x.X.X.x." } },
             { 16, { "o...X...o...X...", "o.o.o.o.o.o.o.o.", "x.x.x.x.x.x.x.x.", nullptr, "X.......X.......", "X.......X.......", nullptr, nullptr } },
             { 16, { "o...X...o...X...", "xoxXxoxXxoxXxoXX", "xxxXxxxXxxxXxxxX", nullptr, "X.X.XX.X.XX.X.X.", "X..x..x.X.x..xx.", "X.xx.xX.X.xx.xXX", "X.x.x.X.x.X.X.x." } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, -5.0f } },
         { "Brazil", "Partido alto", 100, 12, 0.15f,
           { { 16, { "o...X...o...X...", nullptr, "xxxXxxxXxxxXxxxX", nullptr, ".x..x.x.x..x..x.", "X.......X.......", "....X.......X...", nullptr } },
             { 16, { "....X.......X...", nullptr, "x.xXx.xXx.xXx.xX", nullptr, ".x..x.x.x..x..x.", nullptr, nullptr, nullptr } },
             { 16, { "o...X...o...X..x", nullptr, "xxxXxxxXxxxXxxxX", nullptr, ".x..x.x.x..x..x.", "X..x....X.x...x.", "..x.X..x..x.X.x.", "X.x..x.Xx.x..X.x" } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, -5.0f } },
         { "Brazil", "Bossa nova", 132, 12, 0.00f,
           { { 16, { "x..xX..xx..xX..x", nullptr, "x.x.x.x.x.x.x.x.", "....x.......x...", "X..X..X...X..X..", nullptr, nullptr, nullptr } },
             { 16, { "x...X...x...X...", nullptr, "x.x.x.x.x.x.x.x.", nullptr, "..X..X..X..X..X.", nullptr, nullptr, nullptr } },
             { 16, { "x..xX..xx..xX..x", nullptr, "xxxxxxxxxxxxxxxx", "....x.......x...", "X..X..X...X..X..", nullptr, nullptr, "x.x.x.x.x.x.x.x." } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Brazil", "Baião", 105, 12, 0.08f,
           { { 16, { "X..Xo...X..Xo...", nullptr, nullptr, nullptr, "..x.x.x...x.x.x.", nullptr, nullptr, "oxXxoxXxoxXxoxXx" } },
             { 16, { "X...o...X...o...", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, "o.X.o.X.o.X.o.X." } },
             { 16, { "X..Xo.x.X..Xo.xx", nullptr, "xxXxxxXxxxXxxxXx", nullptr, "..x.x.x...x.x.x.", nullptr, nullptr, "oxXxoxXxoxXxoxXx" } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Brazil", "Xote", 84, 12, 0.25f,
           { { 16, { "X.....x.X.......", nullptr, nullptr, nullptr, "....X.......X...", nullptr, nullptr, "o.X.o.X.o.X.o.X." } },
             { 16, { "X.......X.......", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, "o...o.X.o...o.X." } },
             { 16, { "X.....x.X.....x.", nullptr, "x.x.x.x.x.x.x.x.", nullptr, "....X..x....X.x.", nullptr, nullptr, "oxXxoxXxoxXxoxXx" } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Brazil", "Arrasta-pé", 130, 12, 0.05f,
           { { 16, { "X..xX..xX..xX..x", nullptr, nullptr, nullptr, "..x...x...x...x.", nullptr, nullptr, "oxXxoxXxoxXxoxXx" } },
             { 16, { "X...X...X...X...", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, "o.X.o.X.o.X.o.X." } },
             { 16, { "X..xX.xxX..xX.xx", nullptr, "xxxxxxxxxxxxxxxx", nullptr, "..x...xx..x...xx", nullptr, nullptr, "oxXxoxXxoxXxoxXx" } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Brazil", "Xaxado", 110, 12, 0.05f,
           { { 16, { "X..X..X.X..X..X.", nullptr, nullptr, nullptr, "....X.......X..x", nullptr, nullptr, "oxXxoxXxoxXxoxXx" } },
             { 16, { "X.....X.X.....X.", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, "o.X.o.X.o.X.o.X." } },
             { 16, { "X..X..X.X..X.XX.", nullptr, "xxXxxxXxxxXxxxXx", nullptr, "..x.X..x..x.X.xx", nullptr, nullptr, "oxXxoxXxoxXxoxXx" } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Brazil", "Maracatu (baque virado)", 92, 12, 0.05f,
           { { 16, { "X...X...X...X...", "XxxxxxXxXxxxxxXx", "x.X.x.X.x.X.x.X.", nullptr, nullptr, "X..x..x.X..x..X.", "..X..X.x..X..X.x", "X.x.x.X.x.X.x.x." } },
             { 16, { "X.......X.......", "XoooooXoXoooooXo", nullptr, nullptr, nullptr, nullptr, nullptr, "X.x.x.X.x.X.x.x." } },
             { 16, { "X..xX...X..xX.x.", "XxxXxxXxXxxXxxXX", "xxXxxxXxxxXxxxXx", nullptr, nullptr, "X..x..x.X..x..X.", "X.XX.X.xX.XX.XXX", "X.x.x.X.x.X.x.x." } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, -5.0f } },
         { "Brazil", "Samba-reggae", 104, 12, 0.08f,
           { { 16, { "....X.......X.X.", "X..x..x...x..x..", "x.x.x.x.x.x.x.x.", nullptr, "....X.......X...", "X.......X.......", "..X..xX...X..x..", nullptr } },
             { 16, { "....X.......X.X.", nullptr, nullptr, nullptr, "....X.......X...", "X.......X.......", nullptr, nullptr } },
             { 16, { "....X.......X.X.", "X..x..x...x..x..", "xxXxxxXxxxXxxxXx", nullptr, "X.xX.xX.X.xX.XX.", "X.....x.X.....x.", "..X..xX...X..xXX", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Brazil", "Frevo", 150, 12, 0.00f,
           { { 16, { "X...X...X...X...", "xxXxxXxxxxXxxXxX", nullptr, "..x...x...x...x.", nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X...X...X...X...", "x.x.x.x.x.x.x.x.", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X..xX...X..xX.x.", "XxXxxXxXXxXxXXXX", nullptr, "..x...x...x...X.", nullptr, nullptr, "....X.......X..x", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Brazil", "Coco", 112, 12, 0.10f,
           { { 16, { "X..x..X.X..x..X.", nullptr, "xxxXxxxXxxxXxxxX", nullptr, "..X...X...X...X.", nullptr, "....X.......X...", nullptr } },
             { 16, { "X.......X.......", nullptr, nullptr, nullptr, "..X...X...X...X.", nullptr, nullptr, nullptr } },
             { 16, { "X..x..X.X..x.xX.", nullptr, "xxxXxxxXxxxXxxxX", nullptr, "X.X.X.XXX.X.X.XX", nullptr, "..x.X..x..x.X.x.", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Brazil", "Ciranda", 80, 12, 0.10f,
           { { 16, { "X.......x.......", "....x..x....x...", "x.x.x.x.x.x.x.x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X...............", nullptr, "x.x.x.x.x.x.x.x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X.....x.X.....x.", "..x.X..x..x.X.xx", "xxXxxxXxxxXxxxXx", nullptr, nullptr, nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Brazil", "Funk carioca (tamborzão)", 130, 12, 0.00f,
           { { 16, { "X..X..X.X..X..X.", nullptr, "x.x.x.x.x.x.x.x.", nullptr, "....X.......X...", nullptr, "..x..x....x..x.x", nullptr } },
             { 16, { "X.......X.......", nullptr, nullptr, nullptr, "....X.......X...", nullptr, "..x..x....x..x.x", nullptr } },
             { 16, { "X..X..X.X..X..XX", nullptr, "xxxxxxxxxxxxxxxx", nullptr, "....X..x....X.x.", "...x......x.....", ".xx..xx..xx..xXx", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Brazil", "Funk carioca (rolling)", 128, 12, 0.00f,
           { { 16, { "X..X....X..X....", "....X.......X...", "x.x.x.x.x.x.x.x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X.......X.......", nullptr, nullptr, nullptr, "....X.......X...", nullptr, nullptr, nullptr } },
             { 16, { "X..X..X.X..X.xX.", "....X..x....X.xx", "xxxxxxxxxxxxxxxx", "..x...x...x...x.", nullptr, nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Middle East & North Africa", "Fallahi", 130, 12, 0.00f,
           { { 8, { nullptr, nullptr, nullptr, nullptr, nullptr, "X...X...", "..x...x.", nullptr } },
             { 8, { nullptr, nullptr, nullptr, nullptr, nullptr, "X.......", "..x...x.", nullptr } },
             { 8, { nullptr, nullptr, "x.x.x.x.", nullptr, nullptr, "X...X...", ".xX..xX.", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Middle East & North Africa", "Aksak (9/8, 2+2+2+3)", 120, 9, 0.00f,
           { { 9, { nullptr, nullptr, nullptr, nullptr, nullptr, "X.X.X.X..", ".x.x.x.xx", nullptr } },
             { 9, { nullptr, nullptr, nullptr, nullptr, nullptr, "X...X....", "..x...x..", nullptr } },
             { 9, { nullptr, nullptr, "xxxxxxxxx", nullptr, nullptr, "X.X.X.X..", ".x.x.x.xx", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Middle East & North Africa", "Gnawa (12/8)", 96, 11, 0.00f,
           { { 12, { nullptr, nullptr, "X.xX.xX.xX.x", nullptr, nullptr, "X.....X.....", "...X.....X..", nullptr } },
             { 12, { nullptr, nullptr, "X.xX.xX.xX.x", nullptr, nullptr, "X...........", nullptr, nullptr } },
             { 12, { nullptr, nullptr, "X.xX.xX.xX.x", nullptr, "...X.....X..", "X.....X...x.", "...X.X...X.X", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Middle East & North Africa", "Maqsum", 100, 12, 0.00f,
           { { 16, { nullptr, nullptr, nullptr, nullptr, nullptr, "X.......X.......", "..X...X.....X...", nullptr } },
             { 16, { nullptr, nullptr, nullptr, nullptr, nullptr, "X.......X.......", "......X.....X...", nullptr } },
             { 16, { nullptr, nullptr, "x.x.x.x.x.x.x.x.", nullptr, nullptr, "X.......X.......", ".oXoo.X..oooXoo.", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Middle East & North Africa", "Baladi", 100, 12, 0.00f,
           { { 16, { nullptr, nullptr, nullptr, nullptr, nullptr, "X.X.....X.......", "......X.....X...", nullptr } },
             { 16, { nullptr, nullptr, nullptr, nullptr, nullptr, "X.X.....X.......", "............X...", nullptr } },
             { 16, { nullptr, nullptr, "x.x.x.x.x.x.x.x.", nullptr, nullptr, "X.X.....X.......", ".o.oo.X..oooXoo.", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Middle East & North Africa", "Saidi", 110, 12, 0.00f,
           { { 16, { nullptr, nullptr, nullptr, nullptr, nullptr, "X.....X.X.......", "..X.........X...", nullptr } },
             { 16, { nullptr, nullptr, nullptr, nullptr, nullptr, "X.....X.X.......", "............X...", nullptr } },
             { 16, { nullptr, nullptr, "x.x.x.x.x.x.x.x.", nullptr, nullptr, "X.....X.X.......", ".oXoo....oooXoo.", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Middle East & North Africa", "Malfuf", 120, 12, 0.00f,
           { { 16, { nullptr, nullptr, nullptr, nullptr, nullptr, "X.......X.......", "...X..X....X..X.", nullptr } },
             { 16, { nullptr, nullptr, nullptr, nullptr, nullptr, "X.......X.......", "......X.......X.", nullptr } },
             { 16, { nullptr, nullptr, "x.x.x.x.x.x.x.x.", nullptr, nullptr, "X.......X.......", ".ooXo.Xo.ooXo.Xo", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Middle East & North Africa", "Ayoub", 120, 12, 0.00f,
           { { 16, { nullptr, nullptr, nullptr, nullptr, nullptr, "X...X...X...X...", "......X.......X.", nullptr } },
             { 16, { nullptr, nullptr, nullptr, nullptr, nullptr, "X.......X.......", "......X.......X.", nullptr } },
             { 16, { nullptr, nullptr, "x.x.x.x.x.x.x.x.", nullptr, nullptr, "X...X...X...X...", ".oo..oXo.oo..oXo", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Middle East & North Africa", "Chiftetelli (8/4)", 100, 9, 0.00f,
           { { 16, { nullptr, nullptr, nullptr, nullptr, nullptr, "X.......X.X.....", "..XX.XX.....X...", nullptr } },
             { 16, { nullptr, nullptr, nullptr, nullptr, nullptr, "X.......X.X.....", "...X..X.....X...", nullptr } },
             { 16, { nullptr, nullptr, "xxxxxxxxxxxxxxxx", nullptr, nullptr, "X.......X.X.....", ".oXXoXXo.o.oXooo", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Middle East & North Africa", "Samai (10/8)", 120, 9, 0.00f,
           { { 10, { nullptr, nullptr, nullptr, nullptr, nullptr, "X....XX...", "...X...X..", nullptr } },
             { 10, { nullptr, nullptr, nullptr, nullptr, nullptr, "X....X....", "...X...X..", nullptr } },
             { 10, { nullptr, nullptr, "xxxxxxxxxx", nullptr, nullptr, "X....XX...", ".o.Xo..Xoo", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Middle East & North Africa", "Karsilama (9/8)", 130, 9, 0.00f,
           { { 9, { nullptr, nullptr, nullptr, nullptr, nullptr, "X...X....", "..X...XXX", nullptr } },
             { 9, { nullptr, nullptr, nullptr, nullptr, nullptr, "X...X....", "..X...X..", nullptr } },
             { 9, { nullptr, nullptr, "xxxxxxxxx", nullptr, nullptr, "X...X....", ".oXo.oXXX", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "India", "Teentaal (16)", 90, 12, 0.00f,
           { { 32, { nullptr, nullptr, nullptr, nullptr, nullptr, "X.X.X.X.X.X.X.X.X.........X.X.X.", "X.x.x.X.X.x.x.X.X.x.x.X.X.x.x.X.", nullptr } },
             { 32, { nullptr, nullptr, nullptr, nullptr, nullptr, "X.......X.......................", "X.x.x.X.X.x.x.X.X.x.x.X.X.x.x.X.", nullptr } },
             { 32, { nullptr, nullptr, nullptr, nullptr, nullptr, "X.X.X.X.X.X.X.X.X.......X.X.XXXX", "X.x.x.X.X.x.x.X.X.x.x.X.XxXxXxXx", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "India", "Keherwa (8)", 90, 12, 0.00f,
           { { 16, { nullptr, nullptr, nullptr, nullptr, "..........X.....", "X.X.........X...", "X...x.x.x...X.x.", nullptr } },
             { 16, { nullptr, nullptr, nullptr, nullptr, nullptr, "X...............", "X...x.x.x...X.x.", nullptr } },
             { 16, { nullptr, nullptr, nullptr, nullptr, "..........X.....", "X.X.......X.X.X.", "X.x.x.xxx.x.XxXx", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "India", "Dadra (6)", 90, 14, 0.00f,
           { { 12, { nullptr, nullptr, nullptr, nullptr, nullptr, "X.X...X.....", "X.x.x.X.x.x.", nullptr } },
             { 12, { nullptr, nullptr, nullptr, nullptr, nullptr, "X...........", "X.x.x.X.x.x.", nullptr } },
             { 12, { nullptr, nullptr, nullptr, nullptr, nullptr, "X.X...X.X.X.", "X.x.x.XxXxXx", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "India", "Rupak (7)", 90, 12, 0.00f,
           { { 14, { nullptr, nullptr, nullptr, nullptr, nullptr, "......X...X...", "x.x.x.X.x.X.x.", nullptr } },
             { 14, { nullptr, nullptr, nullptr, nullptr, nullptr, "......X.......", "x.x.x.X.x.X.x.", nullptr } },
             { 14, { nullptr, nullptr, nullptr, nullptr, nullptr, "......X...X.XX", "x.x.x.X.x.XxXx", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "India", "Jhaptaal (10)", 90, 12, 0.00f,
           { { 20, { nullptr, nullptr, nullptr, nullptr, nullptr, "X...X.X.......X.X...", "X.x.X.X.x.x.x.X.X.x.", nullptr } },
             { 20, { nullptr, nullptr, nullptr, nullptr, nullptr, "X...................", "X.x.X.X.x.x.x.X.X.x.", nullptr } },
             { 20, { nullptr, nullptr, nullptr, nullptr, nullptr, "X...X.X.......X.XXXX", "X.x.X.X.x.x.x.XxXxXx", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "India", "Ektaal (12)", 80, 12, 0.00f,
           { { 24, { nullptr, nullptr, nullptr, nullptr, "............X...........", "X.X.XX........X.XX..X...", "X.X.XxXxXxx.x.x.XxXxX.x.", nullptr } },
             { 24, { nullptr, nullptr, nullptr, nullptr, nullptr, "X.......................", "X.X.X.x.x.x.x.x.X.x.X.x.", nullptr } },
             { 24, { nullptr, nullptr, nullptr, nullptr, "............X...........", "X.X.XX........X.XX..X.XX", "X.X.XxXxXxx.x.x.XxXxXxXx", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "India", "Bhangra (dhol chaal)", 100, 12, 0.00f,
           { { 16, { nullptr, nullptr, nullptr, nullptr, "....X.......X...", "X..X..X.X..X..X.", "..x..x.x..x..x.x", nullptr } },
             { 16, { nullptr, nullptr, nullptr, nullptr, nullptr, "X.......X.......", "..x..x.x..x..x.x", nullptr } },
             { 16, { nullptr, nullptr, "x.x.x.x.x.x.x.x.", nullptr, "....X.......X...", "X..X..X.X..X.XX.", ".xx.xx.x.xx.xxxx", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Africa & World", "Afro-Cuban 6/8", 110, 11, 0.00f,
           { { 12, { "X.....X.....", nullptr, nullptr, nullptr, "......X...X.", nullptr, "...X.X...X.X", "X.X.XX.X.X.X" } },
             { 12, { nullptr, nullptr, "x.xx.xx.xx.x", nullptr, nullptr, nullptr, nullptr, "X.X.XX.X.X.X" } },
             { 12, { "X..X..X..X..", nullptr, nullptr, nullptr, "X..X..X..X..", "X.....X..XX.", ".xX.xX.xX.xX", "X.X.XX.X.X.X" } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Africa & World", "Highlife", 120, 12, 0.00f,
           { { 16, { "X.....X.X.....X.", "....X.......X...", "x.x.x.x.x.x.x.x.", nullptr, nullptr, nullptr, nullptr, "X.X.X.XX.X.X.X.." } },
             { 16, { nullptr, nullptr, "x.x.x.x.x.x.x.x.", nullptr, nullptr, nullptr, nullptr, "X.X.X.XX.X.X.X.." } },
             { 16, { "X.....X.X.....X.", "....X.......X..x", "xxxxxxxxxxxxxxxx", nullptr, nullptr, nullptr, "..x..x....x..xx.", "X.X.X.XX.X.X.X.." } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Africa & World", "Afrobeats", 105, 12, 0.00f,
           { { 16, { "X.....X...X.....", nullptr, "xxXxxxXxxxXxxxXx", nullptr, "...X..X....X..X.", nullptr, "..........x.x...", nullptr } },
             { 16, { "X...............", nullptr, "x.x.x.x.x.x.x.x.", nullptr, "...X..X....X..X.", nullptr, nullptr, nullptr } },
             { 16, { "X.....X...X...X.", "....X.......X...", "xxXxxxXxxxXxxxXx", nullptr, "...X..X....X..X.", nullptr, "..x..x....x.x.x.", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Africa & World", "Amapiano", 113, 12, 0.00f,
           { { 16, { "X...X...X...X...", nullptr, "..x...x...x...x.", nullptr, "..........X...X.", nullptr, "...x..x..x..x...", nullptr } },
             { 16, { nullptr, nullptr, "..x...x...x...x.", nullptr, "..........X...X.", "X.........X.....", nullptr, nullptr } },
             { 16, { "X...X...X...X...", nullptr, "xxxxxxxxxxxxxxxx", nullptr, "....X.....X.X.X.", "X.........X.....", "...x..x..x..x..x", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Africa & World", "Soukous", 130, 12, 0.00f,
           { { 16, { "X...X...X...X...", "..X...X...X...XX", "xxxxxxxxxxxxxxxx", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X...X...X...X...", nullptr, "xxxxxxxxxxxxxxxx", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X...X...X...X...", "..X...X...X...XX", "xxxxxxxxxxxxxxxx", "..X...X...X...X.", nullptr, nullptr, "X.x...x.X.x...xx", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Africa & World", "Gahu (bell)", 120, 12, 0.00f,
           { { 16, { nullptr, nullptr, nullptr, nullptr, nullptr, "......X.......X.", "X.x.X.x.X.x.X.x.", "X..X..X...X.X..." } },
             { 16, { nullptr, nullptr, "x.x.x.x.x.x.x.x.", nullptr, nullptr, nullptr, nullptr, "X..X..X...X.X..." } },
             { 16, { nullptr, nullptr, "xxxxxxxxxxxxxxxx", nullptr, nullptr, "...X..X....X..X.", "X.x.X.x.X.x.X.xx", "X..X..X...X.X..." } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Africa & World", "Taiko (festival)", 120, 12, 0.00f,
           { { 16, { nullptr, nullptr, nullptr, nullptr, nullptr, "X...X...X.X.X...", "..x...x.......xx", "X.x.X.x.X.x.X.x." } },
             { 16, { nullptr, nullptr, nullptr, nullptr, nullptr, "X.......X.......", nullptr, "X.x.X.x.X.x.X.x." } },
             { 16, { nullptr, nullptr, nullptr, nullptr, nullptr, "X..XX...X.X.X.XX", ".xx..xx..xx.XXXX", "X.x.X.x.X.x.X.x." } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Africa & World", "Flamenco bulería (12)", 120, 9, 0.00f,
           { { 12, { nullptr, nullptr, "xxxxxxxxxxxx", nullptr, "..X..X..X.X.", "X...........", nullptr, nullptr } },
             { 12, { nullptr, nullptr, nullptr, nullptr, "..X..X..X.X.", nullptr, nullptr, nullptr } },
             { 12, { nullptr, nullptr, "xxxxxxxxxxxx", nullptr, "..X..X.XX.X.", "X.X..X..X...", ".x.x.x.x.x.x", nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Africa & World", "Tango", 120, 12, 0.00f,
           { { 16, { "X...X...X...X...", "......X....X....", "x.x.x.x.x.x.x.x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X..X..X.X.......", nullptr, "x.x.x.x.x.x.x.x.", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 16, { "X...X...X...X...", "......X....X..X.", "xxxxxxxxxxxxxxxx", nullptr, "X..X..X.X.......", nullptr, nullptr, nullptr } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Jazz", "Swing (ride)", 140, 11, 0.00f,
           { { 12, { "o..o..o..o..", nullptr, "...X.....X..", nullptr, nullptr, nullptr, nullptr, "X..X.xX..X.x" } },
             { 12, { nullptr, "o.oo.oo.oo.o", "...X.....X..", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 12, { "o..o..o..o..", ".....o....oX", "...X.....X..", "X...........", nullptr, nullptr, nullptr, "X..X.xX..X.x" } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Jazz", "Swing (brushes)", 120, 11, 0.00f,
           { { 12, { "o.....o.....", "o.oo.oo.oo.o", "...X.....X..", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 12, { nullptr, "o.o.o.o.o.o.", "...X.....X..", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 12, { "o.....o...o.", "o.oo.oX.oo.o", "...X.....X..", nullptr, nullptr, nullptr, nullptr, "X..X.xX..X.x" } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Jazz", "Jazz waltz (3/4)", 150, 11, 0.00f,
           { { 9, { "X........", nullptr, "...X..X..", nullptr, nullptr, nullptr, nullptr, "X..X.xX.." } },
             { 9, { nullptr, "o.oo.oo.o", "...X..X..", nullptr, nullptr, nullptr, nullptr, nullptr } },
             { 9, { "X....o...", "....o..oX", "...X..X..", nullptr, nullptr, nullptr, nullptr, "X..X.xX.." } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Jazz", "Bossa jazz (ride)", 140, 12, 0.00f,
           { { 16, { "X..xX..xX..xX..x", nullptr, nullptr, nullptr, "X..X..X...X..X..", nullptr, nullptr, "x.x.x.x.x.x.x.x." } },
             { 16, { "X..xX..xX..xX..x", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, "x.x.x.x.x.x.x.x." } },
             { 16, { "X..xX..xX..xX..x", nullptr, nullptr, "X...............", "X..X..X...X..X..", nullptr, nullptr, "xxxxxxxxxxxxxxxx" } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Jazz", "Afro-jazz 6/8", 120, 11, 0.00f,
           { { 12, { "X.....X.....", nullptr, "...X.....X..", nullptr, nullptr, nullptr, ".......x.x..", "X.X.XX.X.X.X" } },
             { 12, { nullptr, nullptr, "...X.....X..", nullptr, nullptr, nullptr, nullptr, "X.X.XX.X.X.X" } },
             { 12, { "X.....X...x.", nullptr, "...X.....X..", nullptr, nullptr, "...........X", "..x...xx.x.x", "X.X.XX.X.X.X" } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
         { "Jazz", "Fast bebop", 220, 11, 0.00f,
           { { 12, { nullptr, "......o.....", "...X.....X..", nullptr, nullptr, nullptr, nullptr, "X..X.xX..X.x" } },
             { 12, { nullptr, nullptr, "...X.....X..", nullptr, nullptr, nullptr, nullptr, "X..X.xX..X.x" } },
             { 12, { "..........X.", "..o..o..o.oX", "...X.....X..", nullptr, nullptr, nullptr, nullptr, "X..X.xX..X.x" } } },
           { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } },
      };
      count = (int)(sizeof(kGrooves) / sizeof(kGrooves[0]));
      return kGrooves;
   }

   // The table stores rates as plain ints (the node does too, see
   // DrumSequencerNode::rate); pin the values it uses to MusicTime's enum so
   // a reordered enum breaks the build instead of silently retiming grooves.
   static_assert(MusicTime::kEighth == 9, "groove rate 9 = 1/8");
   static_assert(MusicTime::kEighthTrip == 11, "groove rate 11 = 1/8T");
   static_assert(MusicTime::kSixteenth == 12, "groove rate 12 = 1/16");
   static_assert(MusicTime::kSixteenthTrip == 14, "groove rate 14 = 1/16T");
}
