# Cards for the Node Field Guide's newer chapters (21-26). One entry per node:
# (name, tag, description, try-it sentence, wire chain). Descriptions are written from the
# in-app help text in src/main.cpp (SpecificNodeHelpText) so they match what the nodes do.

CHAPTERS = [
    {
        "num": "Twenty-One",
        "n": 21,
        "title": "More Shapes & Slideshows",
        "intro": "Ten more 2D sources: a picture slideshow that steps on the beat, and nine vector shapes that each do one thing well. "
                 "Like Shape, every one is drawn from pure math, so they stay razor sharp at any size and every control can be animated.",
        "cards": [
            ("Slideshow", "SOURCE · IMAGE OUT",
             "Steps through a folder of images on a beat interval, with an optional crossfade between them. Point it at a folder and it becomes a self-running photo reel locked to the tempo.",
             "set the interval to one bar and turn the crossfade up for a slow, dreamy gallery.",
             ["Slideshow", "Bloom", "Output"]),
            ("Ellipse", "SOURCE · IMAGE OUT",
             "A filled or stroked ellipse. Aspect stretches it away from a perfect circle, so one dial takes you from a dot to a wide lens shape.",
             "wire an LFO into Aspect so the circle squashes and stretches like a breathing pupil.",
             ["LFO", "Ellipse (Aspect)", "Output"]),
            ("Rectangle", "SOURCE · IMAGE OUT",
             "A filled or stroked rectangle with an optional corner radius. The simplest building block for panels, bars, frames, and mattes.",
             "use it as a hard-edged matte to cut a window out of a busy video.",
             ["Rectangle", "Set Alpha", "Output"]),
            ("Rounded Rect", "SOURCE · IMAGE OUT",
             "A rectangle with rounded corners. It is the same as Rectangle, but the corner radius gets its own control so you can animate it directly.",
             "modulate the corner radius from square to pill shape on every kick.",
             ["Audio Analyze (Onset)", "Rounded Rect (Radius)", "Output"]),
            ("Polygon", "SOURCE · IMAGE OUT",
             "A regular polygon, and Sides sets how many. Three is a triangle, five a pentagon, and a high number slides toward a circle.",
             "step Sides up with a Pattern modulator and watch the shape grow a corner at a time.",
             ["Pattern", "Polygon (Sides)", "Output"]),
            ("Hexagon", "SOURCE · IMAGE OUT",
             "A six-sided regular polygon. It is a Polygon with Sides locked at six, for when you simply want honeycomb geometry with one less thing to dial in.",
             "tile it with Mirror Tile for an instant honeycomb pattern.",
             ["Hexagon", "Mirror Tile", "Output"]),
            ("Crescent", "SOURCE · IMAGE OUT",
             "A crescent-moon shape, made by subtracting one circle from another. Move the two circles apart and the crescent fattens or thins.",
             "glow it up with Bloom and drop it over a dark gradient for a moon.",
             ["Crescent", "Bloom", "Output"]),
            ("Superellipse", "SOURCE · IMAGE OUT",
             "A squircle: a shape that lives between a rectangle and an ellipse. Inner Ratio tunes how square or how round it feels, the same silhouette you see on app icons.",
             "sweep Inner Ratio with an LFO to morph a circle into a rounded square and back.",
             ["LFO", "Superellipse (Inner Ratio)", "Output"]),
            ("Teardrop", "SOURCE · IMAGE OUT",
             "A teardrop or droplet outline: round at the bottom, pointed at the top. Handy for water, ink, and leaf-like motifs.",
             "repeat it in a ring with Kaleidoscope for a flower made of droplets.",
             ["Teardrop", "Kaleidoscope", "Output"]),
            ("Chevron", "SOURCE · IMAGE OUT",
             "An angled bracket, or chevron. Stack and repeat it for arrows, speed lines, and rank badges.",
             "feed it into Mirror Tile to build a scrolling zig-zag pattern.",
             ["Chevron", "Mirror Tile", "Output"]),
        ],
    },
    {
        "num": "Twenty-Two",
        "n": 22,
        "title": "Alpha, Keys & Edges",
        "intro": "Transparency tools and edge finders. Cut a subject out of its background, clean up the matte, and fix the dark or bright halos that show up when layers don't blend right. "
                 "The last four nodes find edges and tile images seamlessly.",
        "cards": [
            ("Show Alpha", "COMPOSITING · IN/OUT",
             "Shows the alpha channel as a plain greyscale picture: white is solid, black is transparent. It is a viewer, not an edit. It swaps the colour for the matte so you can see exactly what a key produced, and it is the first thing to reach for when a composite goes wrong.",
             "park it after a Chroma Key to see the matte and check for holes.",
             ["Video In", "Chroma Key", "Show Alpha", "Output"]),
            ("Set Alpha", "COMPOSITING · IN/OUT",
             "Replaces the alpha channel outright with the brightness of a second image you patch in: a hand-drawn matte, a Shape, a Ramp, or another branch's Show Alpha. With nothing in the second input, the picture is forced fully opaque.",
             "patch a Ramp into the second input to fade a photo out from left to right.",
             ["Image Source", "Set Alpha (Ramp)", "Output"]),
            ("Alpha Invert", "COMPOSITING · IN/OUT",
             "Swaps transparent for solid and back, and leaves the colour alone. It is the invert-matte switch a key would otherwise need a second node to get.",
             "invert a Luma Key to keep the dark parts of a shot instead of the bright ones.",
             ["Video", "Luma Key", "Alpha Invert", "Output"]),
            ("Alpha from Luma", "COMPOSITING · IN/OUT",
             "Builds a new alpha channel from the picture's own brightness, so a black background becomes see-through with nothing to key against. Invert flips which end is solid, for a white-on-black source.",
             "run fire or smoke footage through it to lift the flames off their black backdrop.",
             ["Video", "Alpha from Luma", "Blend"]),
            ("Alpha Levels", "COMPOSITING · IN/OUT",
             "The Levels remap, applied to the alpha channel only. Low and High clamp and stretch the matte's range (choking a soft edge tighter, or spreading it wider) and Gamma bends the falloff in between. The go-to cleanup pass after Chroma Key or Alpha from Luma.",
             "raise Low a touch after a key to remove the faint haze left around a subject.",
             ["Chroma Key", "Alpha Levels", "Output"]),
            ("Premultiply", "COMPOSITING · IN/OUT",
             "Converts between premultiplied alpha (colour already scaled by its own alpha) and straight alpha. Only reach for it when edges look wrong: a dark fringe on a composite usually means straight alpha needs premultiplying, and a bright halo means the reverse.",
             "if a keyed subject has a dark outline over a bright background, add this before the Blend.",
             ["Chroma Key", "Premultiply", "Blend"]),
            ("Chroma Key", "COMPOSITING · IN/OUT",
             "Removes a chosen key colour, green-screen or blue-screen style, matching it in a way that ignores brightness. Tolerance and Softness shape the edge, Spill Removal tames colour-cast fringes, and the show option previews the matte instead of the keyed picture.",
             "pick the green of a backdrop, then raise Spill Removal until the green glow on hair disappears.",
             ["Video In", "Chroma Key", "Blend", "Output"]),
            ("Luma Key", "COMPOSITING · IN/OUT",
             "Keys out a range of brightness (Low to High) instead of a colour, with Softness at the edges and Invert to flip which range is kept. The show option previews the matte.",
             "key out a white sky from a skyline photo and drop a new sky behind it.",
             ["Image Source", "Luma Key", "Blend", "Output"]),
            ("Mirror Tile", "EFFECTS · IN/OUT",
             "Tiles the image and flips every other tile so the edges meet seamlessly, unlike a plain repeat. Tiles sets how many repeats you get.",
             "tile a Noise source to make a seamless texture for a 3D material.",
             ["Noise", "Mirror Tile", "Material"]),
            ("Normal Map", "EFFECTS · IN/OUT",
             "Works out a tangent-space normal map by treating the picture's brightness as a height field. The output switch can also show the raw normals, the source height, or the steepness of the slope.",
             "turn a Noise or Texture into a bump map for a Material's surface.",
             ["Texture (Brick)", "Normal Map", "Material"]),
            ("Edge Sobel", "EFFECTS · IN/OUT",
             "Classic Sobel edge detection. It outputs how sharply the picture changes as greyscale lines, and Invert flips black and white.",
             "wire it into a Displacement node so only the edges of a photo lift off the surface.",
             ["Image Source", "Edge Sobel", "Output"]),
            ("Edge Outline", "EFFECTS · IN/OUT",
             "Finds edges from the brightness gradient and draws them as flat-colour outlines over the original picture. Thickness and Threshold control how bold and how many.",
             "give a video a hand-inked comic look by adding a black outline over it.",
             ["Video", "Edge Outline", "Output"]),
        ],
    },
    {
        "num": "Twenty-Three",
        "n": 23,
        "title": "More 3D Solids & Mesh Surgery",
        "intro": "Thirteen more 3D primitives (platonic solids, twisted surfaces, gears and arrows), a depth-map unprojector, and the mesh operators: turn a surface into points, thicken it, wireframe it, blow it apart, or delete part of it. "
                 "Every one takes geometry in and gives geometry out, so they chain like any other 3D node.",
        "cards": [
            ("Capsule", "3D · GEOMETRY OUT",
             "A cylinder with half-sphere caps, like a pill. The tube control sets the radius of the caps and the body together.",
             "stretch a Capsule and spin it for a quick pill, bone, or lightsaber shape.",
             ["Capsule", "Material", "Render 3D"]),
            ("Pyramid", "3D · GEOMETRY OUT",
             "A pyramid. Sides sets how many sides the base has, so 4 is the classic square pyramid and larger numbers lean toward a cone.",
             "scatter a handful with Instance on Points for a desert of pyramids.",
             ["Pyramid", "Instance on Points", "Render 3D"]),
            ("Prism", "3D · GEOMETRY OUT",
             "A prism: a polygon extruded into a solid. Sides sets the polygon, so 3 is a triangular prism and 6 is a hex bar.",
             "stack several prisms of different sizes for a skyline.",
             ["Prism", "Array", "Render 3D"]),
            ("Supershape", "3D · GEOMETRY OUT",
             "A shape built from the superformula. Depth, tooth depth and hub hole warp it into gear-like or organic silhouettes, from starfish to flowers to cogs.",
             "sweep tooth depth with an LFO and the shape slowly morphs from smooth to spiky.",
             ["LFO", "Supershape (Tooth Depth)", "Render 3D"]),
            ("Tetrahedron", "3D · GEOMETRY OUT",
             "A four-faced platonic solid: the simplest 3D shape that can enclose space, made of four triangles.",
             "put one under a Wireframe node for a crisp geometric diagram look.",
             ["Tetrahedron", "Wireframe", "Render 3D"]),
            ("Octahedron", "3D · GEOMETRY OUT",
             "An eight-faced platonic solid: two pyramids joined at the base, like a diamond.",
             "give it a glassy Material and a slow spin for a floating crystal.",
             ["Octahedron", "Material", "Render 3D"]),
            ("Dodecahedron", "3D · GEOMETRY OUT",
             "A twelve-faced platonic solid with pentagon faces. It is the rounder of the classic solids and reads almost like a ball.",
             "run it through Explode to blow the twelve faces apart like a petal.",
             ["Dodecahedron", "Explode", "Render 3D"]),
            ("Rounded Cube", "3D · GEOMETRY OUT",
             "A cube with soft edges and corners. Corner radius sets how rounded it gets, from sharp-edged to almost a sphere.",
             "animate the corner radius on a beat for a bouncy, squishy cube.",
             ["Rounded Cube", "Material", "Render 3D"]),
            ("Mobius Strip", "3D · GEOMETRY OUT",
             "A twisted strip with one side and one edge. Width sets how wide the band is.",
             "add Solidify so the one-sided ribbon becomes a solid band you can light properly.",
             ["Mobius Strip", "Solidify", "Render 3D"]),
            ("Klein Bottle", "3D · GEOMETRY OUT",
             "The classic bottle with no inside or outside. It is a closed surface that passes through itself, which makes it a striking thing to light and rotate.",
             "give it a slow spin and a bright rim light for an impossible-object hero shot.",
             ["Klein Bottle", "Material", "Render 3D"]),
            ("Gear 3D", "3D · GEOMETRY OUT",
             "A 3D cogwheel. Depth sets the thickness, and tooth depth and hub hole shape the teeth and the centre bore. It carries the 3D suffix because the 2D Shape node already has its own Gear.",
             "rotate two Gear 3Ds in opposite directions for a clockwork look.",
             ["Gear 3D", "Material", "Render 3D"]),
            ("Star 3D", "3D · GEOMETRY OUT",
             "A 3D star extruded into a solid. Depth sets how thick it is, and inner ratio sets how deep the points cut in. It carries the 3D suffix because the 2D Shape node already has its own Star.",
             "instance a few hundred with random spin for a shower of stars.",
             ["Star 3D", "Instance on Points", "Render 3D"]),
            ("Arrow 3D", "3D · GEOMETRY OUT",
             "A 3D arrow made of a shaft and an arrowhead. It carries the 3D suffix because the 2D Shape node already has its own Arrow.",
             "scatter arrows across a surface and aim them for a flow-field display.",
             ["Arrow 3D", "Instance on Points", "Render 3D"]),
            ("Depth Projection", "3D · GEOMETRY OUT",
             "Turns a depth map, plus an optional colour image, into a 3D point cloud or a triangulated surface. It supports pinhole camera, planar, radial and cylindrical projections, depth curves, and edge tearing.",
             "feed a depth map and its matching photo to pop a flat picture into a shallow 3D scene.",
             ["Image Source (Depth)", "Depth Projection", "Render 3D"]),
            ("Mesh to Points", "3D · GEOMETRY OUT",
             "Samples a mesh's vertices as a point cloud, ready for Instance on Points or Metaballs.",
             "turn a model into points and put a tiny sphere on each one.",
             ["Mesh to Points", "Instance on Points", "Render 3D"]),
            ("Mesh to Edges", "3D · GEOMETRY OUT",
             "Samples points along a mesh's edges as a point cloud, for Instance on Points or Metaballs. A good way to trace the outline of a shape with beads.",
             "instance small spheres along the edges of a cube for a bead-wire frame.",
             ["Mesh to Edges", "Instance on Points", "Render 3D"]),
            ("Mesh to Faces", "3D · GEOMETRY OUT",
             "Samples the centre point of every face as a point cloud, for Instance on Points or Metaballs. One point per face, so the density follows the mesh.",
             "stand a small object on every face of a dodecahedron.",
             ["Mesh to Faces", "Instance on Points", "Render 3D"]),
            ("Solidify", "3D · GEOMETRY OUT",
             "Gives a flat or open surface real thickness, turning it into a solid shell. Keep original also keeps the source surface.",
             "thicken a Plane or a Mobius Strip so it has real edges to catch the light.",
             ["Mobius Strip", "Solidify", "Render 3D"]),
            ("Wireframe", "3D · GEOMETRY OUT",
             "Replaces solid faces with a thin tube along every edge, at the Thickness you choose. A solid becomes a cage.",
             "wireframe a Dodecahedron and add Bloom for a neon-sign look.",
             ["Dodecahedron", "Wireframe", "Render 3D"]),
            ("Triangulate", "3D · GEOMETRY OUT",
             "Re-cuts the mesh into triangles. Jitter randomises how each face is split, giving a more organic, less uniform look.",
             "triangulate with some Jitter, then run Explode for a shattered low-poly feel.",
             ["Sphere", "Triangulate", "Explode"]),
            ("Normals", "3D · GEOMETRY OUT",
             "Recomputes how the surface faces the light. Flat shade gives hard per-face edges instead of smooth shading, and flip reverses which way every face points.",
             "switch on flat shade to turn a smooth sphere into a faceted gem.",
             ["Sphere", "Normals", "Render 3D"]),
            ("Explode", "3D · GEOMETRY OUT",
             "Pushes every face outward from the mesh's centre along its own direction, by Amount, with a different amount per face set by Seed.",
             "wire an envelope into Amount so the shape bursts apart on each hit.",
             ["Envelope", "Explode (Amount)", "Render 3D"]),
            ("Screw", "3D · GEOMETRY OUT",
             "Sweeps a profile around an axis in a spiral. Steps sets the smoothness, Turns the number of revolutions, Rise per turn the pitch, and Radius pushes the sweep outward.",
             "sweep a small circle to make a spring, or a flat strip for a spiral staircase.",
             ["Shape", "Screw", "Render 3D"]),
            ("Delete", "3D · GEOMETRY OUT",
             "Removes the faces marked by an upstream Select node (or the instances, when it sits after Instance on Points). Turn on keep selected instead to flip it: everything except the selection goes, and only the selection stays.",
             "select the top half of a sphere and delete it to make a bowl.",
             ["Sphere", "Select", "Delete", "Render 3D"]),
            ("Set Vertex Color", "3D · GEOMETRY OUT",
             "Writes colour onto each element: vertex colour on a mesh, or per-particle colour on a point cloud, whichever the input carries. Source picks where the colour comes from: one flat colour, a two-colour ramp, random per element, a texture sampled at each element's UV, or the swatches of a Palette node. Render 3D reads it without being told.",
             "colour a scatter of points from a Palette so every point picks one swatch.",
             ["Mesh to Points", "Set Vertex Color (Palette)", "Render 3D"]),
        ],
    },
    {
        "num": "Twenty-Four",
        "n": 24,
        "title": "Loops, Learning & Listening",
        "intro": "A live audio looper, a 16-pad sample player, three new audio effects, a level meter, two modulator helpers, and the Prediction family: nodes that listen to what you play, learn your habits, and carry on in the same style. "
                 "The learning nodes keep what they learn (some of it is saved with the patch), so a good take can be reused.",
        "cards": [
            ("Looper", "SYNTHS · AUDIO OUT",
             "A live audio looper. Wire in the sound, press Rec, and the take ends on its own after the take length and then loops. Play restarts it, Dub layers new sound over it, and Clear empties it. Take length can be a musical division, or free. Every take is shifted by your audio interface's measured latency, so a loop played in time sits on the grid. The loop is kept in memory (up to 60 seconds) and is not saved with the patch.",
             "record a one-bar drum pattern, then Dub a bassline on top of it.",
             ["Audio File", "Looper", "Audio Out"]),
            ("MPC", "SYNTHS · AUDIO OUT",
             "A 16-pad sample player in the spirit of an MPC. Each pad holds one sample and one play mode: One shot plays the whole sample, Gate plays while the pad is held, and Loop toggles a looping playback on and off. Hit pads with the mouse, with a MIDI controller, or with notes 36 to 51 on the note input, the usual pad-controller layout. Every pad is its own voice with its own volume, pitch, pan, speed, fine tune and fades, and a pad can be Synced to a musical division so a hit waits for the next grid line. All pads mix to one stereo output.",
             "load a kick, snare and hat on three pads and play them from a MIDI pad controller through a MIDI Notes node.",
             ["MIDI Notes", "MPC", "Audio Out"]),
            ("Resonator Bank", "AUDIOEFFECTS · IN/OUT",
             "Up to 16 band-pass resonators running side by side, forming a tuned bank of ringing filters, including a metallic tuning mode. Feed it noise or drums and it rings like a struck bell or plate.",
             "push a drum loop through it in metallic mode for a gamelan-style shimmer.",
             ["Audio File", "Resonator Bank", "Audio Out"]),
            ("Cycle Shaper", "AUDIOEFFECTS · IN/OUT",
             "Distorts and crossfades the shape of a single waveform cycle. A way to bend a plain tone into harder, brighter, or stranger timbres.",
             "run a plain sine through it and sweep the shaping for a rubbery, evolving lead.",
             ["Oscillator", "Cycle Shaper", "Audio Out"]),
            ("Spec Blur", "AUDIOEFFECTS · IN/OUT",
             "A streaming phase vocoder that smears the spectrum over time. Sharp hits dissolve into a harmonic cloud, with tilt, phase diffusion and freeze controls. It adds 42.7 ms of delay, and its mix defaults to fully wet.",
             "freeze a held chord and let it hang as a pad while you play over the top.",
             ["Wavetable", "Spec Blur", "Reverb", "Audio Out"]),
            ("Audio Meter", "UTILITY · IN/OUT",
             "A stereo level meter with separate left and right bars on a -60 to +3 dBFS scale. Each bar shows the average level (solid) inside the peaks (faint), with a peak-hold line and the loudest peak as a number on top that turns red at 0 dBFS. Audio passes through unchanged, and it measures whatever it is patched to even with its output unconnected, so it works as a tap on any cable.",
             "hang one off the master cable to watch your headroom as you mix.",
             ["Audio File", "Audio Meter", "Audio Out"]),
            ("Velocity to CV", "MODULATORS · IN/OUT",
             "Turns the velocity of incoming notes into a 0 to 1 modulator, with an adjustable velocity range. Hit harder and the value goes higher.",
             "let note velocity control the Bloom amount, so loud notes flare.",
             ["MIDI Notes", "Velocity to CV", "Bloom (Amount)"]),
            ("CV Recorder", "MODULATORS · IN/OUT",
             "Records any modulator you patch in. Press Rec, perform a gesture, and it loops the take back with adjustable speed and low and high range. Takes are timed in beats, follow the tempo, pause with the transport, and are saved with the patch.",
             "record a hand-played XY Motion Pad swirl, then loop it into Twirl.",
             ["XY Motion Pad", "CV Recorder", "Twirl (Angle)"]),
            ("Predictive Modulator", "PREDICTION · IN/OUT",
             "Learns a small model of one modulator you patch in, then keeps that motion going on its own once learning stops. Draw a gesture once and it carries on in the same spirit.",
             "learn a few seconds of a knob move, stop, and it keeps wandering in the same way.",
             ["Macro Knob", "Predictive Modulator", "Bloom (Amount)"]),
            ("Predictive Coloring", "PREDICTION · IN/OUT",
             "Learns what graded footage looks like to you and grades incoming frames toward it. Press Learn on footage you've already graded to build a target look, or leave self normalize on to auto-level without one. Mix blends the grade in, and Wander makes it drift gently among looks it has actually seen.",
             "learn from a graded still, then run raw video through it to match.",
             ["Video In", "Predictive Coloring", "Output"]),
            ("Predictive Notes", "PREDICTION · NOTE OUT",
             "Wire a note chain in and press Learn. It listens (passing the notes through), learns pitches, rhythm, lengths and velocities, then plays on its own in that style. Stray at the bottom replays the phrase, the middle plays in character, and the top ignores what it learned and picks freely. What it learned is saved with the patch.",
             "play a short phrase, press Learn, and let it improvise a variation.",
             ["MIDI Notes", "Predictive Notes", "Wavetable"]),
            ("Predictive Quantize", "PREDICTION · NOTE OUT",
             "A groove quantizer instead of a grid one. It listens to the real spacing between your notes and corrects them in the same pass, with no Learn button, adapting the more you play. Its learned feel is shared by every Predictive Quantize in every patch and keeps only your most recent notes.",
             "tighten a loose keyboard take without making it sound robotic.",
             ["MIDI Notes", "Predictive Quantize", "Wavetable"]),
            ("Predictive Velocity", "PREDICTION · NOTE OUT",
             "A learned dynamics curve instead of a hand-drawn one. It listens to how hard you play and remaps velocities in the same pass, with no Learn button, adapting as you go. The curve is shared across every patch and keeps only your most recent notes.",
             "even out a lumpy performance while keeping your own touch.",
             ["MIDI Notes", "Predictive Velocity", "Wavetable"]),
            ("Predictive Rhythm", "PREDICTION · NOTE OUT",
             "Works like Predictive Notes, but learns pitch as a distance from a root note instead of absolute pitches. What comes back is a repeating pattern anchored on one note with the occasional deviation, such as C2 C2 C2 D3 C2 C2 C2. Root is found automatically, and changing it afterwards transposes the whole pattern without relearning.",
             "play a bass riff, Learn it, then change Root to move the pattern up a fifth.",
             ["MIDI Notes", "Predictive Rhythm", "Wavetable"]),
        ],
    },
    {
        "num": "Twenty-Five",
        "n": 25,
        "title": "Sketch, Field Notes & Signals",
        "intro": "Code-drawn images and meshes, a Field script that plays notes, a MIDI file player and out, and the three Tracking nodes that turn a camera into modulators. "
                 "Sketch and Sketch 3D turn every param() call into a knob you can modulate, like any other control.",
        "cards": [
            ("Sketch", "SOURCE · IMAGE OUT",
             "Draws an image from a JavaScript sketch you write in the node, with loops, arrays and recursion and a p5.js-style API (rect, circle, line, beginShape, push/pop, translate, rotate, text). A mistake shows its line number and the last working picture stays up. Drop an .svg on the canvas to animate it by id.",
             "write one param(\"size\", 50, 5, 200) call and wire an LFO into the knob it creates.",
             ["LFO", "Sketch (size)", "Output"]),
            ("Sketch 3D", "3D · GEOMETRY OUT",
             "Builds 3D geometry from a JavaScript sketch: box, sphere, cylinder, cone, torus, tube and beginShape/vertex/endShape, moved with translate, rotate and scale. It is the loop-and-recursion counterpart of Field Primitive, and the result patches into Render 3D like any other geometry.",
             "stack a loop of rotated boxes into a spiral staircase and modulate the twist.",
             ["Sketch 3D", "Render 3D", "Output"]),
            ("Field Notes", "NOTES · NOTE OUT",
             "A note node whose body is a Field script. It runs per sample against the transport beat, and note(pitch, vel, len) inside an if sends a note out. tick(div) fires on each beat division, deg(d) is a scale degree under Root and Scale, and rand() is 0 to 1.",
             "fire a random scale degree on every eighth note and send it to a synth.",
             ["Field Notes", "Wavetable", "Audio Out"]),
            ("MIDI File", "NOTES · NOTE OUT",
             "Plays a Standard MIDI File as a note source. It follows the transport, and the project tempo rules, so the file's own tempo is ignored. Transpose, position, speed, velocity and loop are all controls, and drum-channel notes are never transposed.",
             "drop a .mid on the canvas and send it to an arpeggiator for a new take.",
             ["MIDI File", "Arpeggiator", "Wavetable"]),
            ("MIDI Out", "UTILITY · NOTE IN",
             "Plays a hardware or virtual MIDI synth from a note cable on one channel. Four CC rows send a controller number and a modulatable value only when it changes, an optional clock makes Infinite the master clock, and an offset lines up the synth's latency. Anything still held is released on delete, bypass or panic.",
             "patch an LFO into a CC row to sweep a filter on an external synth.",
             ["Note Sequencer", "MIDI Out"]),
            ("Spatial Mixer", "UTILITY · AUDIO IN",
             "Mixes audio in 3D for headphones and plays it straight to the output. Each input is a dot around a head, and its angle, distance and height change how it is heard. A limiter holds -1 dB, it records its own WAV or FLAC, and head tracking works with AirPods on macOS 14 and later.",
             "put a bass on the left, a lead on the right and a pad above your head.",
             ["Wavetable", "Spatial Mixer"]),
            ("Hand Track", "MODULATORS · IMAGE IN",
             "Tracks one hand from an image or camera wire into modulators: palm and fingertip position, pinch, open, roll and size, plus six gestures (fist, point, peace, thumbs up, ok, rock). Needs the Tracking pack from Settings > Extensions.",
             "map pinch to a bloom amount and wave your hand to play the picture.",
             ["Video In", "Hand Track", "Bloom (Amount)"]),
            ("Face Track", "MODULATORS · IMAGE IN",
             "Tracks one face into modulators: head position, turn, nod and tilt, each eye open or closed, brows, mouth open, smile, and where the eyes look. Needs the Tracking pack from Settings > Extensions.",
             "open your mouth to open a filter cutoff.",
             ["Video In", "Face Track", "Audio Filter (Cutoff)"]),
            ("Pose Track", "MODULATORS · IMAGE IN",
             "Tracks one person's body into modulators: head, both wrists, how high each arm is raised, how far apart the wrists are, lean and distance. Keep the upper body in view. Needs the Tracking pack from Settings > Extensions.",
             "raise an arm to bring a chord in.",
             ["Video In", "Pose Track", "Gain (Level)"]),
        ],
    },
    {
        "num": "Twenty-Six",
        "n": 26,
        "title": "Meshes, Curves & Dither",
        "intro": "Newer geometry operators for turning points into surfaces and cells, cleaning up curves, and a dither filter that keeps gradients smooth.",
        "cards": [
            ("Delaunay Mesh", "3D · GEOMETRY OUT",
             "Point cloud in, triangulated surface out. Points are projected onto the chosen plane, joined into Delaunay triangles, and lifted back to their real 3D positions, so a scatter with height becomes a terrain. A mesh is flagged red and ignored, so use Mesh to Points first. Max points thins very large clouds.",
             "turn a shape into points and wire them in for an instant low-poly surface.",
             ["Sphere", "Mesh to Points", "Delaunay Mesh"]),
            ("Voronoi Cells", "3D · GEOMETRY OUT",
             "Point cloud in, one polygon cell per point out, for cracked-glass and fracture looks. Every cell is the region closer to its point than to any other, and hull points are skipped. Inset pulls each cell toward its point to leave gaps.",
             "raise inset to split a flat sheet into glass shards.",
             ["Sphere", "Mesh to Points", "Voronoi Cells"]),
            ("Decimate", "3D · GEOMETRY OUT",
             "Reduces triangle count while keeping the overall shape. Keep is the fraction of triangles to leave, and Lock border holds open edges in place. UVs, colours and hard shading survive, and very low settings stop when no safe collapse remains.",
             "drop keep to 10% for a low-poly look on a dense sphere.",
             ["Sphere", "Decimate", "Render 3D"]),
            ("Curve Ops", "3D · GEOMETRY OUT",
             "Curve in, curve out. Resample spaces points evenly, Simplify drops points that barely change the shape, Smooth relaxes corners while the ends stay put, and Offset draws a parallel curve at a signed distance. The result can still drive a Path.",
             "offset a hand-drawn curve to draw a contour line around it.",
             ["Curve Ops", "Path"]),
            ("Dither", "COMPOSITING · IMAGE IN/OUT",
             "Reduces the image to a few levels per channel like Posterize, but spreads the rounding error as a fixed pattern, so gradients keep their tone instead of banding. Mode picks an ordered Bayer matrix (2, 4 or 8) or a noise pattern, and Mix blends back toward the original.",
             "set three levels with an 8x8 matrix for a retro print look.",
             ["Video", "Dither", "Output"]),
            ("NDI In", "UTILITY · IMAGE OUT",
             "Receives any NDI video source on the network as an image. Pick it from the list, which rescans in the background. Video only. Needs the free NDI runtime from ndi.video.",
             "pull a second computer's screen in and feed it through effects.",
             ["NDI In", "Bloom", "Output"]),
            ("NDI Out", "UTILITY · IMAGE IN",
             "Publishes the connected image as a named NDI video source on the local network for OBS, vMix or Resolume. Video only. Without the NDI runtime the node says so and everything else keeps working.",
             "send your finished patch to OBS with no capture card.",
             ["Video", "NDI Out"]),
        ],
    },
]

ALL_CARDS = sum(len(c["cards"]) for c in CHAPTERS)
