// GENERATED by tools/design/build_glyphs.py from art/icons/src. Do not edit.
#pragma once

namespace IconsInfinite
{
   inline constexpr unsigned kFirst = 0xE900;
   inline constexpr unsigned kLast = 0xE912;
   inline constexpr const char* Arrange = "\xee\xa4\x80"; // U+E900 arrange
   inline constexpr const char* Browser = "\xee\xa4\x81"; // U+E901 browser
   inline constexpr const char* BrowserFill = "\xee\xa4\x82"; // U+E902 browser-fill
   inline constexpr const char* Capture = "\xee\xa4\x83"; // U+E903 capture
   inline constexpr const char* CaptureFill = "\xee\xa4\x84"; // U+E904 capture-fill
   inline constexpr const char* CountIn = "\xee\xa4\x85"; // U+E905 count-in
   inline constexpr const char* Loop = "\xee\xa4\x86"; // U+E906 loop
   inline constexpr const char* Metronome = "\xee\xa4\x87"; // U+E907 metronome
   inline constexpr const char* MetronomeFill = "\xee\xa4\x88"; // U+E908 metronome-fill
   inline constexpr const char* Mixer = "\xee\xa4\x89"; // U+E909 mixer
   inline constexpr const char* ModMatrix = "\xee\xa4\x8a"; // U+E90A mod-matrix
   inline constexpr const char* Play = "\xee\xa4\x8b"; // U+E90B play
   inline constexpr const char* PlayFill = "\xee\xa4\x8c"; // U+E90C play-fill
   inline constexpr const char* Record = "\xee\xa4\x8d"; // U+E90D record
   inline constexpr const char* RecordFill = "\xee\xa4\x8e"; // U+E90E record-fill
   inline constexpr const char* Stop = "\xee\xa4\x8f"; // U+E90F stop
   inline constexpr const char* StopFill = "\xee\xa4\x90"; // U+E910 stop-fill
   inline constexpr const char* Viewport = "\xee\xa4\x91"; // U+E911 viewport
   inline constexpr const char* ViewportFill = "\xee\xa4\x92"; // U+E912 viewport-fill
}
