// GENERATED by tools/design/build_tokens.py from tokens.json. Do not edit.
#pragma once

namespace tok
{
   constexpr float space_1 = 4.0f;
   constexpr float space_2 = 8.0f;
   constexpr float space_3 = 12.0f;
   constexpr float space_4 = 16.0f;
   constexpr float radius_cell = 2.0f;
   constexpr float radius_field = 4.0f;
   constexpr float radius_tile = 6.0f;
   constexpr float radius_pill = 8.0f;
   constexpr float radius_group = 10.0f;
   constexpr float type_caption = 11.0f;
   constexpr float type_body = 13.0f;
   constexpr float type_title = 15.0f;
   constexpr float type_display = 22.0f;
   constexpr float motion_hover_in = 120.0f;
   constexpr float motion_hover_out = 180.0f;
   constexpr float motion_press = 0.0f;
   constexpr float motion_on = 160.0f;
   constexpr float motion_off = 140.0f;
   constexpr float motion_focus = 100.0f;
   constexpr float motion_tooltip_delay = 500.0f;
   constexpr float motion_tooltip_fade = 100.0f;
   constexpr float motion_accent_fade = 200.0f;
   constexpr float hit_min = 24.0f;

   struct Rgba8 { unsigned char r, g, b, a; };
   struct Rgbaf { float r, g, b, a; };
   struct Pair8 { Rgba8 dark, light; };
   struct Pairf { Rgbaf dark, light; };
   constexpr Pair8 scope_bg = { {11, 12, 16, 255}, {236, 240, 248, 255} };
   constexpr Pair8 scope_border = { {64, 68, 84, 255}, {185, 192, 208, 255} };
   constexpr Pair8 scope_grid = { {255, 255, 255, 26}, {208, 215, 228, 255} };
   constexpr Pair8 scope_midline = { {255, 255, 255, 46}, {178, 186, 204, 255} };
   constexpr Pair8 scope_text = { {120, 128, 150, 255}, {70, 78, 96, 255} };
   constexpr Pair8 backdrop_base = { {18, 18, 24, 255}, {238, 240, 246, 255} };
   constexpr Pair8 backdrop_check = { {30, 30, 38, 255}, {220, 224, 232, 255} };
   constexpr Pair8 curvebox_bg = { {22, 24, 32, 255}, {235, 238, 246, 255} };
   constexpr Pair8 curvebox_bg_hover = { {32, 35, 45, 255}, {225, 230, 240, 255} };
   constexpr Pair8 curvebox_border = { {45, 48, 62, 255}, {195, 205, 220, 255} };
   constexpr Pair8 curvebox_border_hover = { {70, 75, 95, 255}, {160, 175, 200, 255} };
   constexpr Pair8 curvebox_border_active = { {80, 160, 255, 255}, {60, 140, 240, 255} };
   constexpr Pair8 curvebox_ref = { {70, 75, 95, 120}, {170, 180, 195, 120} };
   constexpr Pair8 curve_active = { {80, 180, 255, 255}, {20, 120, 240, 255} };
   constexpr Pair8 curve_bent = { {70, 200, 230, 255}, {30, 140, 210, 255} };
   constexpr Pair8 curve_idle = { {150, 160, 180, 200}, {110, 120, 140, 200} };
   constexpr Pair8 curve_dot_bent = { {80, 200, 255, 255}, {20, 120, 240, 255} };
   constexpr Pair8 curve_dot_idle = { {140, 150, 170, 255}, {120, 130, 150, 255} };
   constexpr Pair8 curve_live = { {255, 180, 50, 255}, {235, 100, 30, 255} };
   constexpr Pair8 curve_live_ring = { {20, 20, 26, 255}, {255, 255, 255, 255} };
   constexpr Pair8 curve_value_text = { {160, 168, 185, 220}, {90, 98, 115, 220} };
   constexpr Pair8 sparkline_bg = { {20, 22, 28, 200}, {235, 238, 246, 200} };
   constexpr Pair8 sparkline_border = { {40, 44, 56, 255}, {200, 205, 215, 255} };
   constexpr Rgba8 transparent = {0, 0, 0, 0};
   constexpr Rgba8 record = {239, 68, 68, 255};
   constexpr Rgba8 danger_hover = {230, 60, 60, 255};
   constexpr Rgba8 prediction = {34, 197, 94, 255};
   constexpr Rgba8 modulation = {234, 179, 8, 255};
   constexpr Rgba8 modulation_row = {234, 179, 8, 60};
   constexpr Rgba8 inert = {110, 110, 120, 255};
   constexpr Rgba8 expression = {168, 85, 247, 255};
   constexpr Pairf dropdown_fill = { {0.16f, 0.18f, 0.24f, 1.0f}, {0.86f, 0.88f, 0.94f, 1.0f} };
   constexpr Pairf dropdown_hover = { {0.28f, 0.31f, 0.42f, 1.0f}, {0.8f, 0.84f, 0.92f, 1.0f} };
   constexpr Pairf dropdown_active = { {0.35f, 0.39f, 0.52f, 1.0f}, {0.74f, 0.78f, 0.88f, 1.0f} };
   constexpr Pairf dropdown_text = { {0.9f, 0.93f, 0.98f, 1.0f}, {0.15f, 0.18f, 0.24f, 1.0f} };
   constexpr float accent_hover = 0.36f;
   constexpr float accent_selected = 0.6f;
   constexpr float accent_pressed = 0.78f;
}
