// GENERATED by tools/design/build_tokens.py from tokens.json. Do not edit.
#pragma once

namespace tok
{
   constexpr float space_1 = 4.0f;
   constexpr float space_2 = 8.0f;
   constexpr float space_3 = 12.0f;
   constexpr float space_4 = 16.0f;
   constexpr float radius_cell = 2.0f;
   constexpr float radius_field = 4.0f;
   constexpr float radius_tile = 6.0f;
   constexpr float radius_pill = 8.0f;
   constexpr float radius_group = 10.0f;
   constexpr float type_caption = 11.0f;
   constexpr float type_body = 13.0f;
   constexpr float type_title = 15.0f;
   constexpr float type_display = 22.0f;
   constexpr float motion_hover_in = 120.0f;
   constexpr float motion_hover_out = 180.0f;
   constexpr float motion_press = 0.0f;
   constexpr float motion_on = 160.0f;
   constexpr float motion_off = 140.0f;
   constexpr float motion_focus = 100.0f;
   constexpr float motion_tooltip_delay = 500.0f;
   constexpr float motion_tooltip_fade = 100.0f;
   constexpr float motion_accent_fade = 200.0f;
   constexpr float hit_min = 24.0f;

   struct Rgba8 { unsigned char r, g, b, a; };
   struct Rgbaf { float r, g, b, a; };
   struct Pair8 { Rgba8 dark, light; };
   struct Pairf { Rgbaf dark, light; };
   constexpr Pair8 scope_bg = { {11, 12, 16, 255}, {236, 240, 248, 255} };
   constexpr Pair8 scope_border = { {64, 68, 84, 255}, {185, 192, 208, 255} };
   constexpr Pair8 scope_grid = { {255, 255, 255, 26}, {208, 215, 228, 255} };
   constexpr Pair8 scope_midline = { {255, 255, 255, 46}, {178, 186, 204, 255} };
   constexpr Pair8 scope_text = { {120, 128, 150, 255}, {70, 78, 96, 255} };
   constexpr Pair8 backdrop_base = { {18, 18, 24, 255}, {238, 240, 246, 255} };
   constexpr Pair8 backdrop_check = { {30, 30, 38, 255}, {220, 224, 232, 255} };
   constexpr Pairf dropdown_fill = { {0.16f, 0.18f, 0.24f, 1.0f}, {0.86f, 0.88f, 0.94f, 1.0f} };
   constexpr Pairf dropdown_hover = { {0.28f, 0.31f, 0.42f, 1.0f}, {0.8f, 0.84f, 0.92f, 1.0f} };
   constexpr Pairf dropdown_active = { {0.35f, 0.39f, 0.52f, 1.0f}, {0.74f, 0.78f, 0.88f, 1.0f} };
   constexpr Pairf dropdown_text = { {0.9f, 0.93f, 0.98f, 1.0f}, {0.15f, 0.18f, 0.24f, 1.0f} };
   constexpr float accent_hover = 0.36f;
   constexpr float accent_selected = 0.6f;
   constexpr float accent_pressed = 0.78f;
}
