#!/usr/bin/env python3
"""art/icons/src/*-20.svg -> external/icons/Infinite/infinite-glyphs.ttf + src/app/ui/design/Glyphs.gen.h.

Codepoints are assigned once into art/icons/codepoints.json (PUA from U+E900) and never reused or moved.
  build_glyphs.py          build
  build_glyphs.py --check  fail if outputs are stale (header only; the TTF is binary)
Needs: pip install skia-pathops fonttools
"""
import json, pathlib, sys
sys.path.insert(0, str(pathlib.Path(__file__).parent))
import glyphlib
from fontTools.fontBuilder import FontBuilder
from fontTools.pens.ttGlyphPen import TTGlyphPen
from fontTools.pens.transformPen import TransformPen
from fontTools.pens.cu2quPen import Cu2QuPen

ROOT = glyphlib.ROOT
REG = ROOT / "art/icons/codepoints.json"
TTF = ROOT / "external/icons/Infinite/infinite-glyphs.ttf"
HDR = ROOT / "src/app/ui/design/Glyphs.gen.h"
UPM, SCALE, BASE_Y = 1000, 50.0, 16.0   # 20 grid units = 1000 em; svg y=16 sits on the baseline

def cname(n):
    return "".join(p.capitalize() for p in n.replace("-20", "").split("-"))

def utf8(cp): return "".join(f"\\x{b:02x}" for b in chr(cp).encode())

def main():
    reg = json.loads(REG.read_text()) if REG.exists() else {}
    names = [f.name[:-len("-20.svg")] for f in glyphlib.icons()]
    for n in names:
        if n not in reg: reg[n] = 0xE900 + (max(reg.values()) - 0xE900 + 1 if reg else 0)
    glyphs, bad = {}, 0
    for f, n in zip(glyphlib.icons(), names):
        path, problems = glyphlib.outline(f)
        for p in problems: print(f"{f.name}: {p}"); bad += 1
        pen = TTGlyphPen(None)
        tp = TransformPen(Cu2QuPen(pen, 1.0, reverse_direction=True), (SCALE, 0, 0, -SCALE, 0, BASE_Y * SCALE))
        path.draw(tp)
        glyphs[n] = pen.glyph()
    if bad: return 1
    order = [".notdef"] + names
    notdef = TTGlyphPen(None).glyph()
    fb = FontBuilder(UPM, isTTF=True)
    fb.setupGlyphOrder(order)
    fb.setupCharacterMap({reg[n]: n for n in names})
    fb.setupGlyf({".notdef": notdef, **glyphs})
    fb.setupHorizontalMetrics({g: (UPM, 0) for g in order})
    fb.setupHorizontalHeader(ascent=800, descent=-200)
    fb.setupNameTable({"familyName": "Infinite Glyphs", "styleName": "Regular"})
    fb.setupOS2(sTypoAscender=800, sTypoDescender=-200, usWinAscent=800, usWinDescent=200)
    fb.setupPost()
    L = ["// GENERATED by tools/design/build_glyphs.py from art/icons/src. Do not edit.", "#pragma once", "",
         "namespace IconsInfinite", "{",
         f"   inline constexpr unsigned kFirst = 0x{min(reg.values()):X};", f"   inline constexpr unsigned kLast = 0x{max(reg.values()):X};"]
    for n in sorted(names, key=lambda n: reg[n]):
        L.append(f'   inline constexpr const char* {cname(n)} = "{utf8(reg[n])}"; // U+{reg[n]:X} {n}')
    L += ["}", ""]
    text = "\n".join(L)
    if "--check" in sys.argv:
        if not HDR.exists() or HDR.read_text() != text:
            print("Glyphs.gen.h is stale: run tools/design/build_glyphs.py"); return 1
        print("Glyphs.gen.h up to date"); return 0
    TTF.parent.mkdir(parents=True, exist_ok=True)
    fb.save(str(TTF)); HDR.write_text(text)
    REG.write_text(json.dumps(dict(sorted(reg.items(), key=lambda kv: kv[1])), indent=1) + "\n")
    print(f"wrote {TTF.relative_to(ROOT)} ({len(names)} glyphs), {HDR.relative_to(ROOT)}"); return 0

if __name__ == "__main__":
    sys.exit(main())
