#!/usr/bin/env python3
"""tokens.json -> Tokens.gen.h. Usage: build_tokens.py [--check]  (--check fails if the header is stale)."""
import json, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = ROOT / "src/app/ui/design/tokens.json"
OUT = ROOT / "src/app/ui/design/Tokens.gen.h"

def ident(s): return s.replace(".", "_")

def build():
    t = json.loads(SRC.read_text())
    L = ["// GENERATED by tools/design/build_tokens.py from tokens.json. Do not edit.",
         "#pragma once", "", "namespace tok", "{"]
    b = t["base"]
    for group in ("space", "radius", "type"):
        for k, v in b[group].items():
            L.append(f"   constexpr float {group}_{k} = {float(v)}f;")
    for k, v in b["motion_ms"].items():
        L.append(f"   constexpr float motion_{k} = {float(v)}f;")
    L.append(f"   constexpr float hit_min = {float(b['hit_min'])}f;")
    r = t["roles"]
    L += ["", "   struct Rgba8 { unsigned char r, g, b, a; };", "   struct Rgbaf { float r, g, b, a; };", "   struct Pair8 { Rgba8 dark, light; };", "   struct Pairf { Rgbaf dark, light; };"]
    for k, v in r["pairs"].items():
        d, l = v["dark"], v["light"]
        L.append(f"   constexpr Pair8 {ident(k)} = {{ {{{d[0]}, {d[1]}, {d[2]}, {d[3]}}}, {{{l[0]}, {l[1]}, {l[2]}, {l[3]}}} }};")
    for k, v in r.get("fixed", {}).items():
        L.append(f"   constexpr Rgba8 {ident(k)} = {{{v[0]}, {v[1]}, {v[2]}, {v[3]}}};")
    for k, v in r["pairs_f"].items():
        d, l = v["dark"], v["light"]
        f = lambda c: "{" + ", ".join(f"{x}f" for x in c) + "}"
        L.append(f"   constexpr Pairf {ident(k)} = {{ {f(d)}, {f(l)} }};")
    for k, v in r["accent_ladder"].items():
        L.append(f"   constexpr float accent_{k} = {v}f;")
    L += ["}", ""]
    return "\n".join(L)

if __name__ == "__main__":
    text = build()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            print("Tokens.gen.h is stale: run tools/design/build_tokens.py"); sys.exit(1)
        print("Tokens.gen.h up to date")
    else:
        OUT.write_text(text); print("wrote", OUT.relative_to(ROOT))
