#!/usr/bin/env python3
"""Count every UI element class per screen surface, straight from src/app.

Output: docs/plans/iconography/inventory.md. Re-run after any UI change so the
design-system plan's coverage claims stay true. Usage: python3 tools/design/inventory.py
"""
import collections, pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT = ROOT / "docs/plans/iconography/inventory.md"

SURFACES = [  # (surface, glob patterns) first match wins
    ("Top bar + menus", ["src/app/frame/StageMenuBar.cpp"]),
    ("Modulation matrix", ["src/app/panels/ModMatrixPanel.cpp", "src/app/ui/ModWidgets.cpp"]),
    ("Performance mode", ["src/app/panels/PerfPanel.cpp"]),
    ("Viewport panel", ["src/app/panels/ViewportPanel.cpp"]),
    ("Timeline / Arrange", ["src/app/panels/Arrange*.cpp", "src/arrange/*.cpp"]),
    ("Browser / Library", ["src/app/panels/LibraryPanels.cpp", "src/app/ui/BrowserUi.cpp"]),
    ("Canvas (nodes shell, cables, minimap)", ["src/app/frame/StageNodeBodies.cpp", "src/app/frame/StageLinks.cpp",
                                                "src/app/frame/StageLayout.cpp", "src/app/frame/StageFloating.cpp",
                                                "src/app/frame/StageDropHandling.cpp", "src/app/panels/Minimap.cpp"]),
    ("Node bodies", ["src/app/bodies/*.cpp"]),
    ("Shared widgets", ["src/app/ui/ParamWidgets.cpp", "src/app/ui/Theme.cpp"]),
    ("Popups + context menus", ["src/app/frame/StagePopups*.cpp"]),
    ("Side panels + docking", ["src/app/frame/StageSidePanels.cpp"]),
    ("Settings + help windows", ["src/app/panels/SettingsWindow.cpp", "src/app/panels/HelpWindows.cpp"]),
    ("Keyboard navigation", ["src/app/frame/StageKeyboard.cpp"]),
]

CLASSES = [  # (class, regex)
    ("Icon (Tabler, drawn)", r"Tabler::Draw\w+"),
    ("Icon (font glyph)", r"IconsLucide::\w+"),
    ("Button", r"ImGui::(Button|SmallButton|InvisibleButton|ImageButton|ArrowButton)\(|PrimaryButton"),
    ("Toggle (bypass/eye/viewport/scale)", r"\b(BypassToggle|EyeToggle|ViewportToggle|GlobalScaleToggle)\("),
    ("Checkbox", r"\b(ImGui::Checkbox|ModCheckbox|row\.Checkbox|\.Checkbox)\("),
    ("Dropdown", r"\b(BeginCombo|ImGui::Combo|DropdownButton|row\.Dropdown|\.Dropdown)\("),
    ("Knob", r"\b\w*Knob\w*\("),
    ("Slider / fader / drag", r"\b(SliderFloat|SliderInt|DragFloat|DragInt|ModSlider\w*|VFaderFloat|AudioSliderFloat)\("),
    ("Text / number field", r"\bInput(Text|Float|Int|TextWithHint|TextMultiline)\("),
    ("Colour swatch / picker", r"\b(ColorEdit\w*|ColorPicker\w*|ColorButton|ColorSwatch)\("),
    ("List row / tree", r"\b(Selectable|TreeNode\w*|CollapsingHeader)\("),
    ("Table", r"\bBeginTable\("),
    ("Tabs", r"\b(BeginTabBar|BeginTabItem|TabItemButton)\("),
    ("Menu / menu item", r"\b(BeginMenu|MenuItem)\("),
    ("Popup / context menu", r"\b(BeginPopup\w*|OpenPopup\w*)\("),
    ("Tooltip", r"\b(HelpTip|SetTooltip|BeginTooltip|SetItemTooltip)\("),
    ("Mouse cursor", r"SetMouseCursor\("),
    ("Drag and drop", r"\b(BeginDragDropSource|BeginDragDropTarget|AcceptDragDropPayload)\("),
    ("Mod dot / pin", r"\b(DrawDiscreteParamPin|DrawPin|CollapsedBindingPins)\("),
    ("Separator", r"\b(Separator|SeparatorText|NodeSeparator)\("),
    ("Hand-drawn shape", r"->Add(Circle|CircleFilled|Rect|RectFilled|RectFilledMultiColor|Line|Triangle|TriangleFilled|Bezier\w*|Polyline|ConvexPolyFilled|Ngon\w*)\("),
    ("Hand-drawn text", r"->AddText\("),
    ("Literal colour", r"IM_COL32\(|ImVec4\(\s*[0-9.]+f\s*,\s*[0-9.]+f\s*,\s*[0-9.]+f"),
    ("Close / cross control", r"Tabler::DrawX\b|\"[xX×]##|\"\\xc3\\x97"),
]

def files_for(globs):
    out = []
    for g in globs:
        out += sorted(ROOT.glob(g))
    return out

def main():
    grid = collections.OrderedDict()
    icons = collections.defaultdict(collections.Counter)
    for surface, globs in SURFACES:
        counts = collections.Counter()
        for f in files_for(globs):
            text = f.read_text(errors="ignore")
            for cls, rx in CLASSES:
                hits = re.findall(rx, text)
                counts[cls] += len(hits)
            for m in re.finditer(r"Tabler::Draw(\w+)", text):
                icons[m.group(1)][surface] += 1
        grid[surface] = counts

    lines = ["# UI inventory (generated)", "",
             "Generated by `tools/design/inventory.py` from `src/app` + `src/arrange`. Do not edit by hand.",
             "Counts are call sites, not on-screen instances. Test/bench files are excluded.", ""]
    surfaces = list(grid)
    lines.append("## Element classes per surface")
    lines.append("")
    lines.append("| Class | " + " | ".join(surfaces) + " | Total |")
    lines.append("|---|" + "---|" * (len(surfaces) + 1))
    for cls, _ in CLASSES:
        row = [grid[s][cls] for s in surfaces]
        lines.append(f"| {cls} | " + " | ".join(str(v) if v else "·" for v in row) + f" | **{sum(row)}** |")
    lines += ["", "## Drawn icons in use (each must get an Infinite Glyph)", "", "| Tabler icon | Uses | Surfaces |", "|---|---|---|"]
    for name, by in sorted(icons.items(), key=lambda kv: -sum(kv[1].values())):
        lines.append(f"| {name} | {sum(by.values())} | {', '.join(sorted(by))} |")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}")

if __name__ == "__main__":
    sys.exit(main())
