// Projector windows and pacing (moved verbatim from main.cpp).
#include "app/AppShared.h"

namespace app
{
   // Releases everything one projector window's OWN GL context owns, then
   // destroys the window. Every caller (the context menu, the should-close
   // poll, CloseAllProjectorWindows) runs with the MAIN context current, and
   // that is exactly the trap this function exists to close:
   //
   // A NodeViewport's destructor (NodeViewport.cpp) calls
   // glDeleteVertexArrays/glDeleteFramebuffers on mVao/mSelVao/mPointVao/mFbo.
   // Those names were generated by NodeViewport::Render inside the projector
   // window's context, because the projector blit loop makes that context
   // current before rendering. VAO and FBO names are per-context - a share
   // group does not share container objects - and they're allocated from 1
   // upward in every context independently. So deleting them with the main
   // context current does not delete "nothing": it deletes a live,
   // identically-numbered FBO or VAO belonging to some unrelated node in the
   // editor, which is why closing one projector window used to visibly
   // corrupt other nodes on the canvas. Making the owning context current
   // first sends each delete to the context that actually owns the name.
   //
   // Same reasoning for GLUtil's per-context fullscreen-quad VAO, which the
   // blit path lazily created in this context.
   //
   // Not needed for gNodeViewports / gPanelViewports / gRetiredViewports:
   // those are only ever rendered from the editor's own frame, so they are
   // created and destroyed in the main context and already agree.
   void DestroyProjectorWindow(ProjectorWindow& pw)
   {
      GLFWwindow* previous = glfwGetCurrentContext();
      if (previous == pw.window)
         previous = nullptr; // never restore the context we're about to destroy

      glfwMakeContextCurrent(pw.window);

      // Drop this node's solo-render FBO too, if it had one (geometry nodes
      // only - see gProjectorViewports). Safe to erase immediately: unlike
      // gRetiredViewports, nothing queues this texture into an ImGui draw
      // list, it's only ever read by our own immediate GL blit this frame.
      gProjectorViewports.erase(pw.nodeIndex);
      GLUtil::ReleaseCurrentContextResources();

      glfwMakeContextCurrent(previous);
      glfwDestroyWindow(pw.window);
   }


   // Closes and forgets one projector window by its position in gProjectorWindows.
   void CloseProjectorWindow(size_t i)
   {
      if (i >= gProjectorWindows.size())
         return;
      DestroyProjectorWindow(gProjectorWindows[i]);
      gProjectorWindows.erase(gProjectorWindows.begin() + (ptrdiff_t)i);
   }


   // Closes the projector window showing this node index, if any is open.
   void CloseProjectorWindowFor(int nodeIndex)
   {
      for (size_t i = 0; i < gProjectorWindows.size(); i++)
         if (gProjectorWindows[i].nodeIndex == nodeIndex)
         {
            CloseProjectorWindow(i);
            return;
         }
   }


   void CloseAllProjectorWindows()
   {
      // Per-window rather than a blanket gProjectorViewports.clear() after
      // the fact: each viewport's GL names belong to its own window's
      // context, so they have to be released while that context is still
      // alive and current. See DestroyProjectorWindow.
      for (ProjectorWindow& pw : gProjectorWindows)
         DestroyProjectorWindow(pw);
      gProjectorWindows.clear();
      // Anything left here belongs to a node whose window is already gone
      // (nothing should, DestroyProjectorWindow erases each entry) - drop it
      // so the map doesn't outlive the frame.
      gProjectorViewports.clear();
   }


   // Finds the open projector window (if any) showing this node index.
   // Replaces the inline linear-search loop the context menu used to do
   // itself every frame.
   ProjectorWindow* FindProjectorWindow(int nodeIndex)
   {
      for (ProjectorWindow& pw : gProjectorWindows)
         if (pw.nodeIndex == nodeIndex)
            return &pw;
      return nullptr;
   }


   // Which monitor a window is physically on right now, by largest overlap
   // between the window's rect and each monitor's workarea. Needed because
   // ProjectorWindow::monitorIndex only reflects where WE last placed the
   // window - it goes stale the instant the user drags the window by its
   // title bar to a different display. Returns -1 if GLFW reports no
   // monitors at all.
   int ProjectorMonitorIndex(GLFWwindow* w)
   {
      int wx, wy, ww, wh;
      glfwGetWindowPos(w, &wx, &wy);
      glfwGetWindowSize(w, &ww, &wh);

      int monitorCount = 0;
      GLFWmonitor** monitors = glfwGetMonitors(&monitorCount);
      if (monitorCount <= 0)
         return -1;

      int bestIndex = 0;
      long long bestOverlap = -1;
      for (int i = 0; i < monitorCount; i++)
      {
         int mx, my, mw, mh;
         glfwGetMonitorWorkarea(monitors[i], &mx, &my, &mw, &mh);

         const int ox0 = std::max(wx, mx);
         const int oy0 = std::max(wy, my);
         const int ox1 = std::min(wx + ww, mx + mw);
         const int oy1 = std::min(wy + wh, my + mh);
         const long long overlap = (ox1 > ox0 && oy1 > oy0)
                                       ? (long long)(ox1 - ox0) * (long long)(oy1 - oy0)
                                       : 0;
         if (overlap > bestOverlap)
         {
            bestOverlap = overlap;
            bestIndex = i;
         }
      }
      return bestIndex;
   }


   void PollTailFences()
   {
      gTailCanvasFence.Poll();
      gTailProjFence.Poll();
   }


   // Called once per frame right before the projectors present. Blocks on the
   // frame clock's display (the primary Output's, else the canvas's) while
   // FrameClockActive; otherwise releases the clock (Vsync off with no
   // projector, export running).
   void PaceProjectorPresent(GLFWwindow* canvas)
   {
      ProjectorPacer& pacer = gProjectorPacer;
      if (!FrameClockActive())
      {
         if (pacer.haveMonitor)
         {
            Platform::StopDisplayRefreshClock();
            pacer.Reset();
         }
         return;
      }

      // Which display the primary Output is on, re-read twice a second: the
      // user can drag it or fullscreen it onto another display at any time.
      const double now = glfwGetTime();
      if (!pacer.haveMonitor || now - pacer.lastMonitorCheck >= 0.5)
      {
         pacer.lastMonitorCheck = now;
         GLFWwindow* clockWindow = canvas;
         if (!gProjectorWindows.empty())
         {
            clockWindow = gProjectorWindows[0].window;
            for (const ProjectorWindow& pw : gProjectorWindows)
               if (pw.fullscreen)
               {
                  clockWindow = pw.window;
                  break;
               }
         }
         int monitorCount = 0;
         GLFWmonitor** monitors = glfwGetMonitors(&monitorCount);
         const int idx = ProjectorMonitorIndex(clockWindow);
         if (idx >= 0 && idx < monitorCount)
         {
            int mx = 0, my = 0;
            glfwGetMonitorPos(monitors[idx], &mx, &my);
            const GLFWvidmode* mode = glfwGetVideoMode(monitors[idx]);
            pacer.SetDisplay(mx, my, mode ? (double)mode->refreshRate : 0.0);
         }
      }
      if (!pacer.haveMonitor)
         return;

      if (pacer.lastPresent >= 0.0)
         pacer.AddWork((now - pacer.lastPresent) * 1000.0);
      Bench::FrameTail& tail = Bench::Tail();
      const double tailWaitStartMs = tail.active ? Bench::ScopedStageTimer::NowMs() : 0.0;
      if (tail.active)
      {
         if (pacer.lastPresent >= 0.0)
            tail.cur.workMs = (now - pacer.lastPresent) * 1000.0;
         gTailProjFence.Poll();
         tail.cur.canvasGpuPendingAtWait = gTailCanvasFence.Poll();
         tail.MarkAt(Bench::FrameTail::kMarkWaitStart, tailWaitStartMs);
      }
      if (!Platform::WaitForDisplayRefresh(pacer.monitorX, pacer.monitorY, pacer.refreshHz, pacer.intervals) &&
          pacer.refreshHz > 0.0 && pacer.lastPresent >= 0.0)
      {
         // No display clock (stalled link, display asleep): the canvas is at
         // swap interval 0 too, so hold the rate on a plain timer rather than
         // letting the whole loop run unpaced.
         const double deadline = pacer.lastPresent + (double)pacer.intervals / pacer.refreshHz;
         const double slack = deadline - glfwGetTime();
         if (slack > 0.002)
            std::this_thread::sleep_for(std::chrono::duration<double>(slack - 0.001));
         while (glfwGetTime() < deadline)
            std::this_thread::yield();
      }
      pacer.lastPresent = glfwGetTime();
      if (tail.active)
      {
         tail.lastWaitEndMs = Bench::ScopedStageTimer::NowMs();
         tail.cur.waitMs = tail.lastWaitEndMs - tailWaitStartMs;
         PollTailFences();
      }
   }


   // Enters or leaves fullscreen on a projector window, targeting a specific
   // monitor. Deliberately NOT exclusive GLFW fullscreen
   // (glfwSetWindowMonitor with a monitor) - exclusive fullscreen is exactly
   // what auto-iconifies / drops the window behind the editor the moment
   // keyboard focus moves to the other display, which is the original bug.
   // Borderless + always-on-top (topmost on Windows, GLFW_FLOATING on macOS)
   // keeps the output window visible and undecorated while leaving the
   // editor window free to keep keyboard focus. Do not "simplify" this back
   // to glfwSetWindowMonitor.
   void SetProjectorFullscreen(ProjectorWindow& pw, int monitorIndex, bool fullscreen)
   {
      GLFWwindow* w = pw.window;

      int monitorCount = 0;
      GLFWmonitor** monitors = glfwGetMonitors(&monitorCount);
      if (monitorCount <= 0)
         return;
      monitorIndex = std::clamp(monitorIndex, 0, monitorCount - 1);
      GLFWmonitor* monitor = monitors[monitorIndex];

      if (fullscreen)
      {
         if (!pw.fullscreen)
         {
            // Save the current windowed box so Leaving can restore it.
            glfwGetWindowPos(w, &pw.windowedX, &pw.windowedY);
            glfwGetWindowSize(w, &pw.windowedW, &pw.windowedH);
         }

         const GLFWvidmode* mode = glfwGetVideoMode(monitor);
         int mx, my;
         glfwGetMonitorPos(monitor, &mx, &my);

#if defined(_WIN32)
         // Windows: hand the monitor rect to ConfigureOutputWindow so the
         // frame removal and the resize happen in one SetWindowPos. Sizing
         // first with glfwSetWindowSize would set the *client* area of a
         // still-decorated window to the full video mode, and stripping the
         // frame afterwards would leave the window larger than the monitor,
         // hanging off the bottom-right. See Platform.h's comment on
         // ConfigureOutputWindow.
         Platform::ConfigureOutputWindow(w, /*borderless=*/true, /*topmost=*/true, /*hideCursor=*/true,
                                         mx, my,
                                         mode != nullptr ? mode->width : 0,
                                         mode != nullptr ? mode->height : 0);
         if (mode == nullptr)
            glfwSetWindowPos(w, mx, my); // no video mode to size to; at least place it
#else
         // macOS: GLFW_DECORATED keeps the content rect when the frame goes
         // away, so sizing first is correct here and stays untouched.
         glfwSetWindowPos(w, mx, my);
         if (mode != nullptr)
            glfwSetWindowSize(w, mode->width, mode->height);
         glfwSetWindowAttrib(w, GLFW_DECORATED, GLFW_FALSE);
         glfwSetWindowAttrib(w, GLFW_FLOATING, GLFW_TRUE);
         glfwSetInputMode(w, GLFW_CURSOR, GLFW_CURSOR_HIDDEN);
#endif
      }
      else
      {
         // Restore the saved windowed box, clamped to the target monitor's
         // workarea - re-centre it if the saved rect no longer intersects
         // that monitor at all (e.g. it was placed on a display that's since
         // been unplugged or the box was saved on a different monitor).
         int mx, my, mw, mh;
         glfwGetMonitorWorkarea(monitor, &mx, &my, &mw, &mh);

         int rx = pw.windowedX, ry = pw.windowedY;
         int rw = std::min(pw.windowedW, mw);
         int rh = std::min(pw.windowedH, mh);

         const bool intersects = (rx < mx + mw) && (rx + rw > mx) && (ry < my + mh) && (ry + rh > my);
         if (!intersects)
         {
            rx = mx + (mw - rw) / 2;
            ry = my + (mh - rh) / 2;
         }
         else
         {
            rx = std::clamp(rx, mx, mx + mw - rw);
            ry = std::clamp(ry, my, my + mh - rh);
         }

#if defined(_WIN32)
         Platform::ConfigureOutputWindow(w, /*borderless=*/false, /*topmost=*/false, /*hideCursor=*/false);
#else
         glfwSetWindowAttrib(w, GLFW_DECORATED, GLFW_TRUE);
         glfwSetWindowAttrib(w, GLFW_FLOATING, GLFW_FALSE);
         glfwSetInputMode(w, GLFW_CURSOR, GLFW_CURSOR_NORMAL);
#endif
         glfwSetWindowPos(w, rx, ry);
         glfwSetWindowSize(w, rw, rh);
      }

      pw.fullscreen = fullscreen;
      pw.monitorIndex = monitorIndex;
      if (const char* name = glfwGetMonitorName(monitor))
         pw.monitorName = name;
      if (fullscreen)
         pw.returnToMonitor.clear();
      glfwShowWindow(w);
   }

   // Display hot-plug. Called once a frame; does nothing unless the set of monitors changed. A fullscreen output whose
   // display went away drops to its windowed box on a remaining display (so the show keeps rendering and stays
   // visible) and remembers that display; when one of the same name comes back it goes fullscreen there again.
   // Polled rather than callback-driven: glfwGetMonitors is cached by GLFW, so the poll costs a few string compares,
   // and the same code runs on macOS, Windows and Linux.
   void UpdateProjectorsForMonitors()
   {
      if (gProjectorWindows.empty())
         return;
      int count = 0;
      GLFWmonitor** monitors = glfwGetMonitors(&count);
      std::string sig;
      for (int i = 0; i < count; i++)
      {
         const char* n = glfwGetMonitorName(monitors[i]);
         sig += (n != nullptr ? n : "?");
         sig += '|';
      }
      static std::string sLast;
      if (sig == sLast)
         return;
      sLast = sig;
      if (count <= 0)
         return;
      auto find = [&](const std::string& name) {
         for (int i = 0; i < count; i++)
         {
            const char* n = glfwGetMonitorName(monitors[i]);
            if (n != nullptr && name == n)
               return i;
         }
         return -1;
      };
      for (ProjectorWindow& pw : gProjectorWindows)
      {
         if (pw.fullscreen)
         {
            const int at = find(pw.monitorName);
            if (at < 0)
            {
               const std::string gone = pw.monitorName;
               SetProjectorFullscreen(pw, 0, false);
               pw.returnToMonitor = gone;
            }
            else
               pw.monitorIndex = at;
         }
         else if (!pw.returnToMonitor.empty())
         {
            const int at = find(pw.returnToMonitor);
            if (at >= 0)
               SetProjectorFullscreen(pw, at, true);
         }
      }
   }


   // Moves a projector window to a different monitor. If it's fullscreen,
   // re-enters fullscreen on the new monitor; otherwise just centres the
   // existing windowed box in the new monitor's workarea (shrinking it to
   // fit if needed) and records the new monitorIndex.
   void MoveProjectorToMonitor(ProjectorWindow& pw, int monitorIndex)
   {
      if (pw.fullscreen)
      {
         SetProjectorFullscreen(pw, monitorIndex, true);
         return;
      }

      int monitorCount = 0;
      GLFWmonitor** monitors = glfwGetMonitors(&monitorCount);
      if (monitorCount <= 0)
         return;
      monitorIndex = std::clamp(monitorIndex, 0, monitorCount - 1);
      GLFWmonitor* monitor = monitors[monitorIndex];

      int mx, my, mw, mh;
      glfwGetMonitorWorkarea(monitor, &mx, &my, &mw, &mh);

      int ww, wh;
      glfwGetWindowSize(pw.window, &ww, &wh);
      ww = std::min(ww, mw);
      wh = std::min(wh, mh);

      const int x = mx + (mw - ww) / 2;
      const int y = my + (mh - wh) / 2;
      glfwSetWindowPos(pw.window, x, y);
      glfwSetWindowSize(pw.window, ww, wh);

      pw.monitorIndex = monitorIndex;
   }


   // F11-style toggle. Going IN, targets whichever monitor the window is
   // physically on right now (ProjectorMonitorIndex) rather than the stored
   // monitorIndex, since the user may have dragged it since it was last
   // moved programmatically. Going OUT, uses the stored monitorIndex (the
   // monitor fullscreen actually filled) so the restored box is clamped
   // against the right workarea.
   void ToggleProjectorFullscreen(ProjectorWindow& pw)
   {
      if (pw.fullscreen)
         SetProjectorFullscreen(pw, pw.monitorIndex, false);
      else
         SetProjectorFullscreen(pw, ProjectorMonitorIndex(pw.window), true);
   }


   // F11 toggles fullscreen; Escape leaves fullscreen and ONLY that - it
   // must never close the window (that's still "Close window" from the
   // context menu / the OS close button).
   void ProjectorKeyCallback(GLFWwindow* window, int key, int /*scancode*/, int action, int /*mods*/)
   {
      if (action != GLFW_PRESS)
         return;

      ProjectorWindow* pw = nullptr;
      for (ProjectorWindow& p : gProjectorWindows)
         if (p.window == window)
         {
            pw = &p;
            break;
         }
      if (pw == nullptr)
         return;

      if (key == GLFW_KEY_F11)
         ToggleProjectorFullscreen(*pw);
      else if (key == GLFW_KEY_ESCAPE && pw->fullscreen)
         SetProjectorFullscreen(*pw, pw->monitorIndex, false);
   }


   // Opens a new projector window on `gn`. An ordinary decorated/resizable
   // window at first - fullscreen (borderless + always-on-top) is entered
   // explicitly via F11 or the "Output window" context menu, not by the OS's
   // own window controls; see SetProjectorFullscreen for why. Any number of
   // these can be open at once, one per node. `mainWindow` is passed in as
   // the GL share context so the projector window sees the exact same
   // textures/FBOs the editor already produced - no cross-context copy.
   void OpenProjectorWindow(GLFWwindow* mainWindow, GraphNode& gn)
   {
      // Already have one open for this node - nothing to do (the context menu
      // offers "Close window" instead once one exists).
      for (const ProjectorWindow& pw : gProjectorWindows)
         if (pw.nodeIndex == gn.index)
            return;

      int w = gn.node->GetOutputWidth();
      int h = gn.node->GetOutputHeight();
      if (w <= 0 || h <= 0)
      {
         w = 1280;
         h = 720;
      }

      // Open at a *positioning* size, not the source's native size - a 4K
      // source opening a 4K window is unusable to drag around on a 1080p
      // laptop panel. F11/fullscreen resizes it to the target monitor's full
      // mode anyway, so this only affects the windowed box.
      const double scale = std::min(1.0, std::min(960.0 / (double)w, 540.0 / (double)h));
      w = std::max(320, (int)(w * scale));
      h = std::max(180, (int)(h * scale));

      glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
      // 3.3, not 3.2: glad (non-Apple loader, see below) only populates a
      // version block's function pointers when glGetString(GL_VERSION)
      // reports it was actually granted, and glVertexAttribDivisor - used by
      // every instanced draw in the app - is a 3.3 entry point. A driver that
      // honours a literal 3.2 request (Mesa-on-D3D12, some Intel iGPU/RDP/VM
      // stacks) leaves it null, so any instanced draw is an access violation
      // there today. All 56 shaders in the tree are #version 150 and stay
      // valid unchanged under a 3.3 context.
      glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
      glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
      glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GLFW_TRUE);
      glfwWindowHint(GLFW_DECORATED, GLFW_TRUE);
      glfwWindowHint(GLFW_RESIZABLE, GLFW_TRUE);
      // GLFW window hints are sticky global state - without resetting this,
      // an earlier window that went fullscreen (which sets FLOATING TRUE)
      // would leak that attribute into every later window created.
      glfwWindowHint(GLFW_FLOATING, GLFW_FALSE);
      // Alpha-capable window: a node with a transparent background shows the
      // desktop through the windowed Output (OBS window capture) instead of a
      // checkerboard. Sticky like the hints above, so set explicitly and
      // reset after creation; opaque output is unaffected (alpha 1).
      glfwWindowHint(GLFW_TRANSPARENT_FRAMEBUFFER, GLFW_TRUE);
      GLFWwindow* projWindow = glfwCreateWindow(w, h, NodeTitleWithInstance(gn).c_str(), nullptr, mainWindow);
      glfwWindowHint(GLFW_TRANSPARENT_FRAMEBUFFER, GLFW_FALSE);
      if (projWindow == nullptr)
      {
         glfwMakeContextCurrent(mainWindow);
         return;
      }
      SetWindowIcon(projWindow);

      // Offset from the main window rather than wherever the OS happens to
      // drop it, so opening several in a row doesn't stack them exactly on
      // top of each other.
      int mainX = 0, mainY = 0;
      glfwGetWindowPos(mainWindow, &mainX, &mainY);
      glfwSetWindowPos(projWindow, mainX + 60, mainY + 60);

      glfwSetKeyCallback(projWindow, ProjectorKeyCallback);

      // Projector contexts never wait in their swap: the loop is paced by the
      // primary Output display's refresh clock (PaceProjectorPresent), so a
      // driver-default interval here would be a second vsync wait per frame
      // per window. The canvas drops to 0 too while any projector is open.
      glfwMakeContextCurrent(projWindow);
      glfwSwapInterval(0);
      glfwMakeContextCurrent(mainWindow);
      ApplyCanvasSwapInterval();

      ProjectorWindow pw;
      pw.window = projWindow;
      pw.nodeIndex = gn.index;
      pw.windowedX = mainX + 60;
      pw.windowedY = mainY + 60;
      pw.windowedW = w;
      pw.windowedH = h;
      pw.monitorIndex = ProjectorMonitorIndex(projWindow);
      gProjectorWindows.push_back(pw);
   }
}
