#!/usr/bin/env python3
"""Build the brand book and its token files from docs/brand/brand.json.

    python3 tools/brand/build_brand_book.py

Writes docs/brand/brand-book.html (the visual book), docs/brand/brand.css (CSS custom properties per mode),
docs/brand/brand.tokens.json (Design Tokens Community Group format, 2025.10) and docs/brand/img/*.webp (the 3D
renders from tools/brand/build_3d.py, resized). Exits 1 if any pair in colour.contrast_gate misses its WCAG 2.2
ratio, so a palette edit cannot ship an unreadable pairing. The rules are in docs/brand/BRAND.md; every number on
the page is computed here from the JSON, so the book cannot drift from the tokens."""
import glob
import html
import json
import math
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import colour as K  # noqa: E402

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
DOC = os.path.join(ROOT, "docs", "brand")
B = json.load(open(os.path.join(DOC, "brand.json")))
C = B["colour"]
MODES = C["modes"]
E = html.escape


# ---------------------------------------------------------------- contrast gate
def gate():
    rows, bad = [], []
    for mode, roles in MODES.items():
        for fgk, bgk, need in C["contrast_gate"]["pairs"]:
            f, b = roles[fgk], roles[bgk]
            r = K.wcag(f, b)
            lc = K.apca(f, b)
            ok = r >= need
            rows.append((mode, fgk, bgk, f, b, r, lc, need, ok))
            if not ok:
                bad.append(f"{mode}: {fgk} {f} on {bgk} {b} = {r:.2f}, needs {need}")
    return rows, bad


GATE, BAD = gate()
if BAD:
    print("contrast gate FAILED:\n  " + "\n  ".join(BAD))
    sys.exit(1)


# ---------------------------------------------------------------- springs
def spring(z, w, t):
    if z < 1:
        wd = w * math.sqrt(1 - z * z)
        return 1 - math.exp(-z * w * t) * (math.cos(wd * t) + z / math.sqrt(1 - z * z) * math.sin(wd * t))
    return 1 - (1 + w * t) * math.exp(-w * t)


def spring_stats(z, w):
    over = math.exp(-math.pi * z / math.sqrt(1 - z * z)) if z < 1 else 0.0
    t, dt, settle = 0.0, 0.0005, 0.0
    while t < 3:
        if abs(spring(z, w, t) - 1) > 0.02:
            settle = t
        t += dt
    return over, settle + dt


def css_linear(z, w, n=32):
    _, T = spring_stats(z, w)
    pts = [f"{spring(z, w, T * i / n):.3f}".rstrip("0").rstrip(".") or "0" for i in range(n + 1)]
    pts[-1] = "1"
    return f"linear({', '.join(pts)})", round(T * 1000)


SPRINGS = []
for s in B["motion"]["springs"]:
    o, st = spring_stats(s["zeta"], s["omega"])
    lin, ms = css_linear(s["zeta"], s["omega"])
    SPRINGS.append(dict(s, overshoot=o, settle_ms=ms, linear=lin, response=2 * math.pi / s["omega"]))


# ---------------------------------------------------------------- token files
def fluid(mn, mx, lo=375, hi=1440):
    if mn == mx:
        return f"{mn / 16:.4g}rem"
    slope = (mx - mn) / (hi - lo)
    base = mn - slope * lo
    return f"clamp({mn / 16:.4g}rem, {base / 16:.4g}rem + {slope * 100:.4g}vw, {mx / 16:.4g}rem)"


def slug(s):
    return s.lower().replace(" ", "-").replace(",", "")


def write_css():
    L = ["/* Generated by tools/brand/build_brand_book.py from docs/brand/brand.json. Do not edit. */",
         "/* Usage: <html data-mode=\"midnight|mist|paper\">; paper is the default. */"]
    for i, (mode, roles) in enumerate(MODES.items()):
        sel = ":root, [data-mode=\"paper\"]" if mode == "paper" else f"[data-mode=\"{mode}\"]"
        L.append(f"{sel} {{")
        L += [f"  --{k}: {v};" for k, v in roles.items() if not k.startswith("_")]
        L.append("}")
    L.append(":root {")
    for fam, pal in (("ember", C["anchors"]["ember"]), ("signal", C["anchors"]["signal"]), ("midnight", C["anchors"]["midnight"])):
        L += [f"  --{fam}-{k}: {v};" for k, v in pal.items()]
    g = C["gradient"]
    L.append(f"  --brand-gradient: linear-gradient(90deg, {', '.join(f'{h} {p * 100:g}%' for h, p in zip(g['stops'], g['positions']))});")
    L.append(f"  --iridescence: conic-gradient({', '.join(C['iridescence']['stops'])});")
    for c in C["category"]:
        L.append(f"  --cat-{slug(c['name'])}: {c['hex']};")
    for s in B["type"]["web_scale"]:
        fam = "'Geist Mono', ui-monospace, monospace" if "mono" in s["step"].lower() else "Geist, system-ui, sans-serif"
        L.append(f"  --type-{slug(s['step'])}: {s['weight']} {fluid(s['min'], s['max'])}/{s['leading']} {fam};")
        L.append(f"  --track-{slug(s['step'])}: {s['tracking']}em;")
    for r in B["shape"]["brand_radius"]:
        L.append(f"  --radius-{slug(r['name'])}: {r['px']}px;")
    for i, sp in enumerate(B["shape"]["space"]):
        L.append(f"  --space-{i + 1}: {sp}px;")
    for e in B["motion"]["eases"]:
        L.append(f"  --{e['name']}: {e['value']};")
    for s in SPRINGS:
        L.append(f"  --spring-{s['name']}: {s['linear']};")
        L.append(f"  --spring-{s['name']}-ms: {s['settle_ms']}ms;")
    for k, v in B["motion"]["durations_ms"].items():
        L.append(f"  --dur-{k}: {v}ms;")
    L.append("}")
    L.append("@media (prefers-reduced-motion: reduce) { :root { " + " ".join(f"--dur-{k}: 0ms;" for k in B["motion"]["durations_ms"]) + " } }")
    open(os.path.join(DOC, "brand.css"), "w").write("\n".join(L) + "\n")


def write_dtcg():
    def col(h):
        return {"$type": "color", "$value": {"colorSpace": "srgb", "components": [round(x, 4) for x in K.rgb(h)], "hex": h}}
    t = {"$description": "Infinite brand tokens (DTCG 2025.10). Generated from docs/brand/brand.json.",
         "mode": {m: {k: col(v) for k, v in r.items() if not k.startswith("_") and v.startswith("#")} for m, r in MODES.items()},
         "palette": {f: {k: col(v) for k, v in p.items()} for f, p in C["anchors"].items()},
         "category": {slug(c["name"]): col(c["hex"]) for c in C["category"]},
         "radius": {slug(r["name"]): {"$type": "dimension", "$value": {"value": r["px"], "unit": "px"}} for r in B["shape"]["brand_radius"]},
         "space": {str(s): {"$type": "dimension", "$value": {"value": s, "unit": "px"}} for s in B["shape"]["space"]},
         "duration": {k: {"$type": "duration", "$value": {"value": v, "unit": "ms"}} for k, v in B["motion"]["durations_ms"].items()},
         "easing": {e["name"]: {"$type": "cubicBezier", "$value": [float(x) for x in e["value"][13:-1].split(",")]} for e in B["motion"]["eases"]},
         "font": {slug(f["name"]): {"$type": "fontFamily", "$value": f["name"]} for f in B["type"]["families"] if f["weights"]}}
    json.dump(t, open(os.path.join(DOC, "brand.tokens.json"), "w"), indent=2)


def write_images():
    out = os.path.join(DOC, "img")
    os.makedirs(out, exist_ok=True)
    done = []
    try:
        from PIL import Image
    except ImportError:
        return done
    for p in sorted(glob.glob(os.path.join(ROOT, "art", "brand", "3d", "renders", "*.png"))):
        n = os.path.basename(p)[:-4]
        im = Image.open(p).convert("RGB")
        if im.width > 1600:
            im = im.resize((1600, round(im.height * 1600 / im.width)), Image.LANCZOS)
        im.save(os.path.join(out, n + ".webp"), quality=86, method=6)
        done.append(n)
    return done


write_css()
write_dtcg()
IMGS = write_images()


# ---------------------------------------------------------------- figures (SVG, computed)
def lem_path(A, cx, cy, n=240):
    pts = []
    for i in range(n + 1):
        p = 2 * math.pi * i / n
        d = 1 + math.cos(p) ** 2
        pts.append((cx + A * math.sin(p) / d, cy - A * math.sin(p) * math.cos(p) / d))
    return "M" + " L".join(f"{x:.2f},{y:.2f}" for x, y in pts) + "Z"


def grad_def(gid, x0, x1):
    g = C["gradient"]
    st = "".join(f'<stop offset="{p}" stop-color="{h}"/>' for h, p in zip(g["stops"], g["positions"]))
    return f'<linearGradient id="{gid}" gradientUnits="userSpaceOnUse" x1="{x0}" y1="0" x2="{x1}" y2="0">{st}</linearGradient>'


def mark(A=100, pad=None, gid="g0"):
    s = B["logo"]["stroke"] * A
    w, h = 2 * A + s, A / math.sqrt(2) + s
    pad = s / 2 if pad is None else pad
    W, H = w + 2 * pad, h + 2 * pad
    return (f'<svg viewBox="0 0 {W:.1f} {H:.1f}" role="img" aria-label="Infinite mark"><defs>{grad_def(gid, pad, pad + w)}</defs>'
            f'<path d="{lem_path(A, W / 2, H / 2)}" fill="none" stroke="url(#{gid})" stroke-width="{s:.2f}" stroke-linejoin="round"/></svg>')


def fig_construction():
    A, s = 200, B["logo"]["stroke"] * 200
    W, H = 760, 470
    cx, cy = W / 2, H / 2 - 4
    w, h = 2 * A + s, A / math.sqrt(2) + s
    m = MODES["mist"]
    lines = [f'<rect width="{W}" height="{H}" fill="{m["surface-1"]}" rx="16"/>']
    cs = 2 * s
    lines.append(f'<rect x="{cx - w / 2 - cs:.1f}" y="{cy - h / 2 - cs:.1f}" width="{w + 2 * cs:.1f}" height="{h + 2 * cs:.1f}" fill="none" stroke="{m["accent"]}" stroke-dasharray="6 6" stroke-width="1.2"/>')
    lines.append(f'<rect x="{cx - w / 2:.1f}" y="{cy - h / 2:.1f}" width="{w:.1f}" height="{h:.1f}" fill="none" stroke="{m["line"]}" stroke-width="1"/>')
    lines.append(f'<line x1="{cx - A - 40}" y1="{cy}" x2="{cx + A + 40}" y2="{cy}" stroke="{m["line"]}"/><line x1="{cx}" y1="{cy - h / 2 - 20}" x2="{cx}" y2="{cy + h / 2 + 20}" stroke="{m["line"]}"/>')
    for sgn in (1, -1):
        lines.append(f'<line x1="{cx - 70}" y1="{cy + sgn * 70}" x2="{cx + 70}" y2="{cy - sgn * 70}" stroke="{m["signal"]}" stroke-dasharray="3 4"/>')
    lines.append(f'<defs>{grad_def("gc", cx - w / 2, cx + w / 2)}</defs><path d="{lem_path(A, cx, cy)}" fill="none" stroke="url(#gc)" stroke-width="{s:.1f}" opacity=".9"/>')
    lines.append(f'<path d="{lem_path(A, cx, cy)}" fill="none" stroke="{m["ink"]}" stroke-width="1"/>')
    for x in (cx - A, cx + A):
        lines.append(f'<circle cx="{x}" cy="{cy}" r="3.5" fill="{m["ink"]}"/>')
    t = 'font-family="Geist Mono" font-size="12" fill="' + m["ink-2"] + '"'
    lines.append(f'<text x="{cx + A / 2}" y="{cy + 18}" {t} text-anchor="middle">A</text>')
    lines.append(f'<text x="{cx - w / 2}" y="{cy - h / 2 - cs - 8}" {t}>clear space 2s</text>')
    lines.append(f'<text x="{cx + 18}" y="{cy - h / 2 - 12}" {t}>45° tangents, 90° crossing</text>')
    lines.append(f'<text x="{cx + A + s / 2}" y="{cy + h / 2 + 20}" {t} text-anchor="end">s = 87/338 A</text>')
    lines.append(f'<text x="{cx - w / 2}" y="{cy + h / 2 + cs + 22}" {t}>2.2574 A × 0.9645 A   ·   arc 5.2441 A</text>')
    return f'<svg viewBox="0 0 {W} {H}" role="img" aria-label="Logo construction">{"".join(lines)}</svg>'


def fig_ramp(fam):
    f = C["families"][fam]
    r = K.ramp(f["hue"], f["chroma"], C["ramp_steps"])
    anch = C["anchors"].get(fam, {})
    cells = []
    for k, h in r.items():
        use = anch.get(k, h)
        L, Cc, H = K.oklch(use)
        tc = "#12152A" if K.wcag(use, "#12152A") > K.wcag(use, "#FFFFFF") else "#FFFFFF"
        cells.append(f'<div class="rc" style="background:{use};color:{tc}"><b>{k}</b><code>{use}</code><small>L{L:.2f} C{Cc:.2f}</small>{"<i>anchor</i>" if k in anch else ""}</div>')
    return f'<div class="ramp"><h4>{fam.title()} <code>H {f["hue"]}</code></h4><div class="rr">{"".join(cells)}</div><p>{E(f["role"])}</p></div>'


def mode_panel(name, r):
    chips = []
    for k in ("ground", "deep", "surface-1", "surface-2", "surface-3", "line", "ink", "ink-2", "ink-3", "signal", "accent", "accent-ink"):
        chips.append(f'<div class="chip"><i style="background:{r[k]}"></i><b>{k}</b><code>{r[k]}</code></div>')
    return (f'<div class="mode" style="background:{r["ground"]};color:{r["ink"]}"><div class="mh"><b>{name.title()}</b><span style="color:{r["ink-3"]}">{E(r["_doc"])}</span></div>'
            f'<div class="msurf" style="background:{r["surface-1"]}"><p style="color:{r["ink"]}">The cable is the point.</p><p style="color:{r["ink-2"]}">Secondary text sits on ink-2.</p>'
            f'<p style="color:{r["ink-3"]};font-family:Geist Mono;font-size:12px">ink-3 · 120 BPM · 4.00 ms</p><p><span class="btn" style="background:{r["accent-ink"] if name != "midnight" else r["accent"]};color:{r["on-accent"]}">Download</span>'
            f' <span style="color:{r["signal"]};font-weight:600">Signal link</span></p></div><div class="chips">{"".join(chips)}</div></div>')


def gate_table():
    rows = "".join(f'<tr><td>{m}</td><td><span class="dot" style="background:{f}"></span>{a}</td><td><span class="dot" style="background:{b}"></span>{bk}</td>'
                   f'<td><b>{r:.2f}</b></td><td>{need:g}</td><td>{lc:+.0f}</td><td class="{"ok" if ok else "no"}">{"pass" if ok else "fail"}</td></tr>'
                   for m, a, bk, f, b, r, lc, need, ok in GATE)
    return f'<table class="t"><tr><th>mode</th><th>text</th><th>on</th><th>WCAG</th><th>needs</th><th>APCA Lc</th><th></th></tr>{rows}</table>'


def cvd_strip():
    pairs = [("Ember", C["anchors"]["ember"]["400"]), ("Signal", C["anchors"]["signal"]["300"]), ("Modulation", [r for r in C["role"] if r["name"] == "Modulation"][0]["dark"]),
             ("Record", "#BE3434"), ("Go", "#2EAA4A")]
    rows = []
    for kind in ("normal", "protan", "deutan", "tritan"):
        cells = "".join(f'<i style="background:{h if kind == "normal" else K.cvd(h, kind)}" title="{n}"></i>' for n, h in pairs)
        a = C["anchors"]["ember"]["400"]
        b = C["anchors"]["signal"]["300"]
        de = K.delta_e(a, b) if kind == "normal" else K.delta_e(K.cvd(a, kind), K.cvd(b, kind))
        rows.append(f'<div class="cvd"><code>{kind}</code><div>{cells}</div><span>Ember vs Signal ΔE {de:.0f}</span></div>')
    return f'<div class="cvds" style="background:{MODES["midnight"]["ground"]}">{"".join(rows)}<p>Swatches: {", ".join(n for n, _ in pairs)}. Simulation: Machado, Oliveira and Fernandes 2009, severity 1.</p></div>'


def collisions():
    cats = C["category"]
    out = []
    for i, a in enumerate(cats):
        for b in cats[i + 1:]:
            worst = min([("normal", K.delta_e(a["hex"], b["hex"]))] + [(k, K.delta_e(K.cvd(a["hex"], k), K.cvd(b["hex"], k))) for k in ("protan", "deutan", "tritan")], key=lambda x: x[1])
            if worst[1] < 6:
                out.append((worst[1], a, b, worst[0]))
    out.sort(key=lambda x: x[0])
    rows = "".join(f'<tr><td><span class="dot" style="background:{a["hex"]}"></span>{a["name"]}</td><td><span class="dot" style="background:{b["hex"]}"></span>{b["name"]}</td><td>{k}</td><td><b>{d:.1f}</b></td></tr>' for d, a, b, k in out[:10])
    return f'<table class="t"><tr><th>category</th><th>vs</th><th>worst vision</th><th>ΔE OK</th></tr>{rows}</table>'


def fig_springs():
    W, H, pl, pb = 640, 300, 44, 34
    T = 0.45
    paths = []
    cols = [C["anchors"]["ember"]["500"], MODES["mist"]["signal"], "#1E9646", MODES["mist"]["ink-3"]]
    for i, (s, colr) in enumerate(zip(SPRINGS, cols)):
        pts = [(pl + (W - pl - 12) * t / 200, H - pb - (H - pb - 20) * spring(s["zeta"], s["omega"], T * t / 200) / 1.2) for t in range(201)]
        paths.append(f'<path d="M{" L".join(f"{x:.1f},{y:.1f}" for x, y in pts)}" fill="none" stroke="{colr}" stroke-width="2.4"/>')
        j = (24, 30, 40, 52)[i]
        paths.append(f'<text x="{pts[j][0] + 8}" y="{pts[j][1] + 4}" font-family="Geist Mono" font-size="11" fill="{colr}">{s["name"]}</text>')
    y1 = H - pb - (H - pb - 20) / 1.2
    grid = f'<line x1="{pl}" y1="{y1:.1f}" x2="{W - 12}" y2="{y1:.1f}" stroke="#C4C1D9" stroke-dasharray="4 4"/><line x1="{pl}" y1="{H - pb}" x2="{W - 12}" y2="{H - pb}" stroke="#C4C1D9"/>'
    ticks = "".join(f'<text x="{pl + (W - pl - 12) * ms / 450:.1f}" y="{H - 12}" font-family="Geist Mono" font-size="10" fill="#5A6180" text-anchor="middle">{ms}</text>' for ms in (0, 100, 200, 300, 400))
    return f'<svg viewBox="0 0 {W} {H}" role="img" aria-label="Spring step responses">{grid}{ticks}<text x="{pl - 8}" y="{y1 + 4:.1f}" font-family="Geist Mono" font-size="10" fill="#5A6180" text-anchor="end">1</text>{"".join(paths)}<text x="{W - 12}" y="{H - 12}" font-family="Geist Mono" font-size="10" fill="#5A6180" text-anchor="end">ms</text></svg>'


def fig_frame(w, h, label, safe=None, cols=0, extra=""):
    sc = 220 / max(w, h)
    W, H = w * sc, h * sc
    m = MODES["midnight"]
    parts = [f'<rect width="{W:.1f}" height="{H:.1f}" rx="6" fill="{m["ground"]}"/>']
    if safe:
        sx, sy = W * safe, H * safe
        parts.append(f'<rect x="{sx:.1f}" y="{sy:.1f}" width="{W - 2 * sx:.1f}" height="{H - 2 * sy:.1f}" fill="none" stroke="{m["signal"]}" stroke-dasharray="3 3" stroke-width=".8"/>')
        if cols:
            cw = (W - 2 * sx) / cols
            parts += [f'<rect x="{sx + i * cw + .5:.1f}" y="{sy:.1f}" width="{cw - 1:.1f}" height="{H - 2 * sy:.1f}" fill="{m["signal"]}" opacity=".08"/>' for i in range(cols)]
    parts.append(extra.format(W=W, H=H))
    return f'<figure class="fr"><svg viewBox="-1 -1 {W + 2:.1f} {H + 2:.1f}" width="{W:.0f}" role="img" aria-label="{E(label)}">{"".join(parts)}</svg><figcaption>{E(label)}<code>{w}×{h}</code></figcaption></figure>'


def grids():
    g = B["grid"]
    v = g["film_9x16"]
    tall = fig_frame(1080, 1920, "9:16 owner box: top 14%, bottom 22%, right column clear 40-85%", extra=(
        '<rect x="0" y="0" width="{W}" height="' + f"{220 * v['top']:.1f}" + '" fill="#FF6B35" opacity=".2"/>'
        '<rect x="0" y="' + f"{220 * v['bottom']:.1f}" + '" width="{W}" height="' + f"{220 * (1 - v['bottom']):.1f}" + '" fill="#FF6B35" opacity=".2"/>'
        '<rect x="' + f"{220 * 9 / 16 * (1 - v['right_clear'][2]):.1f}" + '" y="' + f"{220 * v['right_clear'][0]:.1f}" + '" width="' + f"{220 * 9 / 16 * v['right_clear'][2]:.1f}" + '" height="' + f"{220 * (v['right_clear'][1] - v['right_clear'][0]):.1f}" + '" fill="#FF6B35" opacity=".2"/>'))
    return "".join([
        fig_frame(3840, 2160, "16:9 film: 12 columns of 288, graphics safe 5% (EBU R95)", 0.05, 12),
        tall,
        fig_frame(1080, 1350, "4:5 social: 6% margin, 6 columns", 0.06, 6),
        fig_frame(1080, 1080, "1:1: 6% margin, 6 columns", 0.06, 6),
        fig_frame(1280, 640, "GitHub social: 6% margin", 0.06, 12),
        fig_frame(1584, 396, "LinkedIn banner: keep the left 25% clear", 0.06, 12, '<rect x="0" y="0" width="{W:.1f}" height="{H:.1f}" fill="none"/>'),
    ])


def fig_icon_keylines():
    s = 10
    m = MODES["mist"]
    ic = B["icon"]
    parts = [f'<rect width="{20 * s}" height="{20 * s}" fill="{m["surface-1"]}"/>']
    parts += [f'<line x1="{i * s}" y1="0" x2="{i * s}" y2="{20 * s}" stroke="{m["line"]}" stroke-width=".5"/><line x1="0" y1="{i * s}" x2="{20 * s}" y2="{i * s}" stroke="{m["line"]}" stroke-width=".5"/>' for i in range(21)]
    p = ic["padding"] * s
    parts.append(f'<rect x="{p}" y="{p}" width="{20 * s - 2 * p}" height="{20 * s - 2 * p}" fill="{m["accent"]}" opacity=".08"/>')
    parts.append(f'<circle cx="{10 * s}" cy="{10 * s}" r="{ic["keylines"]["circle"] / 2 * s}" fill="none" stroke="{m["signal"]}" stroke-width="1.2"/>')
    q = ic["keylines"]["square"]
    parts.append(f'<rect x="{(20 - q) / 2 * s}" y="{(20 - q) / 2 * s}" width="{q * s}" height="{q * s}" rx="{ic["corner_outer"] * s}" fill="none" stroke="{m["signal"]}" stroke-width="1.2"/>')
    pw, ph = ic["keylines"]["portrait"]
    parts.append(f'<rect x="{(20 - pw) / 2 * s}" y="{(20 - ph) / 2 * s}" width="{pw * s}" height="{ph * s}" rx="{ic["corner_outer"] * s}" fill="none" stroke="{m["accent"]}" stroke-width="1" stroke-dasharray="4 3"/>')
    lw, lh = ic["keylines"]["landscape"]
    parts.append(f'<rect x="{(20 - lw) / 2 * s}" y="{(20 - lh) / 2 * s}" width="{lw * s}" height="{lh * s}" rx="{ic["corner_outer"] * s}" fill="none" stroke="{m["accent"]}" stroke-width="1" stroke-dasharray="4 3"/>')
    parts.append(f'<circle cx="{15 * s}" cy="{10 * s}" r="{ic["dot"] / 2 * s}" fill="{m["ink"]}"/>')
    return f'<svg viewBox="0 0 {20 * s} {20 * s}" width="260" role="img" aria-label="Icon keylines">{"".join(parts)}</svg>'


def icons():
    out = []
    for p in sorted(glob.glob(os.path.join(ROOT, "art/icons/src/*-20.svg"))):
        n = os.path.basename(p)[:-7]
        if n.endswith("-fill"):
            continue
        out.append(f'<figure>{open(p).read().replace("<svg ", "<svg width=28 height=28 ")}<figcaption>{n}</figcaption></figure>')
    return "".join(out)


def fig_light():
    L = B["node3d"]["light"]
    W = H = 300
    cx, cy, r = 150, 150, 110
    m = MODES["mist"]
    parts = [f'<rect width="{W}" height="{H}" rx="16" fill="{m["surface-1"]}"/>',
             f'<rect x="{cx - 58}" y="{cy - 64}" width="116" height="128" rx="14" fill="{MODES["midnight"]["surface-1"]}"/>',
             f'<text x="{cx}" y="{cy + 4}" text-anchor="middle" font-family="Geist Mono" font-size="10" fill="{MODES["midnight"]["ink-2"]}">card</text>']
    for name, az, colr in (("key", L["key"]["azimuth"], m["accent"]), ("rim", L["rim"]["azimuth"], m["signal"])):
        x, y = cx + r * math.cos(math.radians(az)), cy - r * math.sin(math.radians(az))
        parts.append(f'<line x1="{x:.1f}" y1="{y:.1f}" x2="{cx}" y2="{cy}" stroke="{colr}" stroke-dasharray="4 4"/><circle cx="{x:.1f}" cy="{y:.1f}" r="12" fill="{colr}"/>'
                     f'<text x="{x:.1f}" y="{y + 28:.1f}" text-anchor="middle" font-family="Geist Mono" font-size="11" fill="{m["ink"]}">{name} {az}°</text>')
    parts.append(f'<path d="M{cx - 16},{cy + 128} L{cx},{cy + 104} L{cx + 16},{cy + 128} Z" fill="{m["ink"]}"/><text x="{cx + 22}" y="{cy + 126}" font-family="Geist Mono" font-size="11" fill="{m["ink"]}">camera + fill</text>')
    return f'<svg viewBox="0 0 {W} {H + 10}" width="300" role="img" aria-label="Light plan, top view">{"".join(parts)}</svg>'


def fig_channels():
    out = []
    for w, h, n in ((1200, 630, "Open Graph"), (1280, 720, "YouTube thumbnail"), (1080, 1920, "Shorts / Reels"), (1080, 1350, "Instagram 4:5"),
                    (1600, 900, "X post"), (1500, 500, "X header"), (1584, 396, "LinkedIn banner"), (1280, 640, "GitHub social"), (2560, 1440, "YouTube banner")):
        sc = 120 / 1920
        extra = ""
        if n == "YouTube banner":
            extra = f'<rect x="{(2560 - 1546) / 2 * sc:.1f}" y="{(1440 - 423) / 2 * sc:.1f}" width="{1546 * sc:.1f}" height="{423 * sc:.1f}" fill="#FF6B35" opacity=".35"/>'
        out.append(f'<figure class="ch"><svg viewBox="0 0 {w * sc:.1f} {h * sc:.1f}" width="{w * sc:.0f}" height="{h * sc:.0f}"><rect width="100%" height="100%" rx="4" fill="#151930"/>{extra}</svg><figcaption>{n}<code>{w}×{h}</code></figcaption></figure>')
    return "".join(out)


def img(n, alt, cls=""):
    if n not in IMGS:
        return f'<div class="noimg">{E(alt)} (run tools/brand/build_3d.py)</div>'
    return f'<img class="{cls}" src="img/{n}.webp" alt="{E(alt)}">'


def table(head, rows):
    return '<table class="t"><tr>' + "".join(f"<th>{E(h)}</th>" for h in head) + "</tr>" + "".join("<tr>" + "".join(f"<td>{c}</td>" for c in r) + "</tr>" for r in rows) + "</table>"


# ---------------------------------------------------------------- content blocks
N3 = B["node3d"]
type_rows = "".join(
    f'<tr><td>{s["step"]}</td><td><span style="font-family:{"Geist Mono" if "mono" in s["step"].lower() else "Geist"};font-weight:{s["weight"]};letter-spacing:{s["tracking"]}em;line-height:{s["leading"]};font-size:{fluid(s["min"], s["max"])};{"text-transform:uppercase;" if "caps" in s["step"] else ""}">'
    f'{"Patch anything into anything" if s["min"] >= 20 else "A cable carries a signal from one node to the next. 120 BPM, 4.00 ms."}</span></td><td><code>{s["min"]:g}→{s["max"]:g} / {s["weight"]} / {s["leading"]} / {s["tracking"]:+g}em</code></td></tr>'
    for s in B["type"]["web_scale"])
fams = "".join(f'<div class="fam"><b class="f{i}">{E(f["name"])}</b><code>{", ".join(map(str, f["weights"])) or "drawn"}</code><p>{E(f["role"])}</p></div>' for i, f in enumerate(B["type"]["families"]))
spring_rows = [[f'<b>{s["name"]}</b>', f'{s["zeta"]}', f'{s["omega"]}', f'{s["overshoot"] * 100:.1f}%', f'{s["settle_ms"]} ms', f'{s["response"]:.3f} s / {s["zeta"]}', E(s["role"])] for s in SPRINGS]
radii = "".join(f'<div class="rd"><div style="border-radius:{min(r["px"], 44)}px"></div><b>{r["name"]}</b><code>{"pill" if r["px"] == 999 else str(r["px"]) + " px"}</code><span>{E(r["role"])}</span></div>' for r in B["shape"]["brand_radius"])
space = "".join(f'<div class="spc"><i style="width:{s}px"></i><code>{s}</code></div>' for s in B["shape"]["space"])
cats = "".join(f'<div class="ct"><i style="background:{c["hex"]}"></i><b>{c["name"]}</b><code>{c["hex"]}</code></div>' for c in C["category"])
roles = "".join(f'<div class="ct"><i style="background:{r["dark"]}"></i><i style="background:{r["light"]}"></i><b>{r["name"]}</b></div>' for r in C["role"])
retired = [[f'<span class="dot" style="background:{r["hex"]}"></span><s>{r["hex"]}</s> {E(r["name"])}', E(r["now"]), E(r["why"])] for r in C["retired"]]
channels = [[E(c["channel"]), E(c["asset"]), f'<code>{E(c["size"])}</code>', E(c["mode"])] for c in B["channels"]]
g = C["gradient"]
grad_css = f"linear-gradient(90deg,{','.join(f'{h} {p * 100:g}%' for h, p in zip(g['stops'], g['positions']))})"
irid_css = f"linear-gradient(90deg,{','.join(C['iridescence']['stops'])})"
MID, MIST, PAP = MODES["midnight"], MODES["mist"], MODES["paper"]

z_rows = [[k.replace("_", " "), f'{v:+g}'] for k, v in sorted(N3["z"].items(), key=lambda kv: kv[1])]
mat_rows = [[k, E(str(v.get("base"))), str(v.get("roughness", "")), "glass coat" if v.get("glass") else ("metal" if v.get("metallic") else "")] for k, v in N3["materials"].items()]

process = [
    ("Capture", "Start from the real node: its body in code (sizes from element-sizes.md and AppShared.h), a screenshot at 100%, the live values a user would set."),
    ("Lay out flat", "Rebuild the panel as vectors in app pixels: cells, wells, captions, pins. The top view must match the app before anything gets depth."),
    ("Assign a z", "Every component gets one height from the z table. Wells go down, prints stay flush, controls come up, caps sit highest. Nothing floats."),
    ("Give it a material", "Matte body, satin knobs, glossy display, printed type. Colour comes from the mode roles; category colour only on the title strip, jacks and cables."),
    ("Light it once", "Key upper-left behind (135°, 50°), rim upper-right behind, fill from the camera. Shadows always on and soft, contact shadow 0.25."),
    ("Frame it", "3/4 view, yaw 20-30°, pitch 25-35°, 50 mm. One angle family per film; the camera sweeps sideways, it does not orbit."),
    ("Make it live", "Knobs turn with the soft spring, keys press with the press spring, the viewer and meters keep moving, the key cable lands with the slab spring."),
    ("Check side by side", "Put the render next to the app screenshot. Same order, same labels, same values. If a control is missing or added, it is wrong."),
]
r7 = [
    ("Flat textures skewed in 2.5D, so cards looked warped", "Real geometry: an 18 u slab with a 3 u fillet, recessed wells, raised controls"),
    ("Outlines on cards and controls", "No outlines: edges come from the fillet catching the key light"),
    ("Win95 bevel blocks for buttons", "Pill keycaps on a shallow well: rest +6, pressed +2.5, LED for state"),
    ("Dark cylinders for knobs, value arc floating in the air", "Skirt + knurled cap + engraved Moon pointer; the arc is printed on the panel at 1.12 r"),
    ("Labels baked tiny into a texture", "Captions are printed geometry in Geist, 13 u, at the app's caption gap of 4"),
    ("No shadows, objects floated, no key light", "One key light, soft shadows on, contact shadow 0.25, ground in the mode colour"),
    ("Glossy neon cables with big ball ends and glow", "Matte 5 u tubes, real plugs seated in side-wall jacks, catenary sag to the floor, no glow"),
]
grammar = [
    ("Land", "An object arrives and settles: soft spring, 4-8 u of travel, 200-320 ms. Slabs and the key cable use the slab spring."),
    ("Patch", "A cable draws from pin to pin: ease-out over 320-480 ms, plug snaps with the slab spring, the destination answers within 100 ms."),
    ("Carry", "Between scenes an object travels and becomes the next frame (iris, zoom to a rect, carried object). No cuts on a beat that has motion."),
    ("Live", "Anything that shows a value keeps moving: knobs breathe ±2°, waveforms scroll, meters fall. A frozen UI reads as a screenshot."),
    ("Breathe", "One slow loop under everything (4-8 s): the ball's iridescence, the gradient sweep. Never on type, stops for reduced motion."),
]
assets = [
    ("Invest", "Lemniscate mark · Ember key cable · the digit bird · mono folio system", "Unique and already recognised; use in every film and post"),
    ("Keep", "Brand gradient (logo only) · Caveat hand word · Patch Type slabs · iridescent ball", "Distinctive but easy to overuse: one per frame"),
    ("Restrain", "Dot grid (texture only, ≤6% opacity) · frosted glass", "Generic to the category; NN/g found translucency costs legibility"),
    ("Retire", "Violet glow · Instrument Serif · coral as accent · terracotta", "Competed with Signal and Ember; diluted the two-ends idea"),
]
fmt = [
    ("Units", "Number, thin space, unit: 120 BPM, 4.00 ms, 1.20 kHz, -6.0 dB, 48 kHz / 24-bit"),
    ("Dates", "ISO in data and filenames (2026-10-10); 10 October 2026 in prose"),
    ("Versions", "v0.5.0 with the v; release names in sentence case"),
    ("Node names", "Exactly as the app spells them, Title Case: Audio Filter, Color Ramp, Liquid Glass"),
    ("Keys", "Cmd/Ctrl + K, keycap chips in mono; macOS first, then Windows/Linux"),
    ("Files and code", "Geist Mono: tools/brand/build_3d.py, .inf, P.y += bass * 2"),
    ("Case", "Sentence case for headings and buttons; lowercase for Patch Type slabs; mono caps only for folios"),
    ("Punctuation", "No em dashes, no exclamation marks, straight quotes in code, curly quotes in prose"),
    ("Spelling", "British in prose (colour, centre); node and API names keep the app's spelling"),
    ("Numbers", "Tabular figures for values that change; minus sign for negatives in display type"),
]
research = [
    ("Colour space", "OKLab / OKLCH", "Ottosson 2020; CSS Color 4", "Ramps keep perceived lightness at one hue; gamut mapped by chroma reduction"),
    ("Contrast floor", "WCAG 2.2 AA/AAA", "W3C 2023", "Build fails below the gate"),
    ("Perceptual contrast", "APCA Lc (guide only)", "Removed from the WCAG 3 draft in 2023; WCAG 3 WD March 2026 still has no contrast method", "Printed beside each pair, never used to pass"),
    ("Colour vision", "Machado, Oliveira, Fernandes 2009", "IEEE TVCG", "Ember vs Signal checked under protan, deutan, tritan"),
    ("Polarity", "Positive polarity reads faster", "Piepenbrock et al. 2013", "Reading surfaces are Paper; Midnight for showcase and film"),
    ("Translucency", "Glass hurts legibility", "NN/g, Budiu, Liquid Glass, Oct 2025", "Glass only behind short labels, 72-78% opacity, never behind body text"),
    ("Expressive UI", "Shape, colour and motion raise speed of finding key actions", "Google Material 3 Expressive, 46 studies, 18,000+ people, 2025", "One accent action per view, springs for state changes"),
    ("Tokens", "DTCG 2025.10, first stable", "W3C Community Group, 28 Oct 2025", "brand.tokens.json is emitted in that format"),
    ("Aesthetic-usability", "Beautiful UI is judged easier to use", "Kurosu and Kashimura 1995", "Polish is not decoration; it carries trust"),
    ("Animation", "Slow in/out, follow-through, squash", "Chang and Ungar 1993; Thomas and Johnston 1981", "Springs with measured overshoot, no linear moves"),
    ("Response time", "0.1 / 1 / 10 s; 400 ms", "Nielsen 1993; Doherty and Thadani 1982", "UI motion ≤200 ms, values never animate"),
    ("Icons", "Labels beat icons alone", "Wiedenbeck 1999; McDougall et al. 2000", "Icons pair with a label on first use and in menus"),
    ("Line length", "45-75 characters", "Bringhurst; Dyson 2004", "Body measure 60-72 ch"),
    ("Brand assets", "Fame × uniqueness audit", "Romaniuk, Building Distinctive Brand Assets, 2018", "The invest / keep / restrain / retire table"),
    ("Captions", "≤17 characters per second", "Netflix timed-text guide; BBC subtitle guidelines", "Kinetic type ≤15 cps"),
    ("Safe areas", "Action 3.5%, graphics 5%", "EBU R95", "Film grid"),
]

# ---------------------------------------------------------------- page
css = open(os.path.join(DOC, "brand.css")).read()
page = f'''<!doctype html><html lang="en" data-mode="paper"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Infinite Brand Book</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Caveat:wght@700&family=Geist:wght@400;500;600;700;800&family=Geist+Mono:wght@400;500&display=swap" rel="stylesheet">
<style>
{css}
*{{box-sizing:border-box}}html{{-webkit-text-size-adjust:100%}}body{{margin:0;background:var(--ground);color:var(--ink);font:400 1rem/1.55 Geist,system-ui,sans-serif;-webkit-font-smoothing:antialiased}}
code{{font:500 .76rem/1.4 'Geist Mono',monospace;letter-spacing:.02em}}main{{max-width:1200px;margin:0 auto;padding:0 clamp(16px,4vw,48px)}}
h1,h2,h3,h4{{margin:0}}h2{{font:var(--type-h2);letter-spacing:var(--track-h2);margin:0 0 10px}}h3{{font:var(--type-h3);letter-spacing:var(--track-h3);margin:40px 0 14px}}h4{{font-weight:650;font-size:1rem;margin-bottom:8px}}
.k{{font:500 11px/1.2 'Geist Mono';letter-spacing:.12em;color:var(--accent-ink);text-transform:uppercase;display:block;margin-bottom:12px}}
p.s{{color:var(--ink-2);max-width:68ch;margin:0 0 24px}}section{{padding:clamp(48px,7vw,88px) 0}}section+section{{border-top:1px solid var(--line)}}
.hero{{background:{MID["ground"]};color:{MID["ink"]};padding:clamp(40px,8vw,96px) 0;overflow:hidden}}
.hero .mk{{width:min(360px,70vw)}}.hero h1{{font:var(--type-display);letter-spacing:var(--track-display);margin:28px 0 12px}}
.hand{{font:700 1.7rem Caveat,cursive;color:{MID["accent"]};transform:rotate(-2deg);display:inline-block;margin:0}}
.lead{{max-width:62ch;color:{MID["ink-2"]};font:var(--type-lead)}}.toc{{display:flex;flex-wrap:wrap;gap:8px;margin-top:28px}}.toc a{{font:500 12px 'Geist Mono';color:{MID["ink"]};text-decoration:none;padding:8px 12px;border-radius:999px;background:{MID["surface-1"]}}}
.cards{{display:grid;gap:16px;grid-template-columns:repeat(auto-fit,minmax(min(100%,260px),1fr))}}.card{{background:var(--surface-1);border-radius:var(--radius-card);padding:24px}}.card b{{display:block;margin-bottom:6px}}.card p{{margin:0;color:var(--ink-2);font-size:.92rem}}
.dk{{background:{MID["ground"]};color:{MID["ink"]};border-radius:var(--radius-card);padding:clamp(16px,3vw,32px)}}.dk p{{color:{MID["ink-2"]}}}
.two{{display:grid;gap:24px;grid-template-columns:repeat(auto-fit,minmax(min(100%,340px),1fr));align-items:start}}
svg{{max-width:100%;height:auto;display:block}}figure{{margin:0}}
.ramp{{margin-bottom:24px}}.rr{{display:grid;grid-template-columns:repeat(11,1fr);border-radius:var(--radius-media);overflow:hidden}}.rc{{padding:12px 8px;min-height:110px;display:flex;flex-direction:column;justify-content:flex-end;gap:2px;font-size:.78rem;position:relative}}.rc code{{font-size:.66rem}}.rc small{{font:500 .6rem 'Geist Mono';opacity:.75}}.rc i{{position:absolute;top:8px;left:8px;font:500 .58rem 'Geist Mono';font-style:normal;text-transform:uppercase;letter-spacing:.08em}}.ramp p{{color:var(--ink-2);font-size:.88rem;margin:8px 0 0}}
@media(max-width:760px){{.rr{{grid-template-columns:repeat(4,1fr)}}}}
.modes{{display:grid;gap:16px;grid-template-columns:repeat(auto-fit,minmax(min(100%,320px),1fr))}}.mode{{border-radius:var(--radius-card);padding:20px}}.mh b{{font-size:1.2rem;display:block}}.mh span{{font-size:.82rem}}.msurf{{border-radius:var(--radius-media);padding:16px;margin:16px 0}}.msurf p{{margin:0 0 6px}}
.btn{{display:inline-flex;height:36px;align-items:center;padding:0 16px;border-radius:999px;font-weight:600;font-size:.88rem}}
.chips{{display:grid;grid-template-columns:1fr 1fr;gap:6px}}.chip{{display:grid;grid-template-columns:16px 1fr auto;gap:8px;align-items:center;font-size:.76rem}}.chip i{{width:16px;height:16px;border-radius:5px;box-shadow:inset 0 0 0 1px rgba(128,128,160,.35)}}.chip b{{font-weight:500}}
.t{{width:100%;border-collapse:collapse;font-size:.88rem}}.t th{{text-align:left;font:500 11px 'Geist Mono';letter-spacing:.08em;text-transform:uppercase;color:var(--ink-3);padding:8px;border-bottom:1px solid var(--line)}}.t td{{padding:10px 8px;border-bottom:1px solid var(--line);vertical-align:top}}
.tw{{overflow-x:auto}}.ok{{color:#1E9646;font-weight:600}}.no{{color:var(--accent-ink);font-weight:600}}.dot{{display:inline-block;width:12px;height:12px;border-radius:50%;margin-right:8px;vertical-align:-1px;box-shadow:inset 0 0 0 1px rgba(128,128,160,.35)}}
.cvds{{border-radius:var(--radius-card);padding:20px;color:{MID["ink"]}}}.cvd{{display:grid;grid-template-columns:70px 1fr auto;gap:12px;align-items:center;margin-bottom:10px}}.cvd div{{display:flex;gap:6px}}.cvd i{{flex:1;height:34px;border-radius:10px}}.cvd span{{font:500 .74rem 'Geist Mono';color:{MID["ink-2"]}}}.cvds p{{font-size:.78rem;color:{MID["ink-3"]};margin:12px 0 0}}
@media(max-width:560px){{.cvd{{grid-template-columns:1fr}}}}
.bar{{height:72px;border-radius:var(--radius-media)}}
.cg{{display:grid;gap:8px;grid-template-columns:repeat(auto-fill,minmax(200px,1fr))}}.ct{{display:flex;gap:8px;align-items:center;background:var(--surface-1);border-radius:12px;padding:10px 12px;font-size:.86rem}}.ct i{{width:14px;height:14px;border-radius:50%}}.ct code{{margin-left:auto;color:var(--ink-3)}}
.fams{{display:grid;gap:16px;grid-template-columns:repeat(auto-fit,minmax(min(100%,240px),1fr));margin-bottom:24px}}.fam{{background:var(--surface-1);border-radius:var(--radius-card);padding:24px}}.fam b{{font-size:1.9rem;font-weight:700;display:block;letter-spacing:-.02em}}.fam .f1{{font-family:'Geist Mono';font-weight:500;letter-spacing:0}}.fam .f2{{font:700 2.4rem Caveat;color:var(--accent)}}.fam .f3{{font-family:'Geist Mono';letter-spacing:.2em}}.fam p{{margin:8px 0 0;color:var(--ink-2);font-size:.88rem}}
.spec td:nth-child(2){{max-width:0;width:60%}}.spec span{{display:block;overflow-wrap:anywhere}}
.rds{{display:grid;gap:16px;grid-template-columns:repeat(auto-fit,minmax(min(100%,220px),1fr))}}.rd{{background:var(--surface-1);border-radius:var(--radius-card);padding:20px;display:flex;flex-direction:column;gap:4px}}.rd div{{height:88px;background:{MID["surface-1"]};margin-bottom:10px}}.rd span{{color:var(--ink-2);font-size:.84rem}}
.spcs{{display:flex;flex-direction:column;gap:6px}}.spc{{display:flex;align-items:center;gap:12px}}.spc i{{height:12px;background:var(--signal);border-radius:3px}}
.frs{{display:flex;flex-wrap:wrap;gap:24px;align-items:flex-end}}.fr figcaption,.ch figcaption{{font-size:.8rem;color:var(--ink-2);margin-top:8px;max-width:260px;display:flex;flex-direction:column}}
.chs{{display:flex;flex-wrap:wrap;gap:20px;align-items:flex-end}}
.icons{{display:grid;grid-template-columns:repeat(auto-fill,minmax(84px,1fr));gap:4px;background:{MID["ground"]};color:{MID["ink"]};border-radius:var(--radius-card);padding:16px}}.icons figure{{display:flex;flex-direction:column;align-items:center;gap:6px;padding:10px 0}}.icons figcaption{{font:500 .58rem 'Geist Mono';color:{MID["ink-3"]};text-align:center}}
.shot{{width:100%;border-radius:var(--radius-card);display:block;background:{MID["ground"]}}}.cap{{font-size:.84rem;color:var(--ink-2);margin:10px 0 0}}
.steps{{counter-reset:s;display:grid;gap:12px;grid-template-columns:repeat(auto-fit,minmax(min(100%,250px),1fr))}}.steps div{{background:var(--surface-1);border-radius:var(--radius-card);padding:20px}}.steps div:before{{counter-increment:s;content:counter(s,decimal-leading-zero);font:500 11px 'Geist Mono';color:var(--accent-ink);letter-spacing:.1em;display:block;margin-bottom:8px}}.steps b{{display:block;margin-bottom:4px}}.steps p{{margin:0;color:var(--ink-2);font-size:.88rem}}
.noimg{{padding:40px;border-radius:var(--radius-card);background:var(--surface-1);color:var(--ink-3)}}
pre{{background:{MID["ground"]};color:{MID["ink-2"]};border-radius:var(--radius-media);padding:16px;overflow-x:auto;font:500 .72rem/1.5 'Geist Mono'}}
footer.f{{padding:48px 0;color:var(--ink-3);font-size:.85rem}}
</style></head><body>
<header class="hero"><main>
<div class="mk">{mark(100, gid="gh")}</div>
<h1>Two ends, one loop.</h1><p class="hand">the brand book</p>
<p class="lead">{E(B["idea"]["concept"])}</p>
<nav class="toc"><a href="#idea">Idea</a><a href="#mark">Mark</a><a href="#colour">Colour</a><a href="#type">Type</a><a href="#grid">Grid</a><a href="#shape">Shape</a><a href="#icons">Icons</a><a href="#motion">Motion</a><a href="#node3d">Node in 3D</a><a href="#kit">3D kit</a><a href="#channels">Channels</a><a href="#format">Formatting</a><a href="#assets">Assets</a><a href="#research">Research</a></nav>
</main></header>
<main>
<section id="idea"><span class="k">01 · Idea</span><h2>Connection, drawn as one line</h2><p class="s">Infinite is a canvas where anything patches into anything. The mark is a single closed line with two ends of one colour field. Every surface uses those two ends and the space between them.</p>
<div class="cards">
<div class="card"><b style="color:var(--accent-ink)">Ember, the warm end</b><p>The human act: the hand word, the key cable, the one call to action. Hue 38. One per frame, under 10% of its area.</p></div>
<div class="card"><b style="color:var(--signal)">Signal, the cool end</b><p>Structure: lines, diagrams, data, focus, selection. Hue 276, on the same hue as Midnight so it never fights the ground.</p></div>
<div class="card"><b>Midnight, the space</b><p>Every neutral sits on hue 274: Midnight grounds, Moon inks, Mist and Paper for reading. Never pure black or white.</p></div>
<div class="card"><b>Personality</b><p>{E(", ".join(B["idea"]["personality"]))}. The line: <b style="display:inline">{E(B["idea"]["line"])}</b></p></div>
</div></section>

<section id="mark"><span class="k">02 · Mark</span><h2>A lemniscate of Bernoulli</h2><p class="s">{E(B["logo"]["curve"])}. The stroke is 87/338 of A, so the mark keeps its weight at every size. Draw it from the formula, never trace it.</p>
<div class="two"><div>{fig_construction()}</div><div class="tw">{table(["measure", "value"], [[E(k.replace("_", " ")), f"<code>{E(', '.join(f'{a} {b} px' for a, b in v.items()) if isinstance(v, dict) else str(v))}</code>"] for k, v in B["logo"].items() if k != "curve"])}</div></div>
<h3>On every ground</h3><div class="cards">
<div class="card" style="background:{MID["ground"]}"><div style="width:70%;margin:12px auto">{mark(100, gid="g1")}</div><p style="color:{MID["ink-2"]}">Midnight: default.</p></div>
<div class="card" style="background:{MIST["ground"]}"><div style="width:70%;margin:12px auto">{mark(100, gid="g2")}</div><p>Mist: allowed.</p></div>
<div class="card" style="background:{PAP["surface-1"]}"><div style="width:70%;margin:12px auto">{mark(100, gid="g3")}</div><p>Paper: allowed at 24 px and up (the light stops are soft on white).</p></div>
<div class="card"><p><b>Never</b>recolour the stops, rotate, outline, add a glow or shadow to the flat mark, put it on a photo without a Midnight tile, or set it below 20 px wide (16 px for the tile icon).</p></div>
</div></section>

<section id="colour"><span class="k">03 · Colour</span><h2>Three families, three modes</h2><p class="s">Every colour is set in OKLCH so lightness steps look even. Anchors (marked) are the owner-approved values from the v0.5 films; the rest of each ramp is generated on the same hue.</p>
{fig_ramp("midnight")}{fig_ramp("signal")}{fig_ramp("ember")}
<h3>Modes</h3><p class="s">One mode per scene or page section. Midnight for showcase, film and social; Mist for diagrams; Paper for reading. Roles, not hexes, go into designs.</p>
<div class="modes">{"".join(mode_panel(n, r) for n, r in MODES.items())}</div>
<h3>Contrast gate</h3><p class="s">The build fails if any pair below misses its ratio. APCA Lc is shown for perceptual sense only (WCAG 3 has no contrast method yet).</p><div class="tw">{gate_table()}</div>
<h3>Colour vision</h3><p class="s">The two ends stay apart for every common colour-vision type, so the warm/cool split works without hue.</p>{cvd_strip()}
<h3>Gradient and iridescence</h3><div class="bar" style="background:{grad_css}"></div><p class="cap">{E(g["role"])}</p><div class="bar" style="background:{irid_css};margin-top:16px"></div><p class="cap">{E(C["iridescence"]["role"])}</p>
<h3>Category and role colours</h3><p class="s">Owned by the app (src/core/CategoryColors.cpp). On brand surfaces they appear only where a node appears: title strip, pins, cables.</p><div class="cg">{cats}</div><div class="cg" style="margin-top:12px">{roles}</div>
<h3>Category collisions (app report)</h3><p class="s">Pairs closer than ΔE 6 under some vision type. Not a brand change: logged for the infinite-design-system owner, because on a busy canvas these pairs are confusable.</p><div class="tw">{collisions()}</div>
<h3>Retired in v2</h3><div class="tw">{table(["was", "now", "why"], retired)}</div></section>

<section id="type"><span class="k">04 · Type</span><h2>Four voices, no fifth</h2><div class="fams">{fams}</div>
<p class="s">Text steps follow a major third (1.25); display steps jump about 1.5. Sizes are fluid between 375 and 1440 px viewports. Tracking tightens as size grows; mono and caps open up.</p>
<div class="tw"><table class="t spec">{type_rows}</table></div>
<h3>Film scale (4K stage)</h3><div class="tw">{table(["step", "px", "weight"], [[s["step"], f'<code>{s["px"]}</code>', str(s["weight"])] for s in B["type"]["film_scale_4k"]])}</div>
<p class="cap">Measure: body {B["type"]["measure"]["body_ch"][0]}-{B["type"]["measure"]["body_ch"][1]} ch, captions {B["type"]["measure"]["caption_ch"][0]}-{B["type"]["measure"]["caption_ch"][1]} ch. Kinetic type at most {B["type"]["measure"]["film_chars_per_second"]} characters per second.</p></section>

<section id="grid"><span class="k">05 · Grid</span><h2>Grids per format</h2><p class="s">Web: 12 columns, max 1200, gutters 16/24/32, 8 px base. Film: 12 columns of 288 on a 3840 stage inside the 5% graphics-safe area. Social: 6% margins, 6 columns. Docs: A4, 18 mm margins, 4 pt baseline.</p><div class="frs">{grids()}</div></section>

<section id="shape"><span class="k">06 · Shape, space, depth</span><h2>Concentric and borderless</h2><div class="rds">{radii}</div>
<p class="s" style="margin-top:20px">Inner radius = outer radius - padding (24 - 8 = 16). Space is an 8 px scale with 4 and 12 as half steps. Depth comes from surface steps and layered soft shadows, never from outlines.</p>
<div class="two"><div class="spcs">{space}</div><div class="tw">{table(["level", "midnight", "shadow"], [[str(e["level"]), e["midnight"], f'<code>{e["shadow"]}</code>'] for e in B["shape"]["elevation"]])}</div></div></section>

<section id="icons"><span class="k">07 · Iconography</span><h2>20 grid, 1.5 stroke, one dot</h2>
<div class="two"><div>{fig_icon_keylines()}<p class="cap">Keylines: circle 16, square 14, portrait 12×16, landscape 16×12, 2 px padding. Stroke 1.25 at 16, 1.5 at 20, 1.75 at 24. Corners 2 outside, 1 inside. The 3 px dot is the same dot as a pin.</p></div>
<div class="cards"><div class="card"><b>Pair with words</b><p>An icon alone only for universal actions (play, stop, record, close). Everywhere else a label sits beside it.</p></div><div class="card"><b>One family</b><p>Line by default; the -fill variant shows the on state, never decoration.</p></div></div></div>
<div class="icons" style="margin-top:24px">{icons()}</div></section>

<section id="motion"><span class="k">08 · Motion</span><h2>Springs you can measure</h2><p class="s">Overshoot = exp(-πζ/√(1-ζ²)). Settle (2%) ≈ 4/(ζω). For SwiftUI, response = 2π/ω and dampingFraction = ζ. For CSS, use the generated linear() curves in brand.css.</p>
<div class="two"><div>{fig_springs()}</div><div class="tw">{table(["spring", "ζ", "ω", "overshoot", "settle", "SwiftUI", "use"], spring_rows)}</div></div>
<h3>Grammar</h3><div class="tw">{table(["verb", "what it means"], [[f"<b>{a}</b>", E(b)] for a, b in grammar])}</div>
<h3>Durations</h3><div class="tw">{table(["token", "ms"], [[k, str(v)] for k, v in B["motion"]["durations_ms"].items()])}</div>
<p class="cap">In the app, motion stays at or under 200 ms and values never animate (they are data). Every brand motion stops for prefers-reduced-motion.</p>
<pre>--spring-slab: {E(SPRINGS[0]["linear"])};</pre></section>

<section id="node3d"><span class="k">09 · The node in 3D</span><h2>The node as an instrument</h2><p class="s">A node in 3D is a physical panel, like a pedal or a module, built from the app's own measurements. It is not a screenshot tilted in space. Reference: {E(N3["reference"])}.</p>
<figure>{img("node_hero", "Audio Filter as a 3D instrument object, Ember key cable in, category cable out", "shot")}<figcaption class="cap">Audio Filter, rendered from tools/brand/build_3d.py. Every size is from the app: 56 knobs in 110 cells, 190 viewer, 21 readout, 4 caption gap.</figcaption></figure>
<h3>Process</h3><div class="steps">{"".join(f"<div><b>{a}</b><p>{E(b)}</p></div>" for a, b in process)}</div>
<h3>Flat first, then depth</h3><div class="two"><figure>{img("node_top", "Top view: must match the app layout", "shot")}<figcaption class="cap">Step 2: the top view has to match the app before anything gets depth.</figcaption></figure><figure>{img("node_exploded", "Exploded view: body, print, controls, caps", "shot")}<figcaption class="cap">Steps 3-4: body, then printed layer (+0), controls, caps. Nothing floats in the final object.</figcaption></figure></div>
<h3>Anatomy</h3><div class="two"><figure>{img("knob_macro", "Knob close-up: skirt, knurled cap, engraved pointer, printed arc", "shot")}<figcaption class="cap">Knob: one size, 56. Skirt, knurled cap at 0.78 r, engraved Moon pointer, value arc printed on the panel in Signal, modulation arc outside it in the Modulation colour.</figcaption></figure>
<div><div class="tw">{table(["component", "z (u)"], z_rows)}</div><div class="tw" style="margin-top:16px">{table(["material", "base", "roughness", ""], mat_rows)}</div></div></div>
<h3>Light and camera</h3><div class="two"><div>{fig_light()}</div><div class="tw">{table(["", "rule"], [["Key", "135° az, 50° el, soft (5° sun angle)"], ["Rim", "45° az, 35° el, 0.6 of key"], ["Fill", "from the camera, 0.35 of key"], ["Shadows", "always on, contact 0.25, ground in the mode colour"], ["Camera", f'yaw {N3["camera"]["yaw"][0]}-{N3["camera"]["yaw"][1]}°, pitch {N3["camera"]["pitch"][0]}-{N3["camera"]["pitch"][1]}°, {N3["camera"]["lens_mm"]} mm'], ["Spec views", E(N3["camera"]["spec_view"])], ["Colour", "Standard view transform, so brand hexes stay true"]])}</div></div>
<h3>What went wrong in the film, and the rule now</h3><div class="tw">{table(["r7 film", "v2 rule"], [[E(a), E(b)] for a, b in r7])}</div>
<h3>Animation</h3><div class="tw">{table(["part", "motion"], [["Knob", "turns with the soft spring; idle breath ±2°"], ["Keycap", "down 80 ms with press spring, up 140 ms; LED fades 160 ms"], ["Switch", "thumb slides with the soft spring, track tints over 160 ms"], ["Cable", "draws pin to pin with ease-out, plug seats with the slab spring (12.6% overshoot)"], ["Viewer", "always live: curve and meters keep moving"]])}</div></section>

<section id="kit"><span class="k">10 · 3D kit</span><h2>Assets you can reuse</h2><p class="s">All in art/brand/3d: glTF (metres, 1 app px = 1 mm), kit.blend, renders. Regenerate with <code>python3 tools/brand/build_3d.py</code>.</p>
<figure>{img("kit_components", "Controls kit: knob, modulated knob, keycap, keycap on, switch, checkbox, dropdown, fader", "shot")}<figcaption class="cap">controls_kit.glb: every control from the element-size table at its app size.</figcaption></figure>
<div class="two" style="margin-top:24px"><figure>{img("logo_3d", "The mark as a 3D loop, over and under at the crossing", "shot")}<figcaption class="cap">logo_3d.glb: the two passes through the crossing separate by 1.24 strokes, so the loop reads over and under.</figcaption></figure><figure>{img("logo_tile", "App tile in 3D", "shot")}<figcaption class="cap">logo_tile.glb: Midnight tile, 22.5% corner, mark at 0.70 width.</figcaption></figure></div>
<div class="two" style="margin-top:24px"><figure>{img("brand_ball", "The iridescent brand ball", "shot")}<figcaption class="cap">brand_ball.glb: the one hero object, iridescence stops on a facing ramp under a clear coat.</figcaption></figure>
<div class="tw">{table(["file", "what"], [["node_audio_filter.glb", "the hero node with both cables"], ["controls_kit.glb", "knob, keycaps, switch, checkbox, dropdown, fader"], ["logo_3d.glb", "the loop"], ["logo_tile.glb", "app tile"], ["brand_ball.glb", "hero object"], ["kit.blend", "everything, with lights and cameras"]])}</div></div></section>

<section id="channels"><span class="k">11 · Channels</span><h2>Every place Infinite shows up</h2><div class="chs">{fig_channels()}</div><div class="tw" style="margin-top:24px">{table(["channel", "asset", "size", "mode"], channels)}</div></section>

<section id="format"><span class="k">12 · Formatting and voice</span><h2>Plain and specific</h2><div class="tw">{table(["", "rule"], [[f"<b>{a}</b>", E(b)] for a, b in fmt])}</div>
<div class="cards" style="margin-top:24px"><div class="card"><b>Say</b><p>A frosted glass pane that bends what is behind it. Patch anything into anything. A DAW for you.</p></div><div class="card"><b style="color:var(--accent-ink)">Never</b><p>“The world's first”, “revolutionary”, exclamation marks, em dashes, “free for now”, a second accent colour, a card with an outline.</p></div></div></section>

<section id="assets"><span class="k">13 · Distinctive assets</span><h2>Where to spend attention</h2><div class="tw">{table(["", "assets", "why"], [[f"<b>{a}</b>", E(b), E(c)] for a, b, c in assets])}</div></section>

<section id="research"><span class="k">14 · Research</span><h2>What the rules rest on</h2><div class="tw">{table(["topic", "finding", "source", "rule here"], [[E(a), E(b), E(c), E(d)] for a, b, c, d in research])}</div></section>
<footer class="f">Generated by tools/brand/build_brand_book.py from docs/brand/brand.json v{B["version"]} ({B["updated"]}). Edit the JSON or BRAND.md, never this file. Tokens: brand.css, brand.tokens.json.</footer>
</main></body></html>'''
open(os.path.join(DOC, "brand-book.html"), "w").write(page)
print(f"wrote docs/brand/brand-book.html {len(page) // 1024} KB, brand.css, brand.tokens.json, {len(IMGS)} images; contrast gate {len(GATE)} pairs pass")
