"""Category colour audit: which node categories look alike, per theme preset and per vision type.

What: parses every theme preset in src/core/CategoryColors.cpp (category colours and the panel colour), then for
each preset lists category pairs closer than deltaE OK 6 under normal, protan, deutan or tritan vision (the
brand book's collision threshold), and categories under 3:1 against the panel (a title strip that does not
read as coloured). Writes docs/plans/ui-system/category-colour-collisions.md for the infinite-design-system owner.
Why: on a busy canvas the category colour is how a patch is read at a glance; the brand book found confusable
pairs in the default preset, and every new preset or category can add more.

Usage:
    python3 tools/brand/category_audit.py                # write the report, print a summary
    python3 tools/brand/category_audit.py --preset Infinite
    python3 tools/brand/category_audit.py --stdout       # print the report instead of writing it
Category colours are theme-owned and user-editable, so the brand keeps no copy: other tools call app_categories()
(the default preset, for renders and CSS) or presets() (all of them).
Exit codes: 0 report written, 1 the Infinite preset has more near-identical pairs (deltaE under 3) than BASELINE_SAME
(the ratchet: lower it when a fix lands), 2 usage error.
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(__file__))
import colour as K  # noqa: E402

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
SRC = os.path.join(ROOT, "src", "core", "CategoryColors.cpp")
OUT = os.path.join(ROOT, "docs", "plans", "ui-system", "category-colour-collisions.md")
NEAR, SAME, MIN_CONTRAST = 6.0, 3.0, 3.0
BASELINE_SAME = 8  # Infinite preset, 2026-10-10
VISION = ("normal", "protan", "deutan", "tritan")


def hx(r, g, b):
    return "#%02X%02X%02X" % tuple(round(float(v) * 255) for v in (r, g, b))


def presets():
    text = open(SRC).read()
    body = text[text.index("RawPresets()"):]
    out, cur = [], None
    for line in body.splitlines():
        m = re.match(r'\s*\{\s*"([^"]+)",\s*\{\s*$', line)
        if m:
            cur = {"name": m.group(1), "cats": [], "panel": None}
            out.append(cur)
            continue
        m = re.match(r'\s*\{\s*"([^"]+)",\s*\{\s*([\d.]+)f?,\s*([\d.]+)f?,\s*([\d.]+)f?\s*\}', line)
        if m and cur is not None:
            cur["cats"].append((m.group(1), hx(*m.groups()[1:])))
            continue
        m = re.match(r'\s*\{?\s*\{\s*([\d.]+)f?,\s*([\d.]+)f?,\s*([\d.]+)f?\s*\},?\s*//\s*panel', line)
        if m and cur is not None:
            cur["panel"] = hx(*m.groups())
        if line.startswith("   };"):
            break
    return [p for p in out if p["cats"]]


def app_categories(preset="Infinite"):
    """[{name, hex}] for one theme preset (default: the app's default theme)."""
    p = next(p for p in presets() if p["name"] == preset)
    return [{"name": n, "hex": h} for n, h in p["cats"]]


def audit(p):
    pairs = []
    cats = p["cats"]
    for i, (na, a) in enumerate(cats):
        for nb, b in cats[i + 1:]:
            d = [(k, K.delta_e(a, b) if k == "normal" else K.delta_e(K.cvd(a, k), K.cvd(b, k))) for k in VISION]
            worst = min(d, key=lambda x: x[1])
            if worst[1] < NEAR:
                pairs.append((worst[1], na, a, nb, b, worst[0], dict(d)["normal"]))
    pairs.sort()
    low = [(n, h, K.wcag(h, p["panel"])) for n, h in cats if p["panel"] and K.wcag(h, p["panel"]) < MIN_CONTRAST]
    return pairs, low


def report(ps):
    lines = ["# Category colour collisions", "",
             "Generated by `python3 tools/brand/category_audit.py` from `src/core/CategoryColors.cpp`. Do not edit by hand.", "",
             f"A pair is listed when its colours are closer than deltaE OK {NEAR:g} under any vision type (about three "
             "just-noticeable steps; the brand book threshold). Under " f"{SAME:g} the two read as the same colour. "
             f"Contrast is WCAG against the preset's panel colour; under {MIN_CONTRAST:g}:1 a title strip stops reading as coloured.", "",
             "| Preset | Pairs under 6 | Of which under 3 | Categories under 3:1 on panel |", "|---|---|---|---|"]
    res = [(p, *audit(p)) for p in ps]
    for p, pairs, low in res:
        lines.append(f"| {p['name']} | {len(pairs)} | {sum(1 for x in pairs if x[0] < SAME)} | {len(low)} |")
    for p, pairs, low in res:
        lines += ["", f"## {p['name']}", ""]
        if pairs:
            lines += ["| Category | vs | Worst vision | deltaE worst | deltaE normal |", "|---|---|---|---|---|"]
            lines += [f"| {na} `{a}` | {nb} `{b}` | {k} | **{d:.1f}** | {dn:.1f} |" for d, na, a, nb, b, k, dn in pairs]
        else:
            lines.append("No pairs under the threshold.")
        if low:
            lines += ["", f"Under {MIN_CONTRAST:g}:1 on panel `{p['panel']}`: " + ", ".join(f"{n} `{h}` ({c:.1f}:1)" for n, h, c in low)]
    lines += ["", "## What to do with a pair", "",
              "1. Prefer separating by lightness (OKLCH L) over hue: it survives every vision type.",
              "2. If two categories never sit next to each other on a canvas (say Notes and Prediction), the pair can stay.",
              "3. Never rely on colour alone: the title text and pin shapes already carry the category.", ""]
    return "\n".join(lines), res


def main():
    args = sys.argv[1:]
    only = args[args.index("--preset") + 1] if "--preset" in args else None
    if set(a for a in args if a.startswith("--")) - {"--preset", "--stdout"}:
        print(__doc__)
        return 2
    ps = [p for p in presets() if not only or p["name"] == only]
    if not ps:
        print(f"no presets parsed from {os.path.relpath(SRC, ROOT)}" + (f" named {only}" if only else ""))
        return 2
    md, res = report(ps)
    if "--stdout" in args:
        print(md)
    else:
        os.makedirs(os.path.dirname(OUT), exist_ok=True)
        open(OUT, "w").write(md)
        print(f"wrote {os.path.relpath(OUT, ROOT)}")
    for p, pairs, low in res:
        print(f"  {p['name']:18} {len(pairs):2} pairs under {NEAR:g}, {sum(1 for x in pairs if x[0] < SAME)} under {SAME:g}, {len(low)} low-contrast")
    bad = 0
    inf = next((r for r in res if r[0]["name"] == "Infinite"), None)
    if inf:
        same = sum(1 for x in inf[1] if x[0] < SAME)
        if same > BASELINE_SAME:
            print(f"  worse: Infinite has {same} near-identical pairs, baseline {BASELINE_SAME}")
            bad = 1
    return bad


if __name__ == "__main__":
    sys.exit(main())
